- This is a revoluationary update for tc-ext-tools. Here are some of the headlines of the update - Storage directory layout changed - Default config and user config files installation path and names changed - Encrypt rule removed from package build rules functions, it is now placed in the build function of buildit - Build process execution time is printed when building ends with success - For other changes see diff

diff --git a/trunk/tools/boostit b/trunk/tools/boostit
--- a/trunk/tools/boostit
+++ b/trunk/tools/boostit
@@ -21,15 +21,15 @@
 #  with this program; if not, write to the Free Software Foundation, Inc.,
 #  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-#  (C) Copyright 2010 Sercan Arslan
+#  (C) Copyright 2011 Sercan Arslan
 #
 
 . /etc/init.d/tc-functions
 
 TCEXTTOOLS_ROOT="$(dirname $0)/.."
 
-if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
-     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
+if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
+     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
 else
      echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
@@ -41,7 +41,7 @@ EXTENSIONS="$3"
 
 print_usage(){
 
-   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extension1 extension2 ...\"${NORMAL}"
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} package version \"extension1 extension2 ...\"${NORMAL}"
 
 }
 
@@ -54,20 +54,20 @@ if [ -z "$EXTENSIONS" ]; then
      EXTENSIONS="$PACKAGE"
 fi
 
-print_it "You entered:\n\n\tPACKAGE=$PACKAGE\n\tVERSION=$VERSION\n\tEXTENSIONS=$EXTENSIONS\n"
+echo -e "${RED}${THIS}: Boosting the package with;\n\t${BLUE}PACKAGE=$PACKAGE\n\tVERSION=$VERSION\n\tEXTENSIONS=$EXTENSIONS\n${NORMAL}"
 
-if [ -e "$PACKAGE_COMMON" ]; then
-     print_it warning "Warning! This package looks to be boosted before.\nIf you continue existing files will be overwritten.\nWould you like you continue ? [y or n]"
+if [ -f "$PACKAGE_COMMON" ]; then
+     print_it warning "This package looks to be boosted before.\nIf you continue existing files will be overwritten.\nWould you like you continue ? [y or n]"
      read ans
      case "$ans" in
           y)
             print_it "You agreed to continue. The files will be overwritten."
             ;;
           n)
-            print_it "You don't want to continue ? Farewell then!"
+            print_it "You don't want to continue ? Farewell!"
             exit 0
             ;;
-          *) 
+          *)
             print_it error "I don't understand what you are saying!"
             exit 1
             ;;
@@ -80,9 +80,11 @@ fi
 
 this_main() {
 
-   if [ ! -d "$PACKAGE_EXTENSIONS" ]; then
-          install -m 755 -d "$PACKAGE_EXTENSIONS" || return 1
+   if [ -d "$PACKAGE_EXTENSIONS" ]; then
+        rm -rf "$PACKAGE_EXTENSIONS"
    fi
+
+   mkdir -p "$PACKAGE_EXTENSIONS" || return 1
 
    if [ "$VERSION" = "svn" ]; then
 
@@ -160,6 +162,7 @@ _EOF
        if [ ! "${EXTENSION%-locale}" = "$EXTENSION" ]; then
               echo "${EXTENSION%-locale}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
               echo "usr/local/share/locale" > "$PACKAGE_EXTENSIONS/$EXTENSION/install" || return 1
+              echo "x-usr/local/share/locale" > "$PACKAGE_EXTENSIONS/${EXTENSION%-locale}/install" || return 1
        elif [ ! "${EXTENSION%-dev}" = "$EXTENSION" ]; then
               echo "${EXTENSION%-dev}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
        fi
diff --git a/trunk/tools/compressit b/trunk/tools/compressit
--- a/trunk/tools/compressit
+++ b/trunk/tools/compressit
@@ -21,15 +21,15 @@
 #  with this program; if not, write to the Free Software Foundation, Inc.,
 #  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-#  (C) Copyright 2010 Sercan Arslan
+#  (C) Copyright 2011 Sercan Arslan
 #
 
 . /etc/init.d/tc-functions
 
 TCEXTTOOLS_ROOT="$(dirname $0)/.."
 
-if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions" ]; then
-     . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/functions"
+if [ -f "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh" ]; then
+     . "$TCEXTTOOLS_ROOT/etc/init.d/tc-ext-tools.sh"
 else
      echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
@@ -41,7 +41,7 @@ OPTIONS="$3"
 
 print_usage(){
 
-   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) bz2|gz|xz /path/to/target options${NORMAL}"
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} gz|bz2|xz /path/to/target options${NORMAL}"
 
 }
 
@@ -60,7 +60,7 @@ this_compress() {
         TOP_DIR="$(basename $TARGET)"
         OUTPUT="${TOP_DIR}.tar.${FORMAT}"
         [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
-        tar "$OPTIONS" -C $(dirname $TARGET) -c"${XXX}f" "$OUTPUT" "$TOP_DIR" || return 1
+        tar "$OPTIONS" -C "$(dirname $TARGET)" -cv${XYZ}f "$OUTPUT" "$TOP_DIR" || return 1
    elif [ -f "$TARGET" ]; then
         OUTPUT="$(basename $TARGET).${FORMAT}"
         [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
@@ -80,17 +80,17 @@ this_main() {
    case "$FORMAT" in
         bz2)
             COMPRESSOR="bzip2"
-            XXX=j
+            XYZ=j
             this_compress || return 1
             ;;
         gz)
             COMPRESSOR="gzip"
-            XXX="z"
+            XYZ="z"
             this_compress || return 1
             ;;
         xz)
             COMPRESSOR="xz"
-            XXX="J"
+            XYZ="J"
             this_compress || return 1
             ;;
         *)
@@ -103,7 +103,7 @@ this_main() {
 }
 
 print_it "Compressing the target $TARGET with the compression format $FORMAT ... \c"
-this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
+this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
