- This update implements a new stamp mechanism used for transitions

diff --git a/trunk/tools/configureit b/trunk/tools/configureit
--- a/trunk/tools/configureit
+++ b/trunk/tools/configureit
@@ -34,9 +34,14 @@ else
      exit 1
 fi
 
-if [ ! -d "$PACKAGE_SOURCE_TOPDIR" ]; then
-       echo "${ERROR_COLOR}You must unpack it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_UNPACK" -a ! -f "$PACKAGE_UNPACK_STAMP" ]; then
+     echo "${ERROR_COLOR}You must unpack it first!${NORMAL}"
+     exit 1
+fi
+
+if [ -n "$HAVE_TET_PATCH" -a ! -f "$PACKAGE_PATCH_STAMP" ]; then
+     echo "${ERROR_COLOR}You must patch it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
@@ -64,6 +69,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_CONFIGURE_STAMP" ] && sudo rm -f "$PACKAGE_CONFIGURE_STAMP"
+
 echo -e "${MESSAGE_COLOR}Configuring the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -72,6 +79,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_CONFIGURE_STAMP"
 
 exit 0
 
diff --git a/trunk/tools/unpackit b/trunk/tools/unpackit
--- a/trunk/tools/unpackit
+++ b/trunk/tools/unpackit
@@ -34,9 +34,9 @@ else
      exit 1
 fi
 
-if [ ! -f "$PACKAGE_SOURCE_ORIG" -a ! -f "$PACKAGE_SOURCE_CONV" ]; then
-       echo "${ERROR_COLOR}You must download it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_DOWNLOAD" -a ! -f "$PACKAGE_DOWNLOAD_STAMP" ]; then
+     echo "${ERROR_COLOR}You must download it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
@@ -86,6 +86,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_UNPACK_STAMP" ] && sudo rm -f "$PACKAGE_UNPACK_STAMP"
+
 echo -e "${MESSAGE_COLOR}Unpacking the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} source ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -94,6 +96,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_UNPACK_STAMP"
 
 exit 0
 
