- Update tc-ext-tools to merge suffix, icon, info, and new feature name into one file which one is called extension common file, with this update user can specify the name of the extension different than the package extension directory layout, and add a global or extension specific suffix. - Updated libgdata package

diff --git a/trunk/tools/createit b/trunk/tools/createit
--- a/trunk/tools/createit
+++ b/trunk/tools/createit
@@ -40,38 +40,36 @@ this_create() {
   cd $PACKAGE_ROOT
 
   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" ]; then
-       sudo install -m 775 -D "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" "$TCEXTTOOLS_BIN/$EXTENSION/usr/local/tce.installed/$EXTENSION" || return 1
-       sudo chown -R root:staff "$TCEXTTOOLS_BIN/$EXTENSION/usr/local/tce.installed" || return 1
-       sudo chmod -R 775 "$TCEXTTOOLS_BIN/$EXTENSION/usr/local/tce.installed" || return 1
+       sudo install -m 775 -D "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed/$EXTENSION_NAME" || return 1
+       sudo chown -R root:staff "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
+       sudo chmod -R 775 "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
   fi
 
   cd "$TCEXTTOOLS_BIN"
 
-  [ -e "${EXTENSION}.tcz" ] && sudo rm -f "${EXTENSION}.tcz"
-  [ -e "${EXTENSION}.tcz.list" ] && sudo rm -f "${EXTENSION}.tcz.list"
-  [ -e "${EXTENSION}.tcz.md5.txt" ] && sudo rm -f "${EXTENSION}.tcz.md5.txt"
+  sudo rm -f *.tcz*
 
-  sudo mksquashfs "$EXTENSION" "${EXTENSION}.tcz" || return 1
+  sudo mksquashfs "$EXTENSION_NAME" "${EXTENSION_NAME}.tcz" || return 1
 
-  md5sum "${EXTENSION}.tcz" > "${EXTENSION}.tcz.md5.txt" || return 1
+  md5sum "${EXTENSION_NAME}.tcz" > "${EXTENSION_NAME}.tcz.md5.txt" || return 1
 
-  cd "$TCEXTTOOLS_BIN/$EXTENSION"
+  cd "$TCEXTTOOLS_BIN/$EXTENSION_NAME"
   for i in $(ls)
   do
-      sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN/${EXTENSION}.tcz.list"
+      sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz.list"
   done
 
   cd "$PACKAGE_ROOT"
 
-  [ -d "$TCEXTTOOLS_EXTENSIONS/$EXTENSION" ] || mkdir -p "$TCEXTTOOLS_EXTENSIONS/$EXTENSION"
+  [ -d "$TCEXTTOOLS_EXTENSIONS/$EXTENSION_NAME" ] || mkdir -p "$TCEXTTOOLS_EXTENSIONS/$EXTENSION_NAME"
 
-  busybox cp -f "$TCEXTTOOLS_BIN/${EXTENSION}.tcz"* "$TCEXTTOOLS_EXTENSIONS/$EXTENSION" || return 1
+  busybox cp -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"* "$TCEXTTOOLS_EXTENSIONS/$EXTENSION_NAME" || return 1
 
   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/dep" ]; then
-       install -m 644 "$PACKAGE_EXTENSIONS/$EXTENSION/dep" "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz.dep" || return 1
+       install -m 644 "$PACKAGE_EXTENSIONS/$EXTENSION/dep" "$TCEXTTOOLS_EXTENSIONS/$EXTENSION_NAME/${EXTENSION_NAME}.tcz.dep" || return 1
   fi
 
-  sudo rm -f "$TCEXTTOOLS_BIN/${EXTENSION}.tcz"*
+  sudo rm -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"*
 
   return 0
 }
@@ -83,17 +81,21 @@ this_main() {
 
   for EXTENSION in $EXTENSIONS
   do
-      if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION" ]; then
+      . "$PACKAGE_COMMON"
+
+      set_extension_name
+
+      if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
            print_it error "You must split it first!"
            exit 1
       fi
 
       this_create
       if [ "$?" -gt 0 ]; then
-           print_it error "Creating the extension $EXTENSION failed!"
+           print_it error "Creating the extension $EXTENSION_NAME failed!"
            return 1
       else
-           print_it "Creating the extension $EXTENSION successful!"
+           print_it "Creating the extension $EXTENSION_NAME successful!"
       fi
   done
 
diff --git a/trunk/tools/splitit b/trunk/tools/splitit
--- a/trunk/tools/splitit
+++ b/trunk/tools/splitit
@@ -80,11 +80,11 @@ this_split() {
   sudo mkdir "$TMP_DIR/root"
   sudo tar -C "$TMP_DIR/root" -pxzf "$TMP_DIR/pkg.tar.gz" || return 1
 
-  if [ -d "$TCEXTTOOLS_BIN/$EXTENSION" ]; then
-       sudo rm -rf "$TCEXTTOOLS_BIN/$EXTENSION" || return 1
+  if [ -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
+       sudo rm -rf "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
   fi
 
-  sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION" || return 1
+  sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
 
   sudo rm -rf "$TMP_DIR"
 
@@ -93,19 +93,17 @@ this_split() {
 
 this_modify() {
 
-  if [ -f "$PACKAGE_EXTENSIONS/$EXTENSION/icon" ]; then
-       . "$PACKAGE_EXTENSIONS/$EXTENSION/icon"
-  fi
-
   if [ -n "$ICON" ]; then
-       if [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION/$ICON" ]; then
-            print_it error "The icon: $TCEXTTOOLS_BIN/$EXTENSION/$ICON does not exist!"
+       if [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON" ]; then
+            print_it error "The icon: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON does not exist!"
             return 1
-       elif [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION/$DESKTOP" ]; then
-            print_it error "The desktop entry: $TCEXTTOOLS_BIN/$EXTENSION/$DESKTOP does not exist!"
+       elif [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" ]; then
+            print_it error "The desktop entry: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP does not exist!"
             return 1
        else
-            sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_BIN/$EXTENSION/$DESKTOP" || return 1
+            sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" || return 1
+            unset ICON
+            unset DESKTOP
        fi
   fi
 }
@@ -114,24 +112,27 @@ this_main() {
 
   for EXTENSION in $EXTENSIONS
   do
+      . "$PACKAGE_COMMON"
+
+      set_extension_name
 
       TMP_DIR=$(busybox mktemp -d)
 
       this_split
       if [ "$?" -gt 0 ]; then
-           print_it error "Splitting the extension $EXTENSION failed!"
+           print_it error "Splitting the extension $EXTENSION_NAME failed!"
            sudo rm -rf "$TMP_DIR"
            return 1
       else
-           print_it "Splitting the extension $EXTENSION successful!"
+           print_it "Splitting the extension $EXTENSION_NAME successful!"
       fi
 
       this_modify
       if [ "$?" -gt 0 ]; then
-           print_it error "Modifying the extension $EXTENSION failed!"
+           print_it error "Modifying the extension $EXTENSION_NAME failed!"
            return 1
       else
-           print_it "Modifying the extension $EXTENSION successful!"
+           print_it "Modifying the extension $EXTENSION_NAME successful!"
       fi
   done
 
