Added auto change-log support

diff --git a/trunk/tools/generateit b/trunk/tools/generateit
--- a/trunk/tools/generateit
+++ b/trunk/tools/generateit
@@ -39,6 +39,120 @@ if [ -n "$HAVE_TET_CREATE" -a ! -f "$PACKAGE_CREATE_STAMP" ]; then
      exit 1
 fi
 
+this_download_info(){
+
+   [ -d "$PACKAGE_EXTENSION_PKG_TEMP" ] || mkdir -p "$PACKAGE_EXTENSION_PKG_TEMP"
+   wget --no-check-certificate --tries=3 "$TCZREPO_EXTENSION_INFO" -P "$PACKAGE_EXTENSION_PKG_TEMP" || return 1
+
+}
+
+this_parse_line(){
+
+   # skip NL and EOF characters
+   if [ "$line" = "" -o "$line" = "EOF" ]; then
+      return 0
+   fi
+
+   if [ "${line#Title:}" != "$line" ]; then
+      TITLE="${line#Title:}"
+      TITLE=`echo "$TITLE" | sed "s/\t\t//"`
+   elif [ "${line#Description:}" != "$line" ]; then
+      DESCRIPTION="${line#Description:}"
+      DESCRIPTION=`echo "$DESCRIPTION" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Version:}" != "$line" ]; then
+      VERSION="${line#Version:}"
+      VERSION=`echo "$VERSION" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Author:}" != "$line" ]; then
+      AUTHOR="${line#Author:}"
+      AUTHOR=`echo "$AUTHOR" | sed "s/\t\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Original-site:}" != "$line" ]; then
+      SITE="${line#Original-site:}"
+      SITE=`echo "$SITE" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Copying-policy:}" != "$line" ]; then
+      COPYING="${line#Copying-policy:}"
+      COPYING=`echo "$COPYING" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Size:}" != "$line" ]; then
+      SIZE="${line#Size:}"
+      SIZE=`echo "$SIZE" | sed "s/\t\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Extension_by:}" != "$line" ]; then
+      MAINTAINER="${line#Extension_by:}"
+      MAINTAINER=`echo "$MAINTAINER" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Tags:}" != "$line" ]; then
+      TAGS="${line#Tags:}"
+      TAGS=`echo "$TAGS" | sed "s/\t\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Comments:}" != "$line" ]; then
+      COMMENTS="${line#Comments:}"
+      COMMENTS=`echo "$COMMENTS" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Change-log:}" != "$line" ]; then
+      CHANGELOG="${line#Change-log:}"
+      CHANGELOG=`echo "$CHANGELOG" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   elif [ "${line#Current:}" != "$line" ]; then
+      CURRENT="${line#Current:}"
+      CURRENT=`echo "$CURRENT" | sed "s/\t//"`
+      blockno=`expr $blockno + 1`
+   else
+      case "$blockno" in
+        0) TITLE=`echo -e "${TITLE}\n${line}"` ;;
+        1) DESCRIPTION=`echo -e "${DESCRIPTION}\n${line}"` ;;
+        2) VERSION=`echo -e "${VERSION}\n${line}"` ;;
+        3) AUTHOR=`echo -e "${AUTHOR}\n${line}"` ;;
+        4) SITE=`echo -e "${SITE}\n${line}"` ;;
+        5) COPYING=`echo -e "${COPYING}\n${line}"` ;;
+        6) SIZE=`echo -e "${SIZE}\n${line}"` ;;
+        7) MAINTAINER=`echo -e "${MAINTAINER}\n${line}"` ;;
+        8) TAGS=`echo -e "${TAGS}\n${line}"` ;;
+        9) COMMENTS=`echo -e "${COMMENTS}\n${line}"` ;;
+        10) CHANGELOG=`echo -e "${CHANGELOG}\n${line}"` ;;
+        11) CURRENT=`echo -e "${CURRENT}\n${line}"` ;;
+      esac
+   fi
+
+}
+
+this_cat_info(){
+
+   if [ "$CHANGELOG" == "---" -o "$CHANGELOG" == "" ]; then
+      cat > "$PACKAGE_EXTENSION_TEMP_COMMON" << EOF
+CHANGELOG="${CURRENT}"
+EOF
+
+   else
+      cat > "$PACKAGE_EXTENSION_TEMP_COMMON" << EOF
+CHANGELOG="${CHANGELOG}
+		${CURRENT}"
+EOF
+   fi
+
+}
+
+this_parse_info(){
+
+   lineno=0
+   blockno=0
+
+   IFS=" "
+
+   (cat "$PACKAGE_EXTENSION_TEMP_INFO"; echo -e "\nEOF") | while read line
+   do
+     lineno=`expr $lineno + 1`
+     this_parse_line
+     if [ "$line" = "EOF" ]; then
+       this_cat_info
+     fi
+   done
+
+}
+
 this_generate() {
 
    echo "Setting the extension description."
@@ -53,8 +167,15 @@ this_generate() {
    echo -e "Checking if the extension has a common file ... \c"
    if [ -f "$PACKAGE_EXTENSION_COMMON" ]; then
         echo "yes"
-        echo "Sourcing the extension common"
         . "$PACKAGE_EXTENSION_COMMON"
+   else
+        echo "no"
+   fi
+
+   echo -e "Checking if the extension temp common exists ... \c"
+   if [ -f "$PACKAGE_EXTENSION_TEMP_COMMON" ]; then
+        echo "yes"
+        . "$PACKAGE_EXTENSION_TEMP_COMMON"
    else
         echo "no"
    fi
@@ -97,9 +218,27 @@ this_main() {
    echo ""
    echo "---------------------------------------------------------------"
 
+   echo "---------------------------------------------------------------"
+   echo "Cleaning the package pkg temporary directory"
+   echo "---------------------------------------------------------------"
+   [ -d "$PACKAGE_PKG_TEMP" ] && sudo rm -rf "$PACKAGE_PKG_TEMP"
+
    for EXTENSION in $EXTENSIONS
    do
        set_extension
+
+       echo "---------------------------------------------------------------"
+       echo "Downloading the extension $PACKAGE_EXTENSION_NAME info from repository"
+       echo "---------------------------------------------------------------"
+       this_download_info
+       if [ "$?" -gt 0 ]; then
+            echo "Downloading the extension info failed! It does not exist or a network issue..."
+       else
+            echo "---------------------------------------------------------------"
+            echo "Parsing the extension info which is downloaded from the repository"
+            echo "---------------------------------------------------------------"
+            this_parse_info || return 1
+       fi
 
        echo "---------------------------------------------------------------"
        echo "Generating the extension $PACKAGE_EXTENSION_NAME info file."
@@ -128,6 +267,11 @@ this_main() {
             echo "---------------------------------------------------------------"
        fi
    done
+
+   echo "---------------------------------------------------------------"
+   echo "Cleaning the package pkg temporary directory"
+   echo "---------------------------------------------------------------"
+   sudo rm -rf "$PACKAGE_PKG_TEMP"
 
    echo "---------------------------------------------------------------"
    echo ""
