- Completed new stamp mechanism for tc-ext-tools

diff --git a/trunk/tools/installit b/trunk/tools/installit
--- a/trunk/tools/installit
+++ b/trunk/tools/installit
@@ -39,8 +39,8 @@ if [ "$PACKAGE_SOURCE_TYPE" = "none" ]; then
 fi
 
 if [ -n "$HAVE_TET_COMPILE" -a ! -f "$PACKAGE_COMPILE_STAMP" ]; then
-      echo "${ERROR_COLOR}You must compile it first!${NORMAL}"
-      exit 1
+     echo "${ERROR_COLOR}You must compile it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
diff --git a/trunk/tools/packageit b/trunk/tools/packageit
--- a/trunk/tools/packageit
+++ b/trunk/tools/packageit
@@ -34,6 +34,26 @@ else
      exit 1
 fi
 
+if [ -n "$HAVE_TET_DOWNLOAD" -a ! -f "$PACKAGE_DOWNLOAD_STAMP" ] && [ -n "$HAVE_TET_CONVERT" -a ! -f "$PACKAGE_CONVERT_STAMP" ]; then
+     echo "${ERROR_COLOR}You must download it first!${NORMAL}"
+     exit 1
+fi
+
+if [ -n "$HAVE_TET_CREATE" -a ! -f "$PACKAGE_CREATE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must create it first!${NORMAL}"
+     exit 1
+fi
+
+if [ -n "$HAVE_TET_GENERATE" -a ! -f "$PACKAGE_GENERATE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must generate it first!${NORMAL}"
+     exit 1
+fi
+
+if [ -n "$HAVE_TET_CHECK" -a ! -f "$PACKAGE_CHECK_STAMP" ]; then
+     echo "${ERROR_COLOR}You must check it first!${NORMAL}"
+     exit 1
+fi
+
 this_main() {
 
    echo "---------------------------------------------------------------"
@@ -119,6 +139,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_PACKAGE_STAMP" ] && sudo rm -f "$PACKAGE_PACKAGE_STAMP"
+
 echo -e "${MESSAGE_COLOR}Packaging the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -127,6 +149,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_PACKAGE_STAMP"
 
 exit 0
 
diff --git a/trunk/tools/stripit b/trunk/tools/stripit
--- a/trunk/tools/stripit
+++ b/trunk/tools/stripit
@@ -34,6 +34,11 @@ else
      exit 1
 fi
 
+if [ -n "$HAVE_TET_SPLIT" -a ! -f "$PACKAGE_SPLIT_STAMP" ]; then
+     echo "${ERROR_COLOR}You must split it first!${NORMAL}"
+     exit 1
+fi
+
 this_strip() {
 
    echo "Getting the package extension executables list."
@@ -96,7 +101,6 @@ this_main() {
             echo "---------------------------------------------------------------"
             echo "Error! Stripping the package extension $PACKAGE_EXTENSION_NAME failed."
             echo "---------------------------------------------------------------"
-            sudo rm -rf "$TMP_DIR"
             return 1
        else
             echo "---------------------------------------------------------------"
@@ -115,6 +119,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_STRIP_STAMP" ] && sudo rm -f "$PACKAGE_STRIP_STAMP"
+
 echo -e "${MESSAGE_COLOR}Stripping the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extensions ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -123,6 +129,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_STRIP_STAMP"
 
 exit 0
 
