- Updated tc-ext-tools

diff --git a/trunk/tools/loadit b/trunk/tools/loadit
--- a/trunk/tools/loadit
+++ b/trunk/tools/loadit
@@ -47,7 +47,7 @@ this_load() {
    EXTENSION_TCZ="${EXTENSION%.tcz}.tcz"
    EXTENSION_NAME="${EXTENSION_TCZ%.tcz}"
 
-   echo -e "Checking if the extension is installed ... \c"
+   echo -e "Checking if the extension $EXTENSION_NAME is installed ... \c"
    if [ -e "/usr/local/tce.installed/$EXTENSION_NAME" ]; then
         echo "yes"
         if [ "$COMMAND" = "cp2fs" -a -d "$TCLOOP/$EXTENSION_NAME" ]; then
@@ -58,7 +58,7 @@ this_load() {
         echo "no"
    fi
 
-   echo -e "Checking if the extension exists ... \c"
+   echo -e "Checking if the extension $EXTENSION_NAME exists ... \c"
    if [ -f "$TCE_DIR/optional/$EXTENSION_TCZ" ]; then
         echo "yes"
    else
@@ -81,20 +81,37 @@ this_load() {
 
 this_main() {
 
+   echo "---------------------------------------------------------------"
    echo ""
    echo "Loading the package $PACKAGE build dependencies ..."
+   echo ""
+   echo "---------------------------------------------------------------"
 
    for EXTENSION in $PACKAGE_BUILD_DEPENDS
    do
-       if [ -n "$EXTENSION" ] && [ "${EXTENSION#\#}" == "$EXTENSION" ]; then
-            echo ""
-            echo "Loading the extension $EXTENSION"
-            this_load || return 1
+       if [ -n "$EXTENSION" ] && [ "${EXTENSION#\#}" = "$EXTENSION" ]; then
+            echo "---------------------------------------------------------------"
+            echo "Loading the package build dependency $EXTENSION"
+            echo "---------------------------------------------------------------"
+            this_load
+            if [ "$?" -gt 0 ]; then
+                 echo "---------------------------------------------------------------"
+                 echo "Error! Loading the package build dependency $EXTENSION failed."
+                 echo "---------------------------------------------------------------"
+                 return 1
+            else
+                 echo "---------------------------------------------------------------"
+                 echo "Loading the package build dependency $EXTENSION successful."
+                 echo "---------------------------------------------------------------"
+            fi
        fi
    done
 
+   echo "---------------------------------------------------------------"
    echo ""
    echo "Loaded the package $PACKAGE build dependencies successfully."
+   echo ""
+   echo "---------------------------------------------------------------"
 
    return 0
 
diff --git a/trunk/tools/unpackit b/trunk/tools/unpackit
--- a/trunk/tools/unpackit
+++ b/trunk/tools/unpackit
@@ -42,31 +42,44 @@ fi
 
 this_main() {
 
+   echo "---------------------------------------------------------------"
    echo ""
-   echo "Unpacking the package $PACKAGE source ..."
+   echo "Unpacking the package $PACKAGE source $PACKAGE_SOURCE_NAME ..."
+   echo ""
+   echo "---------------------------------------------------------------"
 
-   echo "Cleaning the package temporary source directory."
+   echo "Cleaning the package src temporary directory."
    [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
    mkdir -p "$PACKAGE_SRC_TEMP"
 
-   echo "Unpacking the package source $PACKAGE_SOURCE_NAME with the source type $PACKAGE_SOURCE_TYPE."
    if [ "$PACKAGE_SOURCE_TYPE" = "bz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "gz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tgz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tbz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "xz" ] || [ "$PACKAGE_SOURCE_TYPE" = "txz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tar" ]; then
-        echo "Using tar to extract the package source."
-        tar -C "$PACKAGE_SRC_TEMP" -xf "$PACKAGE_SOURCE" || return 1
+        echo "---------------------------------------------------------------"
+        echo "Extracting the package source by using tar."
+        echo "---------------------------------------------------------------"
+        tar -C "$PACKAGE_SRC_TEMP" -xvf "$PACKAGE_SOURCE" || return 1
    elif [ "$PACKAGE_SOURCE_TYPE" = "zip" ]; then
-        echo "Unzipping the package source."
+        echo "---------------------------------------------------------------"
+        echo "Unzipping the package source by using unzip."
+        echo "---------------------------------------------------------------"
         unzip "$PACKAGE_SOURCE" -d "$PACKAGE_SRC_TEMP" || return 1
    elif [ "$PACKAGE_SOURCE_TYPE" = "custom" ]; then
-        echo "Executing the custom build unpack function."
+        echo "---------------------------------------------------------------"
+        echo "Executing the package build unpack function."
+        echo "---------------------------------------------------------------"
         cd "$PACKAGE_SRC_TEMP"
         build_unpack || return 1
    else
-        echo "Error! unsupported source type."
+        echo "---------------------------------------------------------------"
+        echo "Error! Unsupported source type."
+        echo "---------------------------------------------------------------"
         return 1
    fi
 
+   echo "---------------------------------------------------------------"
    echo ""
    echo "Unpacked the package $PACKAGE source successfully."
+   echo ""
+   echo "---------------------------------------------------------------"
 
    return 0
 
