- Added two new tools: configureit, and compileit - Added KERNEL support to extension naming - All code reviewed and edited for better visual, and standarts

diff --git a/trunk/default/functions b/trunk/default/functions
--- a/trunk/default/functions
+++ b/trunk/default/functions
@@ -24,10 +24,14 @@
 #
 
 ############################################################################ 
-#                       tc-ext-tools initialization                        #
+#                             this is it                                   #
 ############################################################################
 
 THIS=$(basename $0)
+
+############################################################################ 
+#                     only some of them can be root                        #
+############################################################################
 
 if [ $(id -u) = 0 ] ; then
      if [ "$THIS" != "installit" ]; then
@@ -41,12 +45,20 @@ else
      fi
 fi
 
+############################################################################ 
+#                        default configuration                             #
+############################################################################
+
 if [ -f "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/config" ]; then
      . "$TCEXTTOOLS_ROOT/etc/tc-ext-tools/config"
 else
      echo "${RED}$(basename $0):${BLUE} tc-ext-tools default configuration file not found!${NORMAL}"
      exit 1
 fi
+
+############################################################################ 
+#                           user configuration                             #
+############################################################################
 
 if [ -f "$HOME/.tc-ext-tools/config" ]; then
      . "$HOME/.tc-ext-tools/config"
@@ -56,10 +68,11 @@ else
 fi
 
 ############################################################################ 
-#                   tc-ext-tools message print function                    #
+#                         message print function                           #
 ############################################################################
 
 print_it() {
+
   case  "$1" in
         error)
                 [ -z "$2" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
@@ -77,13 +90,14 @@ print_it() {
                 echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
                 ;;
   esac
+
 }
 
 ############################################################################ 
 #           sets the variables related with the package source             #
 ############################################################################
 
-set_package_source() {
+set_source() {
 
      if [ -z "$VCS" ]; then
           SOURCE_NAME=${SOURCE##*/}
@@ -107,13 +121,12 @@ set_package_source() {
             SOURCE_TYPE="xz"
             CONVERTED_SOURCE="$SOURCE_NAME"
      else
-            # user must define custom build_unpack, and build_convert functions in the build file for custom package sources
             SOURCE_TYPE="custom"
             [ -z "$CONVERTED_SOURCE" ] && CONVERTED_SOURCE="${SOURCE_NAME%.*}.tar.xz"
      fi
 
      if [ -z "$VCS" ]; then
-          TOP_SRC=$(ls -el $TCEXTTOOLS_SRC_TEMP | egrep '^d' | cut -d : -f3 | cut -d " " -f3)
+          [ -d "$TCEXTTOOLS_SRC_TEMP" ] && TOP_SRC=$(ls -el $TCEXTTOOLS_SRC_TEMP | egrep '^d' | cut -d : -f3 | cut -d " " -f3)
      else
           TOP_SRC=${PACKAGE}-${VERSION}
      fi
@@ -122,6 +135,7 @@ set_package_source() {
           TCEXTTOOLS_TOP_SRC="$TCEXTTOOLS_SRC_TEMP/$TOP_SRC"
           PACKAGE_TOP_SRC="$TCEXTTOOLS_TOP_SRC"
      fi
+
 }
 
 ############################################################################ 
@@ -130,9 +144,7 @@ set_package_source() {
 
 set_extensions() {
 
-      if [ "$THIS" != "boostit" ]; then
-           EXTENSIONS=$(ls -el $PACKAGE_EXTENSIONS | egrep '^d' | cut -d : -f3 | cut -d " " -f3)
-      fi
+   [ -d "$PACKAGE_EXTENSIONS" ] && EXTENSIONS=$(ls -el $PACKAGE_EXTENSIONS | egrep '^d' | cut -d : -f3 | cut -d " " -f3)
 
 }
 
@@ -156,6 +168,47 @@ set_extension_name() {
       else
            EXTENSION_NAME="$NAME"
       fi
+
+      if [ -n "$(echo $EXTENSION_NAME | grep KERNEL)" ]; then
+           EXTENSION_NAME=$(echo $EXTENSION | sed -e "s/KERNEL/${KERNEL}/g")
+      fi
+
+}
+
+############################################################################ 
+#                        date, time, and seconds                           #
+############################################################################
+
+set_date_time() {
+
+    YEAR=$(date +%Y)
+    MONTH=$(date +%m)
+    DAY=$(date +%d)
+    DATE="$YEAR/$MONTH/$DAY"
+
+    HOUR=$(date +%H)
+    MIN=$(date +%M)
+    SEC=$(date +%S)
+    TIME="$HOUR:MIN:$SEC"
+
+}
+
+set_seconds() {
+
+    SECONDS=$(date +%s)
+
+}
+
+############################################################################ 
+#                      export environment variables                        #
+############################################################################
+
+export_flags() {
+
+    [ -z "$CFLAGS" ] && export CFLAGS="$TCEXTTOOLS_CFLAGS"
+    [ -z "$CXXFLAGS" ] && export CXXFLAGS="$TCEXTTOOLS_CXXFLAGS"
+    [ -z "$LDFLAGS" ] && export LDFLAGS="$TCEXTTOOLS_LDFLAGS"
+
 }
 
 ############################################################################ 
@@ -165,7 +218,19 @@ set_extension_name() {
 TCUSER=$(cat /etc/sysconfig/tcuser)
 
 ############################################################################ 
-#                   tc-ext-tools package specific definitions              #
+#                                set tce_dir                               #
+############################################################################
+
+TCE_DIR="$(cat /opt/.tce_dir)"
+
+############################################################################ 
+#                                set kernel                                #
+############################################################################
+
+KERNEL=$(uname -r)
+
+############################################################################ 
+#                          all other definitions                           #
 ############################################################################
 
 PACKAGE_ROOT="$PWD"
@@ -182,12 +247,9 @@ if [ -e "$PACKAGE_COMMON" ]; then
      TCEXTTOOLS_SRC="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_SRC"
      TCEXTTOOLS_LOG="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_LOG"
      TCEXTTOOLS_PKG="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_PKG"
-
      TCEXTTOOLS_BIN_TEMP="$TCEXTTOOLS_BIN/temp"
      TCEXTTOOLS_SRC_TEMP="$TCEXTTOOLS_SRC/temp"
-
      TCEXTTOOLS_PACKAGE="$TCEXTTOOLS_BIN_TEMP/$PACKAGE"
-
      TCEXTTOOLS_DOWNLOAD_LOG="$TCEXTTOOLS_LOG/download.txt"
      TCEXTTOOLS_CONFIGURE_LOG="$TCEXTTOOLS_LOG/configure.txt"
      TCEXTTOOLS_COMPILE_LOG="$TCEXTTOOLS_LOG/compile.txt"
@@ -207,7 +269,7 @@ if [ -e "$PACKAGE_COMMON" ]; then
      [ -d "$TCEXTTOOLS_PKG" ] || install -m 755 -d "$TCEXTTOOLS_PKG"
      [ -d "$TCEXTTOOLS_LOG" ] || install -m 755 -d "$TCEXTTOOLS_LOG"
 
-     set_package_source
+     set_source
 
      TCEXTTOOLS_SOURCE="$TCEXTTOOLS_SRC/$SOURCE_NAME"
      TCEXTTOOLS_CONVERTED_SOURCE="$TCEXTTOOLS_SRC/$CONVERTED_SOURCE"
@@ -222,52 +284,37 @@ if [ -e "$PACKAGE_COMMON" ]; then
      INSTALL_ROOT="$PACKAGE_INSTALL_ROOT"
      PREFIX="$TCEXTTOOLS_PREFIX"
 
-     set_extensions
-
-     KERNEL_EXTENSIONS=$(echo $EXTENSIONS | sed -e "s/KERNEL/$(uname -r)/g")
-
 elif [ "$THIS" != "boostit" ]; then
      print_it error "the package $PACKAGE common file not found!"
      print_it warning "You must boost it first!"
      exit 1
 fi
 
-# to prevent a write permission error due to running installit as root
-if [ "$THIS" = "installit" ]; then
-     su "$TCUSER" -c "touch $TCEXTTOOLS_ERROR_LOG_2"
+############################################################################ 
+#                        some needs build functions                        #
+############################################################################
+
+if [ "$THIS" = "buildit" ] || [ "$THIS" = "convertit" ] || [ "$THIS" = "unpackit" ] || [ "$THIS" = "configureit" ] || [ "$THIS" = "compileit" ] || [ "$THIS" = "installit" ]; then
+     if [ -e "$PACKAGE_BUILD" ]; then
+          . "$PACKAGE_BUILD"
+     else
+          print_it error "the package $PACKAGE build file not found!"
+          exit 1
+     fi
 fi
 
 ############################################################################ 
-#               import tc-ext-tools package build functions                #
+#                           some needs flags                               #
 ############################################################################
 
-if [ -e "$PACKAGE_BUILD" ]; then
-     . "$PACKAGE_BUILD"
-elif [ "$THIS" != "boostit" ]; then
-     print_it error "the package $PACKAGE build file not found!"
-     exit 1
+if [ "$THIS" = "configureit" ] || [ "$THIS" = "compileit" ] || [ "$THIS" = "installit" ]; then
+     export_flags
 fi
 
 ############################################################################ 
-#                             date (YYYY/MM/DD)                            #
+#                              common needs                                #
 ############################################################################
 
-YEAR=$(date +%Y)
-MONTH=$(date +%m)
-DAY=$(date +%d)
-DATE="$YEAR/$MONTH/$DAY"
-
-############################################################################ 
-#                             kernel version                               #
-############################################################################
-
-KERNEL=$(uname -r)
-
-############################################################################ 
-#                export tc-ext-tools environment variables                 #
-############################################################################
-
-[ -z "$CFLAGS" ] && export CFLAGS="$TCEXTTOOLS_CFLAGS"
-[ -z "$CXXFLAGS" ] && export CXXFLAGS="$TCEXTTOOLS_CXXFLAGS"
-[ -z "$LDFLAGS" ] && export LDFLAGS="$TCEXTTOOLS_LDFLAGS"
+set_extensions
+set_date_time
 
diff --git a/trunk/tools/boostit b/trunk/tools/boostit
--- a/trunk/tools/boostit
+++ b/trunk/tools/boostit
@@ -40,7 +40,9 @@ VERSION="$2"
 EXTENSIONS="$3"
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extension1 extension2 ...\"${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extension1 extension2 ...\"${NORMAL}"
+
 }
 
 if [ -z "$PACKAGE" ] || [ -z "$VERSION" ]; then
@@ -72,15 +74,19 @@ if [ -e "$PACKAGE_COMMON" ]; then
      esac
 fi
 
+############################################################################ 
+#                                this main                                 #
+############################################################################
+
 this_main() {
 
-  if [ ! -d "$PACKAGE_EXTENSIONS" ]; then
-       install -m 755 -d "$PACKAGE_EXTENSIONS" || return 1
-  fi
+   if [ ! -d "$PACKAGE_EXTENSIONS" ]; then
+          install -m 755 -d "$PACKAGE_EXTENSIONS" || return 1
+   fi
 
-  if [ "$VERSION" = "svn" ]; then
+   if [ "$VERSION" = "svn" ]; then
 
-       cat > "$PACKAGE_COMMON" << _EOF
+        cat > "$PACKAGE_COMMON" << _EOF
 PACKAGE="$PACKAGE"
 VERSION="svn\${YEAR}\${MONTH}\${DAY}"
 SOURCE=""
@@ -97,11 +103,11 @@ CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-       [ "$?" -gt 0 ] && return 1
+        [ "$?" -gt 0 ] && return 1
 
-  elif [ "$VERSION" = "git" ]; then
+   elif [ "$VERSION" = "git" ]; then
 
-       cat > "$PACKAGE_COMMON" << _EOF
+        cat > "$PACKAGE_COMMON" << _EOF
 PACKAGE="${PACKAGE}"
 VERSION="git\${YEAR}\${MONTH}\${DAY}"
 SOURCE=""
@@ -118,11 +124,11 @@ CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-       [ "$?" -gt 0 ] && return 1
+        [ "$?" -gt 0 ] && return 1
 
-  else
+   else
 
-       cat > "$PACKAGE_COMMON" << _EOF
+        cat > "$PACKAGE_COMMON" << _EOF
 PACKAGE="$PACKAGE"
 VERSION="$VERSION"
 SOURCE=""
@@ -138,28 +144,29 @@ CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-       [ "$?" -gt 0 ] && return 1
+        [ "$?" -gt 0 ] && return 1
 
-  fi
+   fi
 
-  install -m 644 "$TCEXTTOOLS_ROOT/share/tc-ext-tools/build" "$PACKAGE_BUILD" || return 1
+   install -m 644 "$TCEXTTOOLS_ROOT/share/tc-ext-tools/build" "$PACKAGE_BUILD" || return 1
 
-  for EXTENSION in $EXTENSIONS
-  do
-      mkdir -p "$PACKAGE_EXTENSIONS/$EXTENSION" || return 1
-      touch "$PACKAGE_EXTENSIONS/$EXTENSION/install" || return 1
-      if [ "${EXTENSION%-doc}" = "$EXTENSION" ]; then
-           touch "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
-      fi
-      if [ ! "${EXTENSION%-locale}" = "$EXTENSION" ]; then
-           echo "${EXTENSION%-locale}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
-           echo "usr/local/share/locale" > "$PACKAGE_EXTENSIONS/$EXTENSION/install" || return 1
-      elif [ ! "${EXTENSION%-dev}" = "$EXTENSION" ]; then
-           echo "${EXTENSION%-dev}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
-      fi
-  done
+   for EXTENSION in $EXTENSIONS
+   do
+       mkdir -p "$PACKAGE_EXTENSIONS/$EXTENSION" || return 1
+       touch "$PACKAGE_EXTENSIONS/$EXTENSION/install" || return 1
+       if [ "${EXTENSION%-doc}" = "$EXTENSION" ]; then
+            touch "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
+       fi
+       if [ ! "${EXTENSION%-locale}" = "$EXTENSION" ]; then
+              echo "${EXTENSION%-locale}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
+              echo "usr/local/share/locale" > "$PACKAGE_EXTENSIONS/$EXTENSION/install" || return 1
+       elif [ ! "${EXTENSION%-dev}" = "$EXTENSION" ]; then
+              echo "${EXTENSION%-dev}.tcz" > "$PACKAGE_EXTENSIONS/$EXTENSION/dep" || return 1
+       fi
+   done
 
-  return 0
+   return 0
+
 }
 
 print_it "Boosting the package $PACKAGE ... \c"
diff --git a/trunk/tools/buildit b/trunk/tools/buildit
--- a/trunk/tools/buildit
+++ b/trunk/tools/buildit
@@ -24,6 +24,10 @@
 #  (C) Copyright 2010 Sercan Arslan
 #
 
+############################################################################ 
+#                        the one that rules them all                       #
+############################################################################
+
 . /etc/init.d/tc-functions
 
 TCEXTTOOLS_ROOT="$(dirname $0)/.."
@@ -36,297 +40,275 @@ else
 fi
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) (clean|clear)|load|download|convert|unpack|patch|configure|compile|install|strip|split|create|check|generate|package|compress|encrypt|(cat|show)|help|all${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) (clean|clear)|load|download|convert|unpack|patch|configure|compile|install|strip|split|create|check|generate|package|compress|encrypt|show|help|all${NORMAL}"
+
 }
 
 clean_it() {
 
-  print_it "Cleaning the package $PACKAGE ... \c"
-  cleanit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Cleaning the package $PACKAGE ... \c"
+   cleanit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 download_it() {
 
-  if [ -f "$PACKAGE_SOURCE" ]; then
-       print_it warning "The package $PACKAGE source is already downloaded."
-       exit 0
-  fi
+   if [ -f "$PACKAGE_SOURCE" ]; then
+        print_it warning "The package $PACKAGE source is already downloaded."
+        exit 0
+   fi
 
-  print_it "Downloading the package $PACKAGE source ... \c"
-  downloadit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show download"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Downloading the package $PACKAGE source ... \c"
+   downloadit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show download"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 convert_it() {
 
-  if [ ! -e "$PACKAGE_SOURCE" ]; then
-       print_it error "You must download it first!"
-       exit 1
-  fi
+   if [ -f "$PACKAGE_CONVERTED_SOURCE" ]; then
+        print_it warning "The package $PACKAGE source is already converted."
+        exit 0
+   fi
 
-  if [ -e "$PACKAGE_CONVERTED_SOURCE" ]; then
-       print_it warning "The package $PACKAGE source is already converted."
-       exit 0
-  fi
+   print_it "Converting the package $PACKAGE source to xz compressed tarball ... \c"
+   convertit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Converting the package $PACKAGE source to xz compressed tarball ... \c"
-  convertit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 unpack_it() {
 
-  if [ ! -e "$PACKAGE_SOURCE" ]; then
-        print_it error "You must download it first!"
+   print_it "Unpacking the package $PACKAGE source ... \c"
+   unpackit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
         exit 1
-  fi
+   fi
+   print_it hilight "successful!"
 
-  print_it "Unpacking the package $PACKAGE source ... \c"
-  unpackit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 load_it() {
 
-  print_it "Loading the package $PACKAGE build dependencies ... \c"
-  loadit "$BUILD_DEPENDS" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight  "successful!"
+   print_it "Loading the package $PACKAGE build dependencies ... \c"
+   loadit "$BUILD_DEPENDS" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight  "successful!"
+
 }
 
 patch_it() {
 
-  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
-       print_it error "You must unpack it first!"
-       exit 1
-  fi
+   print_it "Patching the package $PACKAGE source ... \c"
+   patchit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Patching the package $PACKAGE source ... \c"
-  patchit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 configure_it() {
 
-  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
-       print_it error "You must unpack it first!"
-       exit 1
-  fi
+   print_it "Configuring the package $PACKAGE ... \c"
+   configureit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show configure"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Configuring the package $PACKAGE ... \c"
-  cd "$PACKAGE_TOP_SRC"
-  build_configure > "$TCEXTTOOLS_CONFIGURE_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show configure"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 compile_it() {
 
-  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
-       print_it error "You must configure it first!"
-       exit 1
-  fi
+   print_it "Compiling the package $PACKAGE ... \c"
+   compileit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show compile"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Compiling the package $PACKAGE ... \c"
-  cd "$PACKAGE_TOP_SRC"
-  build_compile > "$TCEXTTOOLS_COMPILE_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show compile"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 install_it() {
 
-  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
-       print_it error "You must compile it first!"
-       exit 1
-  fi
-
-  print_it "Installing the package $PACKAGE ... \c"
-  sudo installit > "$TCEXTTOOLS_INSTALL_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show install"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Installing the package $PACKAGE ... \c"
+   sudo installit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show install"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
 }
 
 strip_it() {
 
-  if [ ! -d "$PACKAGE_INSTALL_ROOT" ]; then
-       print_it error "You must install it first!"
-       exit 1
-  fi
+   print_it "Stripping the package $PACKAGE ... \c"
+   stripit "$PACKAGE_INSTALL_ROOT" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Stripping the package $PACKAGE ... \c"
-  stripit "$PACKAGE_INSTALL_ROOT" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 split_it() {
 
-  if [ ! -d "$PACKAGE_INSTALL_ROOT" ]; then
-       print_it error "You must install it first!"
-       exit 1
-  fi
+   print_it "Splitting the package $PACKAGE extensions ... \c"
+   splitit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
-  print_it "Splitting the package $PACKAGE extensions ... \c"
-  splitit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
 }
 
 create_it() {
 
-  print_it "Creating the package $PACKAGE extensions ... \c"
-  createit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Creating the package $PACKAGE extensions ... \c"
+   createit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 generate_it() {
 
-  print_it "Generating the package $PACKAGE extensions info files ... \c"
-  generateit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Generating the package $PACKAGE extensions info files ... \c"
+   generateit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 check_it() {
 
-  print_it "Checking the package $PACKAGE extensions ... \c"
-  checkit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Checking the package $PACKAGE extensions ... \c"
+   checkit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 package_it() {
 
-  print_it "Packaging the package $PACKAGE ... \c"
-  packageit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Packaging the package $PACKAGE ... \c"
+   packageit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 compress_it() {
 
-  if [ ! -d "$TCEXTTOOLS_PACKAGE" ]; then
-       print_it error "You must package it first!"
-       exit 1
-  fi
+   if [ ! -d "$TCEXTTOOLS_PACKAGE" ]; then
+          print_it error "You must package it first!"
+          exit 1
+   fi
 
-  print_it "Compressing the package $PACKAGE ... \c"
-  compressit bz2 "$TCEXTTOOLS_PACKAGE" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "For details: buildit show error"
-       exit 1
-  fi
-  print_it hilight "successful!"
+   print_it "Compressing the package $PACKAGE ... \c"
+   compressit bz2 "$TCEXTTOOLS_PACKAGE" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit show error"
+        exit 1
+   fi
+   print_it hilight "successful!"
+
 }
 
 encrypt_it() {
 
-  if [ ! -e "${PACKAGE}.tar.bz2" ]; then
-       print_it error "You must compress it first!"
-       exit 1
-  fi
+   if [ ! -e "${PACKAGE}.tar.bz2" ]; then
+          print_it error "You must compress it first!"
+          exit 1
+   fi
 
-  encryptit "${PACKAGE}.tar.bz2" || exit 1
+   encryptit "${PACKAGE}.tar.bz2" || exit 1
+
 }
 
 build_it() {
 
-  build_rules || exit 1
+   build_rules || exit 1
+
 }
 
 show_it() {
 
-  case "$1" in
-       download) 
+   case "$1" in
+        download) 
                  [ -e "$TCEXTTOOLS_DOWNLOAD_LOG" ] && cat "$TCEXTTOOLS_DOWNLOAD_LOG"
                  ;;
-       configure)
+        configure)
                  [ -e "$TCEXTTOOLS_CONFIGURE_LOG" ] && cat "$TCEXTTOOLS_CONFIGURE_LOG"
                  ;;
-       compile)
+        compile)
                  [ -e "$TCEXTTOOLS_COMPILE_LOG" ] && cat "$TCEXTTOOLS_COMPILE_LOG"
                  ;;
-       install)
+        install)
                  [ -e "$TCEXTTOOLS_INSTALL_LOG" ] && cat "$TCEXTTOOLS_INSTALL_LOG"
                  ;;
-       error)
+        error)
                  [ -e "$TCEXTTOOLS_ERROR_LOG" ] && cat "$TCEXTTOOLS_ERROR_LOG"
                  [ -e "$TCEXTTOOLS_ERROR_LOG_2" ] && cat "$TCEXTTOOLS_ERROR_LOG_2"
                  ;;
-       *)
+        *)
                  print_it warning "Usage: buildit show download|configure|compile|install|error"
                  ;;
-  esac
+   esac
+
 }
 
 if [ -z "$1" ]; then
diff --git a/trunk/tools/createit b/trunk/tools/createit
--- a/trunk/tools/createit
+++ b/trunk/tools/createit
@@ -35,71 +35,89 @@ else
      exit 1
 fi
 
+
+for EXTENSION in $EXTENSIONS
+do
+    . "$PACKAGE_COMMON"
+
+    set_extension_name
+
+    if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
+           print_it error "You must split it first!"
+           exit 1
+    fi
+done
+
+############################################################################ 
+#                          creates the extension                           #
+############################################################################
+
 this_create() {
 
-  cd $PACKAGE_ROOT
+   cd $PACKAGE_ROOT
 
-  if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" ]; then
-       sudo install -m 775 -D "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed/$EXTENSION_NAME" || return 1
-       sudo chown -R root:staff "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
-       sudo chmod -R 775 "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
-  fi
+   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" ]; then
+        sudo install -m 775 -D "$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed" "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed/$EXTENSION_NAME" || return 1
+        sudo chown -R root:staff "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
+        sudo chmod -R 775 "$TCEXTTOOLS_BIN/$EXTENSION_NAME/usr/local/tce.installed" || return 1
+   fi
 
-  cd "$TCEXTTOOLS_BIN"
+   cd "$TCEXTTOOLS_BIN"
 
-  sudo rm -f *.tcz*
+   sudo rm -f *.tcz*
 
-  sudo mksquashfs "$EXTENSION_NAME" "${EXTENSION_NAME}.tcz" || return 1
+   sudo mksquashfs "$EXTENSION_NAME" "${EXTENSION_NAME}.tcz" || return 1
 
-  md5sum "${EXTENSION_NAME}.tcz" > "${EXTENSION_NAME}.tcz.md5.txt" || return 1
+   md5sum "${EXTENSION_NAME}.tcz" > "${EXTENSION_NAME}.tcz.md5.txt" || return 1
 
-  cd "$TCEXTTOOLS_BIN/$EXTENSION_NAME"
-  for i in $(ls)
-  do
-      sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz.list"
-  done
+   cd "$TCEXTTOOLS_BIN/$EXTENSION_NAME"
+   for i in $(ls)
+   do
+       sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz.list"
+   done
 
-  cd "$PACKAGE_ROOT"
+   cd "$PACKAGE_ROOT"
 
-  [ -d "$TCEXTTOOLS_PKG/$EXTENSION_NAME" ] || mkdir -p "$TCEXTTOOLS_PKG/$EXTENSION_NAME"
+   [ -d "$TCEXTTOOLS_PKG/$EXTENSION_NAME" ] || mkdir -p "$TCEXTTOOLS_PKG/$EXTENSION_NAME"
 
-  busybox cp -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"* "$TCEXTTOOLS_PKG/$EXTENSION_NAME" || return 1
+   busybox cp -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"* "$TCEXTTOOLS_PKG/$EXTENSION_NAME" || return 1
 
-  if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/dep" ]; then
-       install -m 644 "$PACKAGE_EXTENSIONS/$EXTENSION/dep" "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz.dep" || return 1
-  fi
+   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/dep" ]; then
+        install -m 644 "$PACKAGE_EXTENSIONS/$EXTENSION/dep" "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz.dep" || return 1
+   fi
 
-  sudo rm -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"*
+   sudo rm -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz"*
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                                this main                                 #
+############################################################################
 
 this_main() {
 
-  [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG"
-  mkdir -p "$TCEXTTOOLS_PKG"
+   [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG"
+   mkdir -p "$TCEXTTOOLS_PKG"
 
-  for EXTENSION in $EXTENSIONS
-  do
-      . "$PACKAGE_COMMON"
+   for EXTENSION in $EXTENSIONS
+   do
+       . "$PACKAGE_COMMON"
 
-      set_extension_name
+       set_extension_name
 
-      if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
-           print_it error "You must split it first!"
-           exit 1
-      fi
+       this_create
+       if [ "$?" -gt 0 ]; then
+            print_it error "Creating the extension $EXTENSION_NAME failed!"
+            return 1
+       else
+            print_it "Creating the extension $EXTENSION_NAME successful!"
+       fi
+   done
 
-      this_create
-      if [ "$?" -gt 0 ]; then
-           print_it error "Creating the extension $EXTENSION_NAME failed!"
-           return 1
-      else
-           print_it "Creating the extension $EXTENSION_NAME successful!"
-      fi
-  done
+   return 0
 
-  return 0
 }
 
 print_it "Creating the package $PACKAGE extensions ... \c"
diff --git a/trunk/tools/generateit b/trunk/tools/generateit
--- a/trunk/tools/generateit
+++ b/trunk/tools/generateit
@@ -35,24 +35,40 @@ else
      exit 1
 fi
 
+for EXTENSION in $EXTENSIONS
+do
+    . "$PACKAGE_COMMON"
+
+    set_extension_name
+
+    if [ ! -e "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" ]; then
+           print_it error "You must create it first!"
+           exit 1
+    fi
+done
+
+############################################################################ 
+#                       generates the extension info                       #
+############################################################################
+
 this_generate() {
 
-  [ ! "${EXTENSION%-bin}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, utilities."
-  [ ! "${EXTENSION%-lib}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, shared libraries."
-  [ ! "${EXTENSION%-dev}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, development files."
-  [ ! "${EXTENSION%-dbg}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, debugging symbols."
-  [ ! "${EXTENSION%-doc}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, documentation files."
-  [ ! "${EXTENSION%-locale}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, locale files."
-  [ ! "${EXTENSION%-gir}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, gobject introspection data."
+   [ ! "${EXTENSION%-bin}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, utilities."
+   [ ! "${EXTENSION%-lib}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, shared libraries."
+   [ ! "${EXTENSION%-dev}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, development files."
+   [ ! "${EXTENSION%-dbg}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, debugging symbols."
+   [ ! "${EXTENSION%-doc}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, documentation files."
+   [ ! "${EXTENSION%-locale}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, locale files."
+   [ ! "${EXTENSION%-gir}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, gobject introspection data."
 
-  if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/common" ]; then
-      . "$PACKAGE_EXTENSIONS/$EXTENSION/common"
-  fi
+   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/common" ]; then
+        . "$PACKAGE_EXTENSIONS/$EXTENSION/common"
+   fi
 
-  CURRENT="$DATE $CURRENT"
-  SIZE=$(du -h "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" | cut -f1)
+   CURRENT="$DATE $CURRENT"
+   SIZE=$(du -h "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" | cut -f1)
 
-  cat > "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz.info" << _EOF
+   cat > "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz.info" << _EOF
 Title:		${EXTENSION_NAME}.tcz
 Description:	${DESCRIPTION}
 Version:	${VERSION}
@@ -66,37 +82,38 @@ Change-log:	${CHANGELOG}
 Current:	${CURRENT}
 _EOF
 
-  if [ "$?" -gt 0 ]; then
-       print_it error "Failed to write to ${EXTENSION_NAME}.tcz.info"
-       return 1
-  fi
+   if [ "$?" -gt 0 ]; then
+        print_it error "Failed to write to ${EXTENSION_NAME}.tcz.info"
+        return 1
+   fi
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                               this main                                  #
+############################################################################
 
 this_main() {
 
-  for EXTENSION in $EXTENSIONS
-  do
-      . "$PACKAGE_COMMON"
+   for EXTENSION in $EXTENSIONS
+   do
+       . "$PACKAGE_COMMON"
 
-      set_extension_name
+       set_extension_name
 
-      if [ ! -e "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" ]; then
-             print_it error "You must create it first!"
-             exit 1
-      fi
+       this_generate
+       if [ "$?" -gt 0 ]; then
+            print_it error "Generating the extension $EXTENSION_NAME info failed!"
+            return 1
+       else
+            print_it "Generating the extension $EXTENSION_NAME info successful!"
+       fi
+   done
 
-      this_generate
-      if [ "$?" -gt 0 ]; then
-           print_it error "Generating the extension $EXTENSION_NAME info failed!"
-           return 1
-      else
-           print_it "Generating the extension $EXTENSION_NAME info successful!"
-      fi
-  done  
+   return 0
 
-  return 0
 }
 
 print_it "Generating the package $PACKAGE extensions info files ... \c"
diff --git a/trunk/tools/loadit b/trunk/tools/loadit
--- a/trunk/tools/loadit
+++ b/trunk/tools/loadit
@@ -37,14 +37,10 @@ fi
 
 EXT_LIST="$1"
 
-TCE_DIR="$(cat /opt/.tce_dir)"
-if [ "$?" -gt 0 ]; then
-     print_it error "Getting system tce directory failed!"
-     exit 1
-fi
-
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) \"ext1 ext2 ext3\" | /path/to/extlist${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) \"ext1 ext2 ext3\" | /path/to/extlist${NORMAL}"
+
 }
 
 if [ -z "$EXT_LIST" ]; then
@@ -52,41 +48,51 @@ if [ -z "$EXT_LIST" ]; then
      exit 1
 fi
 
+############################################################################ 
+#                              load extension                              #
+############################################################################
+
 tcz_load() {
 
-  extension="$1"
-  if [ -n "$extension" ]; then
-       if [ "${extension#\#}" = "$extension" ]; then
-            if [ ! -e "$TCE_DIR/optional/${extension%.tcz}.tcz" ]; then
-                 tce-load -w "${extension%.tcz}.tcz" || return 1
-            fi
-            if [ ! -e "/usr/local/tce.installed/${extension%.tcz}" ]; then
-                 tce-load -i "${extension%.tcz}.tcz" || return 1
-            fi
-       fi
-  fi
+   extension="$1"
+   if [ -n "$extension" ]; then
+        if [ "${extension#\#}" = "$extension" ]; then
+             if [ ! -e "$TCE_DIR/optional/${extension%.tcz}.tcz" ]; then
+                    tce-load -w "${extension%.tcz}.tcz" || return 1
+             fi
+             if [ ! -e "/usr/local/tce.installed/${extension%.tcz}" ]; then
+                    tce-load -i "${extension%.tcz}.tcz" || return 1
+             fi
+        fi
+   fi
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                                this main                                 #
+############################################################################
 
 this_main() {
 
-  if [ -f "$EXT_LIST" ]; then
-       EXT_LIST="$(cat $EXT_LIST)"
-       if [ -z "$EXT_LIST" ]; then
-            print_it error "Dependency list file is empty!"
-            return 1
-       fi
-  fi
+   if [ -f "$EXT_LIST" ]; then
+        EXT_LIST="$(cat $EXT_LIST)"
+        if [ -z "$EXT_LIST" ]; then
+             print_it error "Dependency list file is empty!"
+             return 1
+        fi
+   fi
 
-  EXT_LIST="$EXT_LIST $TCEXTTOOLS_DEPENDS"
+   EXT_LIST="$EXT_LIST $TCEXTTOOLS_DEPENDS"
 
-  for EXT in $EXT_LIST
-  do
-      tcz_load "$EXT" || return 1
-  done
+   for EXT in $EXT_LIST
+   do
+       tcz_load "$EXT" || return 1
+   done
 
-  return 0
+   return 0
+
 }
 
 print_it "Loading the extensions ... \c"
