- Added ooo-build (openoffice3) package - Updated midori - Updated all tools and fixed many bugs see diffs for details

diff --git a/trunk/default/functions b/trunk/default/functions
--- a/trunk/default/functions
+++ b/trunk/default/functions
@@ -1,103 +1,92 @@
-### tc-ext-tools functions
+# tc-ext-tools functions
 
-THIS=$(basename ${0})
+THIS=$(basename $0)
 
 if [ $(id -u) = 0 ] ; then
-     if [ ! "${THIS}" = "buildit" -o ! "${1}" = "install" ]; then
+     if [ ! "$THIS" = "buildit" -o ! "$1" = "install" ]; then
           echo "${RED}Do not run me as root!${NORMAL}"
           exit 1
      fi
 fi
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/config" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/config
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/config ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/config
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools default configuration file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools default configuration file not found!${NORMAL}"
      exit 1
 fi
 
 if [ -f "$HOME"/.tc-ext-tools/config ]; then
      . "$HOME"/.tc-ext-tools/config
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools user configuration file not found!${NORMAL}"
-     exit 1
+    echo "${RED}$(basename $0):${BLUE} tc-ext-tools user configuration file not found!${NORMAL}"
+    exit 1
 fi
 
 print_it() {
-  case  ${1} in
+  case  "$1" in
         error)
-                [ -z "${2}" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
-                echo -e "${TCEXTTOOLS_ERROR_COLOR}${2}${NORMAL}"
+                [ -z "$2" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}$1${NORMAL}"
+                echo -e "${TCEXTTOOLS_ERROR_COLOR}$2${NORMAL}"
                 ;;
         warning)   
-                [ -z "${2}" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
-                echo -e "${TCEXTTOOLS_WARNING_COLOR}${2}${NORMAL}"
+                [ -z "$2" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}$1${NORMAL}"
+                echo -e "${TCEXTTOOLS_WARNING_COLOR}$2${NORMAL}"
                 ;;
         hilight)   
-                [ -z "${2}" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
-                echo -e "${TCEXTTOOLS_HILIGHT_COLOR}${2}${NORMAL}"
+                [ -z "$2" ] && echo -e "${TCEXTTOOLS_MESSAGE_COLOR}$1${NORMAL}"
+                echo -e "${TCEXTTOOLS_HILIGHT_COLOR}$2${NORMAL}"
                 ;;
         *)
-                echo -e "${TCEXTTOOLS_MESSAGE_COLOR}${1}${NORMAL}"
+                echo -e "${TCEXTTOOLS_MESSAGE_COLOR}$1${NORMAL}"
                 ;;
   esac
 }
 
-PACKAGE_ROOT=${PWD}
-PACKAGE_COMMON="${PACKAGE_ROOT}/${TCEXTTOOLS_COMMON}"
-PACKAGE_BUILD="${PACKAGE_ROOT}/${TCEXTTOOLS_BUILD}"
-PACKAGE_SRC="${PACKAGE_ROOT}/${TCEXTTOOLS_SRC}"
-PACKAGE_EXTENSIONS="${PACKAGE_ROOT}/${TCEXTTOOLS_EXTENSIONS}"
-PACKAGE_PATCHES="${PACKAGE_SRC}/${TCEXTTOOLS_PATCHES}"
+PACKAGE_ROOT="$PWD"
+PACKAGE_COMMON="$PACKAGE_ROOT"/"$TCEXTTOOLS_COMMON"
+PACKAGE_BUILD="$PACKAGE_ROOT"/"$TCEXTTOOLS_BUILD"
+PACKAGE_SRC="$PACKAGE_ROOT"/"$TCEXTTOOLS_SRC"
+PACKAGE_EXTENSIONS="$PACKAGE_ROOT"/"$TCEXTTOOLS_EXTENSIONS"
+PACKAGE_PATCHES="$PACKAGE_SRC"/"$TCEXTTOOLS_PATCHES"
 
-if [ -e "${TCEXTTOOLS_COMMON}" ]; then
-     . ${TCEXTTOOLS_COMMON}
+if [ -e "$TCEXTTOOLS_COMMON" ]; then
+     . $TCEXTTOOLS_COMMON
 
-     TCEXTTOOLS_BIN="${TCEXTTOOLS_STORAGE}/${PACKAGE}/${TCEXTTOOLS_BIN}"
-     TCEXTTOOLS_SRC="${TCEXTTOOLS_STORAGE}/${PACKAGE}/${TCEXTTOOLS_SRC}"
-     TCEXTTOOLS_PKG="${TCEXTTOOLS_STORAGE}/${PACKAGE}/${TCEXTTOOLS_PKG}/${PACKAGE}"
-     TCEXTTOOLS_LOG="${TCEXTTOOLS_STORAGE}/${PACKAGE}/${TCEXTTOOLS_LOG}"
-     TCEXTTOOLS_EXTENSIONS="${TCEXTTOOLS_STORAGE}/${PACKAGE}/${TCEXTTOOLS_EXTENSIONS}"
+     TCEXTTOOLS_BIN="$TCEXTTOOLS_STORAGE"/"$PACKAGE"/"$TCEXTTOOLS_BIN"
+     TCEXTTOOLS_SRC="$TCEXTTOOLS_STORAGE"/"$PACKAGE"/"$TCEXTTOOLS_SRC"
+     TCEXTTOOLS_PKG="$TCEXTTOOLS_STORAGE"/"$PACKAGE"/"$TCEXTTOOLS_PKG"/"$PACKAGE"
+     TCEXTTOOLS_LOG="$TCEXTTOOLS_STORAGE"/"$PACKAGE"/"$TCEXTTOOLS_LOG"
+     TCEXTTOOLS_EXTENSIONS="$TCEXTTOOLS_STORAGE"/"$PACKAGE"/"$TCEXTTOOLS_EXTENSIONS"
 
-     TCEXTTOOLS_INSTALL_ROOT="${TCEXTTOOLS_BIN}/root"
-     INSTALL_ROOT="${TCEXTTOOLS_INSTALL_ROOT}"
-     TCEXTTOOLS_BIN_TEMP="${TCEXTTOOLS_BIN}/temp"
-     TCEXTTOOLS_SRC_TEMP="${TCEXTTOOLS_SRC}/temp"
+     TCEXTTOOLS_INSTALL_ROOT="$TCEXTTOOLS_BIN"/root
+     INSTALL_ROOT="$TCEXTTOOLS_INSTALL_ROOT"
+     TCEXTTOOLS_BIN_TEMP="$TCEXTTOOLS_BIN"/temp
+     TCEXTTOOLS_SRC_TEMP="$TCEXTTOOLS_SRC"/temp
 
-     TCEXTTOOLS_CONFIGURE_LOG="${TCEXTTOOLS_LOG}/configure.txt"
-     TCEXTTOOLS_COMPILE_LOG="${TCEXTTOOLS_LOG}/compile.txt"
-     TCEXTTOOLS_INSTALL_LOG="${TCEXTTOOLS_LOG}/install.txt"
-     TCEXTTOOLS_BUILD_LOG="${TCEXTTOOLS_LOG}/build.txt"
-     TCEXTTOOLS_ERROR_LOG="${TCEXTTOOLS_LOG}/error.txt"
-     TCEXTTOOLS_ERROR_LOG_2="${TCEXTTOOLS_LOG}/error2.txt"
+     TCEXTTOOLS_CONFIGURE_LOG="$TCEXTTOOLS_LOG"/configure.txt
+     TCEXTTOOLS_COMPILE_LOG="$TCEXTTOOLS_LOG"/compile.txt
+     TCEXTTOOLS_INSTALL_LOG="$TCEXTTOOLS_LOG"/install.txt
+     TCEXTTOOLS_BUILD_LOG="$TCEXTTOOLS_LOG"/build.txt
+     TCEXTTOOLS_ERROR_LOG="$TCEXTTOOLS_LOG"/error.txt
+     TCEXTTOOLS_ERROR_LOG_2="$TCEXTTOOLS_LOG"/error2.txt
 
-     [ -d "${TCEXTTOOLS_BIN}" ] || install -m 755 -d ${TCEXTTOOLS_BIN}
-     [ -d "${TCEXTTOOLS_SRC}" ] || install -m 755 -d ${TCEXTTOOLS_SRC}
-     [ -d "${TCEXTTOOLS_PKG}" ] || install -m 755 -d ${TCEXTTOOLS_PKG}
-     [ -d "${TCEXTTOOLS_BIN_TEMP}" ] || install -m 755 -d ${TCEXTTOOLS_BIN_TEMP}
-     [ -d "${TCEXTTOOLS_SRC_TEMP}" ] || install -m 755 -d ${TCEXTTOOLS_SRC_TEMP}
-     [ -d "${TCEXTTOOLS_LOG}" ] || install -m 755 -d ${TCEXTTOOLS_LOG}
+     [ -d "$TCEXTTOOLS_BIN" ] || install -m 755 -d "$TCEXTTOOLS_BIN"
+     [ -d "$TCEXTTOOLS_SRC" ] || install -m 755 -d "$TCEXTTOOLS_SRC"
+     [ -d "$TCEXTTOOLS_PKG" ] || install -m 755 -d "$TCEXTTOOLS_PKG"
+     [ -d "$TCEXTTOOLS_BIN_TEMP" ] || install -m 755 -d "$TCEXTTOOLS_BIN_TEMP"
+     [ -d "$TCEXTTOOLS_SRC_TEMP" ] || install -m 755 -d "$TCEXTTOOLS_SRC_TEMP"
+     [ -d "$TCEXTTOOLS_LOG" ] || install -m 755 -d "$TCEXTTOOLS_LOG"
 
-elif [ ! "${THIS}" = "boostit" ]; then
-     print_it error "tc-ext-tools common file not found: ${TCEXTTOOLS_COMMON}"
+elif [ ! "$THIS" = "boostit" ]; then
+     print_it error "tc-ext-tools common file not found: $TCEXTTOOLS_COMMON"
      print_it warning "You must boost it first!"
      exit 1
 fi
 
-## date
+# date
 YEAR=$(date +%Y)
 MONTH=$(date +%m)
 DAY=$(date +%d)
-DATE="${YEAR}/${MONTH}/${DAY}"
+DATE="$YEAR"/"$MONTH"/"$DAY"
 #
-
-if [ ! "${THIS}" = "buildit" -o ! "${1}" = "cat" ] && [ ! "${THIS}" = "boostit" ] && [ ! "${THIS}" = "loadit" ]; then
-     loadit "${TCEXTTOOLS_DEPENDS}" > ${TCEXTTOOLS_ERROR_LOG} 2>&1
-     if [ $? -gt 0 ]; then
-          print_it error "Loading tc-ext-tools dependencies failed : ${TCEXTTOOLS_DEPENDS}"
-          print_it warning "See error logs in ${TCEXTTOOLS_LOG} for details."
-          exit 1
-     fi
-fi
-
-##
diff --git a/trunk/tools/boostit b/trunk/tools/boostit
--- a/trunk/tools/boostit
+++ b/trunk/tools/boostit
@@ -23,32 +23,32 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-PACKAGE="${1}"
-VERSION="${2}"
-EXTENSIONS="${3}"
+PACKAGE="$1"
+VERSION="$2"
+EXTENSIONS="$3"
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extensions\"${NORMAL}"
+  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) package version \"extension1 extension2 ...\"${NORMAL}"
 }
 
-if [ -z "${PACKAGE}" ] || [ -z "${VERSION}" ] || [ -z "${EXTENSIONS}" ]; then
-      print_usage
-      exit 1
+if [ -z "$PACKAGE" ] || [ -z "$VERSION" ] || [ -z "$EXTENSIONS" ]; then
+     print_usage
+     exit 1
 fi
 
-print_it "You entered:\n\n\tPACKAGE=${PACKAGE}\n\tVERSION=${VERSION}\n\tEXTENSIONS=${EXTENSIONS}\n"
+print_it "You entered:\n\n\tPACKAGE=$PACKAGE\n\tVERSION=$VERSION\n\tEXTENSIONS=$EXTENSIONS\n"
 
-if [ -e "${PACKAGE_COMMON}" ]; then
+if [ -e "$PACKAGE_COMMON" ]; then
      print_it warning "Warning! This package looks to be boosted before.\nIf you continue existing files will be overwritten.\nWould you like you continue ? [y or n]"
      read ans
-     case ${ans} in
+     case "$ans" in
           y)
             print_it "You agreed to continue. The files will be overwritten."
             ;;
@@ -65,14 +65,14 @@ fi
 
 this_main() {
 
-  if [ ! -d "${PACKAGE_EXTENSIONS}" ]; then
-      install -m 755 -d ${PACKAGE_EXTENSIONS} || return 1
+  if [ ! -d "$PACKAGE_EXTENSIONS" ]; then
+       install -m 755 -d $PACKAGE_EXTENSIONS || return 1
   fi
 
-  if [ "X${VERSION}" = "Xsvn" ]; then
+  if [ "$VERSION" = "svn" ]; then
 
-  cat > ${PACKAGE_COMMON} << _EOF
-PACKAGE="${PACKAGE}"
+       cat > $PACKAGE_COMMON << _EOF
+PACKAGE="$PACKAGE"
 VERSION="svn\${YEAR}\${MONTH}\${DAY}"
 TOP_SRC="\${PACKAGE}-\${VERSION}"
 SOURCE="\${TOP_SRC}.tar.xz"
@@ -82,22 +82,22 @@ ICON=""
 DESKTOP_ENTRY=""
 BUILD_DEPENDS=""
 
-EXTENSIONS="${EXTENSIONS}"
+EXTENSIONS="$EXTENSIONS"
 DESCRIPTION="A brief description of package."
 AUTHOR="authors of package"
 SITE="http://www.package.com"
 COPYING="GPL-2"
-MAINTAINERS="${PACKAGE_MAINTAINER}"
+MAINTAINERS="$PACKAGE_MAINTAINER"
 COMMENTS="This extension is PPI compatible."
 CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-  [ $? -gt 0 ] && return 1
+       [ "$?" -gt 0 ] && return 1
 
-  elif [ "X${VERSION}" = "Xgit" ]; then
+  elif [ "$VERSION" = "git" ]; then
 
-  cat > ${PACKAGE_COMMON} << _EOF
+       cat > $PACKAGE_COMMON << _EOF
 PACKAGE="${PACKAGE}"
 VERSION="git\${YEAR}\${MONTH}\${DAY}"
 TOP_SRC="\${PACKAGE}-\${VERSION}"
@@ -108,24 +108,24 @@ ICON=""
 DESKTOP_ENTRY=""
 BUILD_DEPENDS=""
 
-EXTENSIONS="${EXTENSIONS}"
+EXTENSIONS="$EXTENSIONS"
 DESCRIPTION="A brief description of package."
 AUTHOR="authors of package"
 SITE="http://www.package.com"
 COPYING="GPL-2"
-MAINTAINERS="${PACKAGE_MAINTAINER}"
+MAINTAINERS="$PACKAGE_MAINTAINER"
 COMMENTS="This extension is PPI compatible."
 CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-  [ $? -gt 0 ] && return 1
+       [ "$?" -gt 0 ] && return 1
 
   else
 
-  cat > ${PACKAGE_COMMON} << _EOF
-PACKAGE="${PACKAGE}"
-VERSION="${VERSION}"
+       cat > $PACKAGE_COMMON << _EOF
+PACKAGE="$PACKAGE"
+VERSION="$VERSION"
 SOURCE="\${PACKAGE}-\${VERSION}.tar.bz2"
 TOP_SRC="\${PACKAGE}-\${VERSION}"
 SOURCE_URL=""
@@ -133,34 +133,34 @@ ICON=""
 DESKTOP_ENTRY=""
 BUILD_DEPENDS=""
 
-EXTENSIONS="${EXTENSIONS}"
+EXTENSIONS="$EXTENSIONS"
 DESCRIPTION="A brief description of package."
 AUTHOR="authors of package"
 SITE="http://www.package.com"
 COPYING="GPL-2"
-MAINTAINERS="${PACKAGE_MAINTAINER}"
+MAINTAINERS="$PACKAGE_MAINTAINER"
 COMMENTS="This extension is PPI compatible."
 CHANGELOG="---"
 CURRENT="First Version"
 _EOF
 
-  [ $? -gt 0 ] && return 1
+       [ "$?" -gt 0 ] && return 1
 
   fi
 
-  install -m 644 ${TCEXTTOOLS_ROOT}/share/tc-ext-tools/build ${PACKAGE_BUILD} || return 1
+  install -m 644 "$TCEXTTOOLS_ROOT"/share/tc-ext-tools/build $PACKAGE_BUILD || return 1
 
-  for EXTENSION in ${EXTENSIONS}
+  for EXTENSION in $EXTENSIONS
   do
-      mkdir -p ${PACKAGE_EXTENSIONS}/${EXTENSION} || return 1
-      touch ${PACKAGE_EXTENSIONS}/${EXTENSION}/install || return 1
-      if [ "${EXTENSION%-doc}" = "${EXTENSION}" ]; then
-           touch ${PACKAGE_EXTENSIONS}/${EXTENSION}/dep || return 1
+      mkdir -p "$PACKAGE_EXTENSIONS"/"$EXTENSION" || return 1
+      touch "$PACKAGE_EXTENSIONS"/"$EXTENSION"/install || return 1
+      if [ "${EXTENSION%-doc}" = "$EXTENSION" ]; then
+           touch "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
       fi
-      if [ ! "${EXTENSION%-locale}" = "${EXTENSION}" ]; then
-           echo "${EXTENSION%-locale}.tcz" > ${PACKAGE_EXTENSIONS}/${EXTENSION}/dep || return 1
-      elif [ ! "${EXTENSION%-dev}" = "${EXTENSION}" ]; then
-           echo "${EXTENSION%-dev}.tcz" > ${PACKAGE_EXTENSIONS}/${EXTENSION}/dep || return 1
+      if [ ! "${EXTENSION%-locale}" = "$EXTENSION" ]; then
+           echo "${EXTENSION%-locale}.tcz" > "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
+      elif [ ! "${EXTENSION%-dev}" = "$EXTENSION" ]; then
+           echo "${EXTENSION%-dev}.tcz" > "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep || return 1
       fi
 
   done
@@ -168,9 +168,9 @@ _EOF
   return 0
 }
 
-print_it "Boosting the package ${PACKAGE} ... \c"
+print_it "Boosting the package $PACKAGE ... \c"
 this_main > /dev/null 2>&1
-if [ $? -gt 0 ]; then
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/checkit b/trunk/tools/checkit
--- a/trunk/tools/checkit
+++ b/trunk/tools/checkit
@@ -23,47 +23,43 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-EXTENSION="${1}"
+EXTENSION="$1"
 
 print_usage(){
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
 }
 
-if [ -z "${EXTENSION}" ]; then
-      print_usage
-      exit 1
+if [ -z "$EXTENSION" ]; then
+     print_usage
+     exit 1
 fi
 
-if [ ! -e "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz" ]; then
+if [ ! -e "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz" ]; then
      print_it error "You must create it first!"
      exit 1
 fi
 
 TMPDIR=$(busybox mktemp -d)
-if [ $? -gt 0 ]; then
-     print_it error "Creating temp directory failed!"
-     exit 1
-fi
 
 this_main() {
 
-  sudo busybox mount -o loop ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz ${TMPDIR} || return 1
+  sudo busybox mount -o loop "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz" $TMPDIR || return 1
 
-  FILES=$(sudo find ${TMPDIR} -not -type d)
-  SAVEIFS=${IFS}
+  FILES=$(sudo find $TMPDIR -not -type d)
+  SAVEIFS=$IFS
   IFS=$(echo -en "\n\b")
-  for f in ${FILES}
+  for f in $FILES
   do
-      sudo file "${f}" || return 1
+      sudo file "$f" || return 1
   done
-  IFS=${SAVEIFS}
+  IFS=$SAVEIFS
 
   if [ -d "$TMPDIR"/usr/local/tce.installed ]; then
        OUT=$(sudo busybox ls -d -l "$TMPDIR"/usr/local/tce.installed)
@@ -72,40 +68,46 @@ this_main() {
 
        if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
             print_it error "Wrong permissions on $EXTENSION tce.installed directory."
+            print_it warning "Expected permissions drwxrwxr-x or drwxrwsr-x but found permissions $PERM"
             return 1
        fi
+
        if [ "$OWNER" != "root staff" ]; then
             print_it error "Wrong ownership on $EXTENSION tce.installed directory."
+            print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
             return 1
        fi
+
        if [ -e "$TMPDIR"/usr/local/tce.installed/"$EXTENSION" ]; then
             OUT=$(sudo busybox ls -l "$TMPDIR"/usr/local/tce.installed/"$EXTENSION")
             PERM=$(echo $OUT | cut -d" " -f1)
             OWNER=$(echo $OUT | cut -d" " -f3-4)
 
-            if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
+            if [ "$PERM" != "-rwxrwxr-x" ] && [ "$PERM" != "-rwxrwsr-x" ]; then
                  print_it error "Wrong permissions on $EXTENSION tce.installed script."
+                 print_it warning "Expected permissions -rwxrwxr-x or -rwxrwsr-x but found permissions $PERM"
                  return 1
             fi
+
             if [ "$OWNER" != "root staff" ]; then
                  print_it error "Wrong ownership on $EXTENSION tce.installed script."
+                 print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
                  return 1
             fi
        fi
   fi
 
-  sudo busybox umount ${TMPDIR}
-  sudo rm -rf ${TMPDIR}
-
+  sudo busybox umount $TMPDIR
+  sudo rm -rf $TMPDIR
   return 0
 }
 
-print_it "Checking the extension ${EXTENSION} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Checking the extension $EXTENSION ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
-     sudo busybox umount ${TMPDIR} > /dev/null 2>&1
-     sudo rm -rf ${TMPDIR} > /dev/null 2>&1
+     sudo busybox umount $TMPDIR > /dev/null 2>&1
+     sudo rm -rf $TMPDIR > /dev/null 2>&1
      exit 1
 fi
 
diff --git a/trunk/tools/compressit b/trunk/tools/compressit
--- a/trunk/tools/compressit
+++ b/trunk/tools/compressit
@@ -23,50 +23,50 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-FORMAT="${1}"
-TARGET="${2}"
-NAME="${3}"
+FORMAT="$1"
+TARGET="$2"
+NAME="$3"
 
 print_usage(){
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) bz2|gz|xz /path/to/target name${NORMAL}"
 }
 
-if [ -z "${TARGET}" -o -z "${FORMAT}" ]; then
+if [ -z "$TARGET" -o -z "$FORMAT" ]; then
      print_usage
      exit 1
 fi
 
 compress() {
 
-  if [ -d "${TARGET}" ]; then
-       TOP_DIR="$(basename ${TARGET})"
-       if [ -n "${NAME}" ]; then
+  if [ -d "$TARGET" ]; then
+       TOP_DIR="$(basename $TARGET)"
+       if [ -n "$NAME" ]; then
             OUTPUT="${NAME}.tar.${FORMAT}"
        else
             OUTPUT="${TOP_DIR}.tar.${FORMAT}"
        fi
 
-       [ -e "${OUTPUT}" ] && sudo rm -f ${OUTPUT}
+       [ -e "$OUTPUT" ] && sudo rm -f $OUTPUT
 
-       tar -C $(dirname ${TARGET}) -c${XXX}f ${OUTPUT} ${TOP_DIR} || return 1
+       tar -C $(dirname $TARGET) -c${XXX}f $OUTPUT $TOP_DIR || return 1
 
-  elif [ -f "${TARGET}" ]; then
-       if [ -n "${NAME}" ]; then
+  elif [ -f "$TARGET" ]; then
+       if [ -n "$NAME" ]; then
             OUTPUT="${NAME}.${FORMAT}"
        else
-            OUTPUT="$(basename ${TARGET}).${FORMAT}"
+            OUTPUT="$(basename $TARGET).${FORMAT}"
        fi
 
-       [ -e "${OUTPUT}" ] && sudo rm -f ${OUTPUT}
+       [ -e "$OUTPUT" ] && sudo rm -f $OUTPUT
 
-       ${COMPRESSOR} -c ${TARGET} > ${OUTPUT} || return 1
+       $COMPRESSOR -c $TARGET > $OUTPUT || return 1
   fi
 
   return 0
@@ -74,7 +74,7 @@ compress() {
 
 this_main() {
 
-  case ${FORMAT} in
+  case "$FORMAT" in
        bz2)
            COMPRESSOR="bzip2"
            XXX=j
@@ -98,9 +98,9 @@ this_main() {
   return 0
 }
 
-print_it "Compressing the target ${TARGET} with the compression format ${FORMAT} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Compressing the target $TARGET with the compression format $FORMAT ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/convertit b/trunk/tools/convertit
--- a/trunk/tools/convertit
+++ b/trunk/tools/convertit
@@ -23,14 +23,14 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-if [ ! -e "${TCEXTTOOLS_SRC}/${SOURCE}" ]; then
+if [ ! -e "$TCEXTTOOLS_SRC"/"$SOURCE" ]; then
      print_it error "You must download it first!"
      return 1
 fi
@@ -39,44 +39,44 @@ this_main() {
 
   TYPE=""
 
-  [ ! "${SOURCE%.bz2}" = "${SOURCE}" ] && TYPE="bz2"
-  [ ! "${SOURCE%.gz}" = "${SOURCE}" ] && TYPE="gz"
-  [ ! "${SOURCE%.tgz}" = "${SOURCE}" ] && TYPE="tgz"
-  [ ! "${SOURCE%.xz}" = "${SOURCE}" ] && TYPE="xz"
-  [ ! "${SOURCE%.zip}" = "${SOURCE}" ] && TYPE="zip"
+  [ ! "${SOURCE%.bz2}" = "$SOURCE" ] && TYPE="bz2"
+  [ ! "${SOURCE%.gz}" = "$SOURCE" ] && TYPE="gz"
+  [ ! "${SOURCE%.tgz}" = "$SOURCE" ] && TYPE="tgz"
+  [ ! "${SOURCE%.xz}" = "$SOURCE" ] && TYPE="xz"
+  [ ! "${SOURCE%.zip}" = "$SOURCE" ] && TYPE="zip"
 
-  if [ -z "${TYPE}" ]; then
-       print_it error "The type of ${SOURCE} is not yet supported!"
+  if [ -z "$TYPE" ]; then
+       print_it error "The type of $SOURCE is not yet supported!"
        exit 1
   fi
 
-  [ -d "${TCEXTTOOLS_SRC_TEMP}" ] && sudo rm -rf ${TCEXTTOOLS_SRC_TEMP}
-  mkdir -p ${TCEXTTOOLS_SRC_TEMP}
+  [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf $TCEXTTOOLS_SRC_TEMP
+  mkdir -p $TCEXTTOOLS_SRC_TEMP
 
-  if [ "X${TYPE}" = "Xbz2" -a ! -e "${TCEXTTOOLS_SRC}/${SOURCE%.bz2}.xz" ]; then
-       bzip2 -d -c ${TCEXTTOOLS_SRC}/${SOURCE} > ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.bz2} || return 1
-       xz ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.bz2} || return 1
-       busybox mv -f ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.bz2}.xz ${TCEXTTOOLS_SRC} || return 1
-  elif [ "X${TYPE}" = "Xgz" -a ! -e "${TCEXTTOOLS_SRC}/${SOURCE%.gz}.xz" ]; then
-       gzip -d -c ${TCEXTTOOLS_SRC}/${SOURCE} > ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.gz} || return 1
-       xz ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.gz} || return 1
-       busybox mv -f ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.gz}.xz ${TCEXTTOOLS_SRC} || return 1
-  elif [ "X${TYPE}" = "Xtgz" -a ! -e "${TCEXTTOOLS_SRC}/${SOURCE%.tgz}.tar.xz" ]; then
-       gzip -d -c ${TCEXTTOOLS_SRC}/${SOURCE} > ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.tgz}.tar || return 1
-       xz ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.tgz}.tar || return 1
-       busybox mv -f ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.tgz}.tar.xz ${TCEXTTOOLS_SRC} || return 1
-  elif [ "X${TYPE}" = "Xzip" -a ! -e "${TCEXTTOOLS_SRC}/${SOURCE%.zip}.tar.xz" ]; then
-       unzip ${TCEXTTOOLS_SRC}/${SOURCE} -d ${TCEXTTOOLS_TEMP} || return 1
-       tar -C ${TCEXTTOOLS_SRC_TEMP} -cJf "${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.zip}.tar.xz" ${TOP_SRC} || return 1
-       busybox mv -f ${TCEXTTOOLS_SRC_TEMP}/${SOURCE%.zip}.tar.xz ${TCEXTTOOLS_SRC} || return 1
+  if [ "$TYPE" = "bz2" -a ! -e "$TCEXTTOOLS_SRC"/"${SOURCE%.bz2}.xz" ]; then
+       bzip2 -d -c "$TCEXTTOOLS_SRC"/"$SOURCE" > "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.bz2}" || return 1
+       xz "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.bz2}" || return 1
+       busybox mv -f "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.bz2}.xz" $TCEXTTOOLS_SRC || return 1
+  elif [ "$TYPE" = "gz" -a ! -e "$TCEXTTOOLS_SRC"/"${SOURCE%.gz}.xz" ]; then
+       gzip -d -c "$TCEXTTOOLS_SRC"/"$SOURCE" > "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.gz}" || return 1
+       xz "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.gz}" || return 1
+       busybox mv -f "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.gz}.xz" $TCEXTTOOLS_SRC || return 1
+  elif [ "$TYPE" = "tgz" -a ! -e "$TCEXTTOOLS_SRC"/"${SOURCE%.tgz}.tar.xz" ]; then
+       gzip -d -c "$TCEXTTOOLS_SRC"/"$SOURCE" > "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.tgz}.tar" || return 1
+       xz "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.tgz}.tar" || return 1
+       busybox mv -f "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.tgz}.tar.xz" $TCEXTTOOLS_SRC || return 1
+  elif [ "$TYPE" = "zip" -a ! -e "$TCEXTTOOLS_SRC"/"${SOURCE%.zip}.tar.xz" ]; then
+       unzip "$TCEXTTOOLS_SRC"/"$SOURCE" -d $TCEXTTOOLS_TEMP || return 1
+       tar -C $TCEXTTOOLS_SRC_TEMP -cJf "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.zip}.tar.xz" $TOP_SRC || return 1
+       busybox mv -f "$TCEXTTOOLS_SRC_TEMP"/"${SOURCE%.zip}.tar.xz" $TCEXTTOOLS_SRC || return 1
   fi
 
   return 0
 }
 
-print_it "Converting the package ${PACKAGE} source to xz compressed tarball ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+prinst_it "Converting the package $PACKAGE source to xz compressed tarball ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/createit b/trunk/tools/createit
--- a/trunk/tools/createit
+++ b/trunk/tools/createit
@@ -23,16 +23,16 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-EXTENSION="${1}"
+EXTENSION="$1"
 
-if [ ! -d "${TCEXTTOOLS_BIN}/${EXTENSION}" ]; then
+if [ ! -d "$TCEXTTOOLS_BIN"/"$EXTENSION" ]; then
      print_it error "You must split it first!"
      exit 1
 fi
@@ -41,55 +41,55 @@ print_usage() {
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
 }
 
-if [ -z "${EXTENSION}" ]; then
-      print_usage
-      exit 1
+if [ -z "$EXTENSION" ]; then
+     print_usage
+     exit 1
 fi
 
 this_main() {
 
-  cd ${PACKAGE_ROOT}
+  cd $PACKAGE_ROOT
 
-  if [ -e "${PACKAGE_EXTENSIONS}/${EXTENSION}/tce.installed" ]; then
-       sudo install -m 775 -D ${PACKAGE_EXTENSIONS}/${EXTENSION}/tce.installed ${TCEXTTOOLS_BIN}/${EXTENSION}/usr/local/tce.installed/${EXTENSION} || return 1
-       sudo chown -R root:staff ${TCEXTTOOLS_BIN}/${EXTENSION}/usr/local/tce.installed || return 1
-       sudo chmod -R 775 ${TCEXTTOOLS_BIN}/${EXTENSION}/usr/local/tce.installed || return 1
+  if [ -e "$PACKAGE_EXTENSIONS"/"$EXTENSION"/tce.installed ]; then
+       sudo install -m 775 -D "$PACKAGE_EXTENSIONS"/"$EXTENSION"/tce.installed "$TCEXTTOOLS_BIN"/"$EXTENSION"/usr/local/tce.installed/"$EXTENSION" || return 1
+       sudo chown -R root:staff "$TCEXTTOOLS_BIN"/"$EXTENSION"/usr/local/tce.installed || return 1
+       sudo chmod -R 775 "$TCEXTTOOLS_BIN"/"$EXTENSION"/usr/local/tce.installed || return 1
   fi
 
-  cd ${TCEXTTOOLS_BIN}
+  cd $TCEXTTOOLS_BIN
 
-  [ -e ${EXTENSION}.tcz ] && sudo rm -f ${EXTENSION}.tcz
-  [ -e ${EXTENSION}.tcz.list ] && sudo rm -f ${EXTENSION}.tcz.list
-  [ -e ${EXTENSION}.tcz.md5.txt ] && sudo rm -f ${EXTENSION}.tcz.md5.txt
+  [ -e "${EXTENSION}.tcz" ] && sudo rm -f "${EXTENSION}.tcz"
+  [ -e "${EXTENSION}.tcz.list" ] && sudo rm -f "${EXTENSION}.tcz.list"
+  [ -e "${EXTENSION}.tcz.md5.txt" ] && sudo rm -f "${EXTENSION}.tcz.md5.txt"
 
-  sudo mksquashfs ${EXTENSION} ${EXTENSION}.tcz || return 1
+  sudo mksquashfs $EXTENSION "${EXTENSION}.tcz" || return 1
 
-  md5sum ${EXTENSION}.tcz > ${EXTENSION}.tcz.md5.txt || return 1
+  md5sum "${EXTENSION}.tcz" > "${EXTENSION}.tcz.md5.txt" || return 1
 
-  cd ${TCEXTTOOLS_BIN}/${EXTENSION}
+  cd "$TCEXTTOOLS_BIN"/"$EXTENSION"
   for i in $(ls)
   do
-      sudo find ${i} -not -type d >> ${TCEXTTOOLS_BIN}/${EXTENSION}.tcz.list
+      sudo find "$i" -not -type d >> "$TCEXTTOOLS_BIN"/"${EXTENSION}.tcz.list"
   done
 
-  cd ${PACKAGE_ROOT}
+  cd $PACKAGE_ROOT
 
-  [ -d "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}" ] || mkdir -p ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}
+  [ -d "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION" ] || mkdir -p "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"
 
-  busybox cp -f ${TCEXTTOOLS_BIN}/${EXTENSION}.tcz* ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION} || return 1
+  busybox cp -f "$TCEXTTOOLS_BIN"/"${EXTENSION}.tcz"* "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION" || return 1
 
-  if [ -e "${PACKAGE_EXTENSIONS}/${EXTENSION}/dep" ]; then
-       install -m 644 ${PACKAGE_EXTENSIONS}/${EXTENSION}/dep ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz.dep || return 1
+  if [ -e "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep ]; then
+       install -m 644 "$PACKAGE_EXTENSIONS"/"$EXTENSION"/dep "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz.dep" || return 1
   fi
 
-  sudo rm -f ${TCEXTTOOLS_BIN}/${EXTENSION}.tcz*
+  sudo rm -f "$TCEXTTOOLS_BIN"/"${EXTENSION}.tcz"*
 
   return 0
 }
 
-print_it "Creating the extension ${EXTENSION} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Creating the extension $EXTENSION ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/downloadit b/trunk/tools/downloadit
--- a/trunk/tools/downloadit
+++ b/trunk/tools/downloadit
@@ -23,40 +23,40 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
 this_main() {
 
-  [ -d "${TCEXTTOOLS_SRC}" ] && sudo rm -rf ${TCEXTTOOLS_SRC}
-  mkdir -p ${TCEXTTOOLS_SRC} || return 1
+  [ -d "$TCEXTTOOLS_SRC" ] && sudo rm -rf $TCEXTTOOLS_SRC
+  mkdir -p $TCEXTTOOLS_SRC || return 1
 
-  if [ -n "${SOURCE_SVN}" ]; then
-       [ -d "${TCEXTTOOLS_SRC_TEMP}" ] && sudo rm -rf ${TCEXTTOOLS_SRC_TEMP}
-       mkdir -p ${TCEXTTOOLS_SRC_TEMP}
-       svn co ${SOURCE_URL} ${TCEXTTOOLS_SRC_TEMP}/${TOP_SRC} || return 1
-       compressit xz ${TCEXTTOOLS_SRC_TEMP}/${TOP_SRC} || return 1
-       busybox mv -f ${SOURCE} ${TCEXTTOOLS_SRC} || return 1
-  elif [ -n "${SOURCE_GIT}" ]; then
-       [ -d "${TCEXTTOOLS_SRC_TEMP}" ] && sudo rm -rf ${TCEXTTOOLS_SRC_TEMP}
-       mkdir -p ${TCEXTTOOLS_SRC_TEMP}
-       git clone ${SOURCE_URL} ${TCEXTTOOLS_SRC_TEMP}/${TOP_SRC} || return 1
-       compressit xz ${TCEXTTOOLS_SRC_TEMP}/${TOP_SRC} || return 1
-       busybox mv -f ${SOURCE} ${TCEXTTOOLS_SRC} || return 1
+  if [ -n "$SOURCE_SVN" ]; then
+       [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf $TCEXTTOOLS_SRC_TEMP
+       mkdir -p $TCEXTTOOLS_SRC_TEMP
+       svn co $SOURCE_URL "$TCEXTTOOLS_SRC_TEMP"/"$TOP_SRC" || return 1
+       compressit xz "$TCEXTTOOLS_SRC_TEMP"/"$TOP_SRC" || return 1
+       busybox mv -f $SOURCE $TCEXTTOOLS_SRC || return 1
+  elif [ -n "$SOURCE_GIT" ]; then
+       [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf $TCEXTTOOLS_SRC_TEMP
+       mkdir -p $TCEXTTOOLS_SRC_TEMP
+       git clone $SOURCE_URL "$TCEXTTOOLS_SRC_TEMP"/"$TOP_SRC" || return 1
+       compressit xz "$TCEXTTOOLS_SRC_TEMP"/"$TOP_SRC" || return 1
+       busybox mv -f $SOURCE $TCEXTTOOLS_SRC || return 1
   else
-       wget --no-check-certificate ${SOURCE_URL} -O ${TCEXTTOOLS_SRC}/${SOURCE} || return 1
+       wget --no-check-certificate $SOURCE_URL -O "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
   fi
 
   return 0
 }
 
-print_it "Downloading the package ${PACKAGE} source ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Downloading the package $PACKAGE source ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/modifyit b/trunk/tools/modifyit
--- a/trunk/tools/modifyit
+++ b/trunk/tools/modifyit
@@ -23,14 +23,14 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!{NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-if [ ! -d "${TCEXTTOOLS_INSTALL_ROOT}" ]; then
+if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
      print_it error "You must install it first!"
      exit 1
 fi
@@ -38,45 +38,45 @@ fi
 this_main() {
 
   # We need to convert symlinks to full path for gnome help browser files
-  if [ -d "${TCEXTTOOLS_INSTALL_ROOT}/usr/local/share/gnome/help" ]; then
-       for l in $(sudo find ${TCEXTTOOLS_INSTALL_ROOT}/usr/local/share/gnome/help -type l)
+  if [ -d "$TCEXTTOOLS_INSTALL_ROOT"/usr/local/share/gnome/help ]; then
+       for l in $(sudo find "$TCEXTTOOLS_INSTALL_ROOT"/usr/local/share/gnome/help -type l)
        do
-           FILE=$(sudo busybox readlink -f ${l})
-           LINK=${FILE#${TCEXTTOOLS_INSTALL_ROOT}}
-           sudo busybox ln -sf ${LINK} ${l} || return 1
+           FILE=$(sudo busybox readlink -f "$l")
+           LINK="${FILE#${TCEXTTOOLS_INSTALL_ROOT}}"
+           sudo busybox ln -sf "$LINK" "$l" || return 1
        done
   fi
   #
 
   # Add wbar icon if ICON variable is set
-  if [ -n "${ICON}" ]; then
-       if [ ! -e "${TCEXTTOOLS_INSTALL_ROOT}/${ICON}" ]; then
-            print_it error "The icon: ${TCEXTTOOLS_INSTALL_ROOT}/${ICON} does not exist!"
+  if [ -n "$ICON" ]; then
+       if [ ! -e "$TCEXTTOOLS_INSTALL_ROOT"/"$ICON" ]; then
+            print_it error "The icon: $TCEXTTOOLS_INSTALL_ROOT/$ICON does not exist!"
             return 1
-       elif [ ! -e "${TCEXTTOOLS_INSTALL_ROOT}/${DESKTOP_ENTRY}" ]; then
-            print_it error "The desktop entry: ${TCEXTTOOLS_INSTALL_ROOT}/${DESKTOP_ENTRY} does not exist!"
+       elif [ ! -e "$TCEXTTOOLS_INSTALL_ROOT"/"$DESKTOP_ENTRY" ]; then
+            print_it error "The desktop entry: $TCEXTTOOLS_INSTALL_ROOT/$DESKTOP_ENTRY does not exist!"
             return 1
        else
-            sudo sh -c "echo 'X-FullPathIcon=${ICON}' >> ${TCEXTTOOLS_INSTALL_ROOT}/${DESKTOP_ENTRY}" || return 1
+            sudo sh -c "echo 'X-FullPathIcon=${ICON}' >> $TCEXTTOOLS_INSTALL_ROOT/$DESKTOP_ENTRY" || return 1
        fi
   fi
   #
 
   # Create a list of package contents so that user can choose where to put files
-  [ -e "${PACKAGE_EXTENSIONS}/${PACKAGE}.list" ] && sudo rm -f ${PACKAGE_EXTENSIONS}/${PACKAGE}.list
+  [ -e "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list" ] && sudo rm -f "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list"
 
-  cd ${TCEXTTOOLS_INSTALL_ROOT}
+  cd $TCEXTTOOLS_INSTALL_ROOT
   for i in $(ls)
   do
-      sudo find ${i} -not -type d >> ${PACKAGE_EXTENSIONS}/${PACKAGE}.list || return 1
+      sudo find "$i" -not -type d >> "$PACKAGE_EXTENSIONS"/"${PACKAGE}.list" || return 1
   done
 
   return 0
 }
 
-print_it "Modifying the package ${PACKAGE} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Modifying the package $PACKAGE ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/patchit b/trunk/tools/patchit
--- a/trunk/tools/patchit
+++ b/trunk/tools/patchit
@@ -23,36 +23,36 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-if [ ! -d "${TCEXTTOOLS_BIN_TEMP}/${TOP_SRC}" ]; then
+if [ ! -d "$TCEXTTOOLS_BIN_TEMP"/"$TOP_SRC" ]; then
      print_it error "You must unpack it first!"
      exit 1
 fi
 
 this_main() {
-  if [ -f "${PACKAGE_PATCHES}/series" ]; then
-       PATCHES=$(cat ${PACKAGE_PATCHES}/series)
-       for PATCH in ${PATCHES}
+  if [ -f "$PACKAGE_PATCHES"/series ]; then
+       PATCHES=$(cat "$PACKAGE_PATCHES"/series)
+       for PATCH in $PATCHES
        do
-           if [ "${PATCH#"#"}" = "${PATCH}" ]; then
-                if [ -f ${PACKAGE_PATCHES}/${PATCH} ]; then
-                     patch --directory="${TCEXTTOOLS_BIN_TEMP}/${TOP_SRC}" -Np1 -i ${PACKAGE_PATCHES}/${PATCH} || return 1
+           if [ "${PATCH#"#"}" = "$PATCH" ]; then
+                if [ -f "$PACKAGE_PATCHES"/"$PATCH" ]; then
+                     patch --directory="$TCEXTTOOLS_BIN_TEMP"/"$TOP_SRC" -Np1 -i "$PACKAGE_PATCHES"/"$PATCH" || return 1
                 fi
            fi
        done
-  elif [ -d "${PACKAGE_PATCHES}" ]; then
-       PATCHES=$(ls ${PACKAGE_PATCHES})
-       if [ -n "${PATCHES}" ]; then
-            for PATCH in ${PATCHES}
+  elif [ -d "$PACKAGE_PATCHES" ]; then
+       PATCHES=$(ls $PACKAGE_PATCHES)
+       if [ -n "$PATCHES" ]; then
+            for PATCH in $PATCHES
             do
-                if [ -f "${PACKAGE_PATCHES}/${PATCH}" ]; then
-                     patch --directory="${TCEXTTOOLS_BIN_TEMP}/${TOP_SRC}" -Np1 -i ${PACKAGE_PATCHES}/${PATCH} || return 1
+                if [ -f "$PACKAGE_PATCHES"/"$PATCH" ]; then
+                     patch --directory="$TCEXTTOOLS_BIN_TEMP"/"$TOP_SRC" -Np1 -i "$PACKAGE_PATCHES"/"$PATCH" || return 1
                 fi
             done
        fi
@@ -61,9 +61,9 @@ this_main() {
   return 0
 }
 
-print_it "Patching the package ${PACKAGE} source ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Patching the package $PACKAGE source ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/trunk/tools/splitit b/trunk/tools/splitit
--- a/trunk/tools/splitit
+++ b/trunk/tools/splitit
@@ -23,78 +23,74 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-EXTENSION="${1}"
+EXTENSION="$1"
 
 print_usage() {
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
 }
 
-if [ ! -d "${TCEXTTOOLS_INSTALL_ROOT}" ]; then
+if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
      print_it error "You must install it first!"
      exit 1
 fi
 
-if [ ! -f "${PACKAGE_EXTENSIONS}/${EXTENSION}/install" ]; then
+if [ ! -f "$PACKAGE_EXTENSIONS"/"$EXTENSION"/install ]; then
       print_usage
       exit 1
 fi
 
 TMP_DIR=$(busybox mktemp -d)
-if [ $? -gt 0 ]; then
-     print_it error "Creating temp directory failed!"
-     exit 1
-fi
 
 this_main() {
 
-  CONTENTS=$(cat ${PACKAGE_EXTENSIONS}/${EXTENSION}/install)
-  [ -z "${CONTENTS}" ] && return 1
+  CONTENTS=$(cat "$PACKAGE_EXTENSIONS"/"$EXTENSION"/install)
+  [ -z "$CONTENTS" ] && return 1
 
   LIST="${TMP_DIR}/install.list"
   X_LIST="${TMP_DIR}/x-install.list"
 
-  touch ${LIST} || return 1
-  touch ${X_LIST} || return 1
+  touch $LIST || return 1
+  touch $X_LIST || return 1
 
-  cd ${TCEXTTOOLS_INSTALL_ROOT}
+  cd $TCEXTTOOLS_INSTALL_ROOT
 
-  for i in ${CONTENTS}
+  for i in $CONTENTS
   do
-      if [ "${i#"#"}" = "${i}" ]; then
-           if [ "${i#x-}" = "${i}" ]; then
-                sudo find ${i} -not -type d >> ${LIST} || return 1
+      if [ "${i#\#}" = "$i" ]; then
+           if [ "${i#x-}" = "$i" ]; then
+                sudo find $i -not -type d >> $LIST || return 1
            else
-                sudo find ${i#x-} -not -type d >> ${X_LIST} || return 1
+                sudo find ${i#x-} -not -type d >> $X_LIST || return 1
            fi
       fi
   done
 
-  sudo tar -T ${LIST} -X ${X_LIST} -cpzf ${TMP_DIR}/pkg.tar.gz || return 1
-  sudo mkdir ${TMP_DIR}/root
-  sudo tar -C ${TMP_DIR}/root -pxzf ${TMP_DIR}/pkg.tar.gz || return 1
+  sudo tar -T $LIST -X $X_LIST -cpzf "$TMP_DIR"/pkg.tar.gz || return 1
+  sudo mkdir "$TMP_DIR"/root
+  sudo tar -C "$TMP_DIR"/root -pxzf "$TMP_DIR"/pkg.tar.gz || return 1
 
-  if [ -d "${TCEXTTOOLS_BIN}/${EXTENSION}" ]; then
-       sudo rm -rf ${TCEXTTOOLS_BIN}/${EXTENSION} || return 1
+  if [ -d "$TCEXTTOOLS_BIN"/"$EXTENSION" ]; then
+       sudo rm -rf "$TCEXTTOOLS_BIN"/"$EXTENSION" || return 1
   fi
 
-  sudo mv ${TMP_DIR}/root ${TCEXTTOOLS_BIN}/${EXTENSION} || return 1
-  sudo rm -rf ${TMP_DIR}
+  sudo mv "$TMP_DIR"/root "$TCEXTTOOLS_BIN"/"$EXTENSION" || return 1
+  sudo rm -rf $TMP_DIR
 
   return 0
 }
 
-print_it "Splitting the extension ${EXTENSION} out of the package ${PACKAGE} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Splitting the extension $EXTENSION out of the package $PACKAGE ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
-     sudo rm -rf ${TMP_DIR} > /dev/null 2>&1
+     [ -d "$TMP_DIR" ] && sudo rm -rf $TMP_DIR > /dev/null 2>&1
      exit 1
 fi
 print_it hilight "successful!"
diff --git a/trunk/tools/unpackit b/trunk/tools/unpackit
--- a/trunk/tools/unpackit
+++ b/trunk/tools/unpackit
@@ -23,14 +23,14 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-if [ ! -e "${TCEXTTOOLS_SRC}/${SOURCE}" ]; then
+if [ ! -e "$TCEXTTOOLS_SRC"/"$SOURCE" ]; then
      print_it error "You must download it first!"
      return 1
 fi
@@ -39,36 +39,36 @@ this_main() {
 
   TYPE=""
 
-  [ ! "${SOURCE%.bz2}" = "${SOURCE}" ] && TYPE="bz2"
-  [ ! "${SOURCE%.gz}" = "${SOURCE}" ] && TYPE="gz"
-  [ ! "${SOURCE%.tgz}" = "${SOURCE}" ] && TYPE="tgz"
-  [ ! "${SOURCE%.xz}" = "${SOURCE}" ] && TYPE="xz"
-  [ ! "${SOURCE%.zip}" = "${SOURCE}" ] && TYPE="zip"
+  [ ! "${SOURCE%.bz2}" = "$SOURCE" ] && TYPE="bz2"
+  [ ! "${SOURCE%.gz}" = "$SOURCE" ] && TYPE="gz"
+  [ ! "${SOURCE%.tgz}" = "$SOURCE" ] && TYPE="tgz"
+  [ ! "${SOURCE%.xz}" = "$SOURCE" ] && TYPE="xz"
+  [ ! "${SOURCE%.zip}" = "$SOURCE" ] && TYPE="zip"
 
-  if [ -z "${TYPE}" ]; then
-       print_it error "The type of ${SOURCE} is not yet supported!"
+  if [ -z "$TYPE" ]; then
+       print_it error "The type of $SOURCE is not yet supported!"
        exit 1
   fi
 
-  [ -d "${TCEXTTOOLS_BIN_TEMP}" ] && sudo rm -rf ${TCEXTTOOLS_BIN_TEMP}
-  mkdir -p ${TCEXTTOOLS_BIN_TEMP}
+  [ -d "$TCEXTTOOLS_BIN_TEMP" ] && sudo rm -rf $TCEXTTOOLS_BIN_TEMP
+  mkdir -p $TCEXTTOOLS_BIN_TEMP
 
-  if [ "X${TYPE}" = "Xbz2" ]; then
-       tar -C ${TCEXTTOOLS_BIN_TEMP} -xjf ${TCEXTTOOLS_SRC}/${SOURCE} || return 1
-  elif [ "X${TYPE}" = "Xgz" -o "X${TYPE}" = "Xtgz" ]; then
-       tar -C ${TCEXTTOOLS_BIN_TEMP} -xzf ${TCEXTTOOLS_SRC}/${SOURCE} || return 1
-  elif [ "X${TYPE}" = "Xxz" ]; then
-       tar -C ${TCEXTTOOLS_BIN_TEMP} -xJf ${TCEXTTOOLS_SRC}/${SOURCE} || return 1
-  elif [ "X${TYPE}" = "Xzip" ]; then
-       unzip ${TCEXTTOOLS_SRC}/${SOURCE} -d ${TCEXTTOOLS_BIN_TEMP} || return 1
+  if [ "$TYPE" = "bz2" ]; then
+       tar -C $TCEXTTOOLS_BIN_TEMP -xjf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
+  elif [ "$TYPE" = "gz" -o "$TYPE" = "tgz" ]; then
+       tar -C $TCEXTTOOLS_BIN_TEMP -xzf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
+  elif [ "$TYPE" = "xz" ]; then
+       tar -C $TCEXTTOOLS_BIN_TEMP -xJf "$TCEXTTOOLS_SRC"/"$SOURCE" || return 1
+  elif [ "$TYPE" = "zip" ]; then
+       unzip "$TCEXTTOOLS_SRC"/"$SOURCE" -d $TCEXTTOOLS_BIN_TEMP || return 1
   fi
 
   return 0
 }
 
-print_it "Unpacking the package ${PACKAGE} source ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Unpacking the package $PACKAGE source ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
