- Revolutionary changes with this update - Added support for packages with custom source such as nvidia - Updated buildit and other tools to fit design standarts - Added new tool cleanit as a result of buildit update - Updated packageit not to package custom src directory anymore - And many others see diff for details

diff --git a/trunk/default/functions b/trunk/default/functions
--- a/trunk/default/functions
+++ b/trunk/default/functions
@@ -1,4 +1,22 @@
-# tc-ext-tools functions
+#
+#  functions: common tc-ext-tools functions and definitions
+#
+#  This program is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation; either version 2 of the License, or
+#  (at your option) any later version.
+#
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
+#
+#  You should have received a copy of the GNU General Public License along
+#  with this program; if not, write to the Free Software Foundation, Inc.,
+#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#  (C) Copyright 2010 Sercan Arslan
+#
 
 THIS=$(basename $0)
 
@@ -55,8 +73,8 @@ PACKAGE_SRC="$PACKAGE_ROOT/$TCEXTTOOLS_SRC"
 PACKAGE_EXTENSIONS="$PACKAGE_ROOT/$TCEXTTOOLS_EXTENSIONS"
 PACKAGE_PATCHES="$PACKAGE_SRC/$TCEXTTOOLS_PATCHES"
 
-if [ -e "$TCEXTTOOLS_COMMON" ]; then
-     . "$TCEXTTOOLS_COMMON"
+if [ -e "$PACKAGE_COMMON" ]; then
+     . "$PACKAGE_COMMON"
 
      TCEXTTOOLS_BIN="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_BIN"
      TCEXTTOOLS_SRC="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_SRC"
@@ -64,7 +82,6 @@ if [ -e "$TCEXTTOOLS_COMMON" ]; then
      TCEXTTOOLS_LOG="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_LOG"
      TCEXTTOOLS_EXTENSIONS="$TCEXTTOOLS_STORAGE/$PACKAGE/$TCEXTTOOLS_EXTENSIONS"
 
-     TCEXTTOOLS_INSTALL_ROOT="$TCEXTTOOLS_BIN/root"
      TCEXTTOOLS_BIN_TEMP="$TCEXTTOOLS_BIN/temp"
      TCEXTTOOLS_SRC_TEMP="$TCEXTTOOLS_SRC/temp"
 
@@ -75,9 +92,6 @@ if [ -e "$TCEXTTOOLS_COMMON" ]; then
      TCEXTTOOLS_BUILD_LOG="$TCEXTTOOLS_LOG/build.txt"
      TCEXTTOOLS_ERROR_LOG="$TCEXTTOOLS_LOG/error.txt"
      TCEXTTOOLS_ERROR_LOG_2="$TCEXTTOOLS_LOG/error2.txt"
-
-     INSTALL_ROOT="$TCEXTTOOLS_INSTALL_ROOT"
-     TOP_SRC_DIR="$TCEXTTOOLS_BIN_TEMP/$TOP_SRC"
 
      if [ -n "$BUILD_DEPENDS" ]; then
           BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS $BUILD_DEPENDS"
@@ -92,9 +106,52 @@ if [ -e "$TCEXTTOOLS_COMMON" ]; then
      [ -d "$TCEXTTOOLS_SRC_TEMP" ] || install -m 755 -d "$TCEXTTOOLS_SRC_TEMP"
      [ -d "$TCEXTTOOLS_LOG" ] || install -m 755 -d "$TCEXTTOOLS_LOG"
 
+     # determine the type of package source from the supported generic types
+     if [ ! "${SOURCE%.bz2}" = "$SOURCE" ]; then
+            SOURCE_TYPE="bz2"
+            CONVERTED_SOURCE="${SOURCE%.bz2}.xz"
+     elif [ ! "${SOURCE%.gz}" = "$SOURCE" ]; then
+            SOURCE_TYPE="gz"
+            CONVERTED_SOURCE="${SOURCE%.gz}.xz"
+     elif [ ! "${SOURCE%.tgz}" = "$SOURCE" ]; then
+            CONVERTED_SOURCE="${SOURCE%.tgz}.tar.xz"
+            SOURCE_TYPE="tgz"
+     elif [ ! "${SOURCE%.zip}" = "$SOURCE" ]; then
+            SOURCE_TYPE="zip"
+            CONVERTED_SOURCE="${SOURCE%.zip}.tar.xz"
+     elif [ ! "${SOURCE%.xz}" = "$SOURCE" ]; then
+            SOURCE_TYPE="xz"
+            CONVERTED_SOURCE="$SOURCE"
+     else
+            # the user have to define custom build_unpack, and build_convert functions in the build file for custom package sources
+            [ -z "$SOURCE_TYPE" ] && SOURCE_TYPE="custom"
+            [ -z "$CONVERTED_SOURCE" ] && CONVERTED_SOURCE="${SOURCE%.*}.tar.xz"
+     fi
+
+     TCEXTTOOLS_SOURCE="$TCEXTTOOLS_SRC/$SOURCE"
+     TCEXTTOOLS_TOP_SRC="$TCEXTTOOLS_BIN_TEMP/$TOP_SRC"
+     TCEXTTOOLS_CONVERTED_SOURCE="$TCEXTTOOLS_SRC/$CONVERTED_SOURCE"
+     TCEXTTOOLS_INSTALL_ROOT="$TCEXTTOOLS_BIN/root"
+
+     PACKAGE_SOURCE="$TCEXTTOOLS_SOURCE"
+     PACKAGE_TOP_SRC="$TCEXTTOOLS_TOP_SRC"
+     PACKAGE_CONVERTED_SOURCE="$TCEXTTOOLS_CONVERTED_SOURCE"
+     PACKAGE_INSTALL_ROOT="$TCEXTTOOLS_INSTALL_ROOT"
+
+     INSTALL_ROOT="$PACKAGE_INSTALL_ROOT"
+
+     #EXTENSIONS=$(echo $EXTENSIONS | sed -e "s/KERNEL/$(uname -r)/g")
+
 elif [ "$THIS" != "boostit" ]; then
-     print_it error "tc-ext-tools common file not found: $TCEXTTOOLS_COMMON"
+     print_it error "the package $PACKAGE common file not found!"
      print_it warning "You must boost it first!"
+     exit 1
+fi
+
+if [ -e "$PACKAGE_BUILD" ]; then
+     . "$PACKAGE_BUILD"
+elif [ "$THIS" != "boostit" ]; then
+     print_it error "the package $PACKAGE build file not found!"
      exit 1
 fi
 
diff --git a/trunk/tools/buildit b/trunk/tools/buildit
--- a/trunk/tools/buildit
+++ b/trunk/tools/buildit
@@ -36,44 +36,11 @@ print_usage(){
 
 clean_it() {
 
-  cd "$PACKAGE_ROOT"
-
   print_it "Cleaning the package $PACKAGE ... \c"
-
-  RETURN_CODE=0
-
-  if [ -d "$TCEXTTOOLS_BIN" ]; then
-       sudo rm -rf "$TCEXTTOOLS_BIN" > /dev/null 2>&1 || RETURN_CODE=1
-  fi
-
-  mkdir -p "$TCEXTTOOLS_BIN" > /dev/null 2>&1 || RETURN_CODE=1
-
-  if [ -d "$TCEXTTOOLS_PKG" ]; then
-       sudo rm -rf "$TCEXTTOOLS_PKG" > /dev/null 2>&1 || RETURN_CODE=1
-  fi
-
-  mkdir -p "$TCEXTTOOLS_PKG" > /dev/null 2>&1 || RETURN_CODE=1
-
-  if [ -d "$TCEXTTOOLS_BIN_TEMP" ]; then
-       sudo rm -rf "$TCEXTTOOLS_BIN_TEMP" > /dev/null 2>&1 || RETURN_CODE=1
-  fi
-
-  mkdir -p "$TCEXTTOOLS_BIN_TEMP" > /dev/null 2>&1 || RETURN_CODE=1
-
-  if [ -d "$TCEXTTOOLS_SRC_TEMP" ]; then
-       sudo rm -rf "$TCEXTTOOLS_SRC_TEMP" > /dev/null 2>&1 || RETURN_CODE=1
-  fi
-
-  mkdir -p "$TCEXTTOOLS_SRC_TEMP" > /dev/null 2>&1 || RETURN_CODE=1
-
-  if [ -d "$TCEXTTOOLS_LOG" ]; then
-       sudo rm -rf "$TCEXTTOOLS_LOG" > /dev/null 2>&1 || RETURN_CODE=1
-  fi
-
-  mkdir -p "$TCEXTTOOLS_LOG" > /dev/null 2>&1 || RETURN_CODE=1
-
-  if [ "$RETURN_CODE" -gt 0 ]; then
+  cleanit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
        print_it error "failed!"
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
@@ -81,9 +48,7 @@ clean_it() {
 
 download_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ -f "$TCEXTTOOLS_SRC/$SOURCE" ]; then
+  if [ -f "$PACKAGE_SOURCE" ]; then
        print_it warning "The package $PACKAGE source is already downloaded."
        exit 0
   fi
@@ -92,7 +57,7 @@ download_it() {
   downloadit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show download"
        exit 1
   fi
   print_it hilight "successful!"
@@ -100,18 +65,21 @@ download_it() {
 
 convert_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -e "$TCEXTTOOLS_SRC/$SOURCE" ]; then
+  if [ ! -e "$PACKAGE_SOURCE" ]; then
        print_it error "You must download it first!"
        exit 1
+  fi
+
+  if [ -e "$PACKAGE_CONVERTED_SOURCE" ]; then
+       print_it warning "The package $PACKAGE source is already converted."
+       exit 0
   fi
 
   print_it "Converting the package $PACKAGE source to xz compressed tarball ... \c"
   convertit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
@@ -119,9 +87,7 @@ convert_it() {
 
 unpack_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -e "$TCEXTTOOLS_SRC/$SOURCE" ]; then
+  if [ ! -e "$PACKAGE_SOURCE" ]; then
         print_it error "You must download it first!"
         exit 1
   fi
@@ -130,7 +96,7 @@ unpack_it() {
   unpackit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
@@ -138,13 +104,11 @@ unpack_it() {
 
 load_it() {
 
-  cd "$PACKAGE_ROOT"
-
   print_it "Loading the package $PACKAGE build dependencies ... \c"
   loadit "$BUILD_DEPENDS" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight  "successful!"
@@ -152,49 +116,34 @@ load_it() {
 
 patch_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -d "$TCEXTTOOLS_BIN_TEMP/$TOP_SRC" ]; then
+  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
        print_it error "You must unpack it first!"
        exit 1
   fi
 
-  if [ -d "$PACKAGE_PATCHES" ]; then
-       print_it "Patching the package $PACKAGE source ... \c"
-       patchit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-       if [ "$?" -gt 0 ]; then
-            print_it error "failed!"
-            print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
-            exit 1
-       fi
-       print_it hilight "successful!"
-  else
-       print_it warning "There is no patch for the package $PACKAGE."
+  print_it "Patching the package $PACKAGE source ... \c"
+  patchit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
+       print_it error "failed!"
+       print_it warning "For details: buildit show error"
+       exit 1
   fi
+  print_it hilight "successful!"
 }
 
 configure_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ -e "$TCEXTTOOLS_BUILD" ]; then
-       . "$TCEXTTOOLS_BUILD"
-  else
-       print_it error "tc-ext-tools build functions file not found: $TCEXTTOOLS_BUILD"
-       exit 1
-  fi
-
-  if [ ! -d "$TCEXTTOOLS_BIN_TEMP/$TOP_SRC" ]; then
+  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
        print_it error "You must unpack it first!"
        exit 1
   fi
 
   print_it "Configuring the package $PACKAGE ... \c"
-  cd "$TCEXTTOOLS_BIN_TEMP/$TOP_SRC"
+  cd "$PACKAGE_TOP_SRC"
   build_configure > "$TCEXTTOOLS_CONFIGURE_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See $TCEXTTOOLS_CONFIGURE_LOG for details."
+       print_it warning "For details: buildit show configure"
        exit 1
   fi
   print_it hilight "successful!"
@@ -202,26 +151,17 @@ configure_it() {
 
 compile_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ -e "$TCEXTTOOLS_BUILD" ]; then
-       . "$TCEXTTOOLS_BUILD"
-  else
-       print_it error "tc-ext-tools build functions file not found: $TCEXTTOOLS_BUILD"
-       exit 1
-  fi
-
-  if [ ! -d "$TCEXTTOOLS_BIN_TEMP/$TOP_SRC" ]; then
+  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
        print_it error "You must configure it first!"
        exit 1
   fi
 
   print_it "Compiling the package $PACKAGE ... \c"
-  cd "$TCEXTTOOLS_BIN_TEMP/$TOP_SRC"
+  cd "$PACKAGE_TOP_SRC"
   build_compile > "$TCEXTTOOLS_COMPILE_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See $TCEXTTOOLS_COMPILE_LOG for details."
+       print_it warning "For details: buildit show compile"
        exit 1
   fi
   print_it hilight "successful!"
@@ -229,9 +169,7 @@ compile_it() {
 
 install_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -d "$TOP_SRC_DIR" ]; then
+  if [ ! -d "$PACKAGE_TOP_SRC" ]; then
        print_it error "You must compile it first!"
        exit 1
   fi
@@ -240,27 +178,7 @@ install_it() {
   sudo installit > "$TCEXTTOOLS_INSTALL_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See $TCEXTTOOLS_INSTALL_LOG for details."
-       exit 1
-  fi
-  print_it hilight "successful!"
-
-}
-
-modify_it() {
-
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
-       print_it error "You must install it first!"
-       exit 1
-  fi
-
-  print_it "Modifying the package $PACKAGE ... \c"
-  modifyit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-  if [ "$?" -gt 0 ]; then
-       print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show install"
        exit 1
   fi
   print_it hilight "successful!"
@@ -269,18 +187,16 @@ modify_it() {
 
 strip_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
+  if [ ! -d "$PACKAGE_INSTALL_ROOT" ]; then
        print_it error "You must install it first!"
        exit 1
   fi
 
   print_it "Stripping the package $PACKAGE ... \c"
-  stripit "$TCEXTTOOLS_INSTALL_ROOT" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  stripit "$PACKAGE_INSTALL_ROOT" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
@@ -288,115 +204,70 @@ strip_it() {
 
 split_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
+  if [ ! -d "$PACKAGE_INSTALL_ROOT" ]; then
        print_it error "You must install it first!"
        exit 1
   fi
 
-  for EXTENSION in $EXTENSIONS
-  do
-      print_it "Splitting the extension $EXTENSION out of the package $PACKAGE ... \c"
-      splitit "$EXTENSION" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-      if [ "$?" -gt 0 ]; then
-           print_it error "failed!"
-           print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
-           exit 1
-      fi
-      print_it hilight "successful!"
-  done
+  print_it "Splitting the package $PACKAGE extensions ... \c"
+  splitit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
+       print_it error "failed!"
+       print_it warning "For details: buildit show error"
+       exit 1
+  fi
+  print_it hilight "successful!"
 }
 
 create_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  [ -d "$TCEXTTOOLS_EXTENSIONS" ] && sudo rm -rf "$TCEXTTOOLS_EXTENSIONS" > /dev/null 2>&1
-  mkdir -p "$TCEXTTOOLS_EXTENSIONS" > /dev/null 2>&1
-
-  for EXTENSION in $EXTENSIONS
-  do
-      if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION" ]; then
-           print_it error "You must split it first!"
-           exit 1
-      fi
-
-      print_it "Creating the extension $EXTENSION ... \c"
-      createit "$EXTENSION" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-      if [ "$?" -gt 0 ]; then
-           print_it error "failed!"
-           print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
-           exit 1
-      fi
-      print_it hilight "successful!"
-  done
+  print_it "Creating the package $PACKAGE extensions ... \c"
+  createit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
+       print_it error "failed!"
+       print_it warning "For details: buildit show error"
+       exit 1
+  fi
+  print_it hilight "successful!"
 }
 
 generate_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  for EXTENSION in $EXTENSIONS
-  do
-      if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
-           print_it error "You must create it first!"
-           exit 1
-      fi
-
-      print_it "Generating the extension $EXTENSION info ... \c"
-      generateit "$EXTENSION" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-      if [ "$?" -gt 0 ]; then
-           print_it error "failed!"
-           print_it warning "See $TCEXTTOOLS_ERROR_LOG for details."
-           exit 1
-      fi
-      print_it hilight "successful!"
-  done
+  print_it "Generating the package $PACKAGE extensions info files ... \c"
+  generateit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
+       print_it error "failed!"
+       print_it warning "For details: buildit show error"
+       exit 1
+  fi
+  print_it hilight "successful!"
 }
 
 check_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  for EXTENSION in $EXTENSIONS
-  do
-      if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
-           print_it error "You must create it first!"
-           exit 1
-      fi
-
-      print_it "Checking the extension $EXTENSION ... \c"
-      checkit "$EXTENSION" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
-      if [ "$?" -gt 0 ]; then
-           print_it error "failed!"
-           print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
-           exit 1
-      fi
-      print_it hilight "successful!"
-  done
+  print_it "Checking the package $PACKAGE extensions ... \c"
+  checkit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
+  if [ "$?" -gt 0 ]; then
+       print_it error "failed!"
+       print_it warning "For details: buildit show error"
+       exit 1
+  fi
+  print_it hilight "successful!"
 }
 
 package_it() {
-
-  cd "$PACKAGE_ROOT"
-
-  [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG" > /dev/null 2>&1
-  mkdir -p "$TCEXTTOOLS_PKG" > /dev/null 2>&1
 
   print_it "Packaging the package $PACKAGE ... \c"
   packageit > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
 }
 
 compress_it() {
-
-  cd "$PACKAGE_ROOT"
 
   if [ ! -d "$TCEXTTOOLS_PKG" ]; then
        print_it error "You must package it first!"
@@ -407,7 +278,7 @@ compress_it() {
   compressit bz2 "$TCEXTTOOLS_PKG" > "$TCEXTTOOLS_ERROR_LOG" 2>&1
   if [ "$?" -gt 0 ]; then
        print_it error "failed!"
-       print_it warning "See error logs in $TCEXTTOOLS_LOG for details."
+       print_it warning "For details: buildit show error"
        exit 1
   fi
   print_it hilight "successful!"
@@ -415,33 +286,20 @@ compress_it() {
 
 encrypt_it() {
 
-  cd "$PACKAGE_ROOT"
-
   if [ ! -e "${PACKAGE}.tar.bz2" ]; then
        print_it error "You must compress it first!"
        exit 1
   fi
 
-  [ -e "${PACKAGE}.tar.bz2.bfe" ] && sudo rm -f "${PACKAGE}.tar.bz2.bfe"
   encryptit "${PACKAGE}.tar.bz2" || exit 1
 }
 
 build_it() {
 
-  cd "$PACKAGE_ROOT"
-
-  if [ -e "$TCEXTTOOLS_BUILD" ]; then
-       . "$TCEXTTOOLS_BUILD"
-  else
-       print_it error "tc-ext-tools build functions file not found: $TCEXTTOOLS_BUILD"
-       exit 1
-  fi
-
   build_rules || exit 1
 }
 
 show_it() {
-  cd "$PACKAGE_ROOT"
 
   case "$1" in
        download) 
diff --git a/trunk/tools/checkit b/trunk/tools/checkit
--- a/trunk/tools/checkit
+++ b/trunk/tools/checkit
@@ -30,25 +30,7 @@ else
      exit 1
 fi
 
-EXTENSION="$1"
-
-print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
-}
-
-if [ -z "$EXTENSION" ]; then
-     print_usage
-     exit 1
-fi
-
-if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
-     print_it error "You must create it first!"
-     exit 1
-fi
-
-TMPDIR=$(busybox mktemp -d)
-
-this_main() {
+this_check() {
 
   sudo busybox mount -o loop "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" "$TMPDIR" || return 1
 
@@ -99,15 +81,39 @@ this_main() {
 
   sudo busybox umount "$TMPDIR"
   sudo rm -rf "$TMPDIR"
+
   return 0
 }
 
-print_it "Checking the extension $EXTENSION ... \c"
+this_main() {
+
+  for EXTENSION in $EXTENSIONS
+  do
+      if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
+             print_it error "You must create it first!"
+             exit 1
+      fi
+
+      TMPDIR=$(busybox mktemp -d)
+
+      this_check
+      if [ "$?" -gt 0 ]; then
+           print_it error "Checking the extension $EXTENSION failed!"
+           sudo busybox umount "$TMPDIR"
+           sudo rm -rf "$TMPDIR"
+           return 1
+      else
+           print_it "Checking the extension $EXTENSION successful!"
+      fi
+  done
+
+  return 0
+}
+
+print_it "Checking the package $PACKAGE extensions ... \c"
 this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
-     sudo busybox umount "$TMPDIR" > /dev/null 2>&1
-     sudo rm -rf "$TMPDIR" > /dev/null 2>&1
      exit 1
 fi
 
diff --git a/trunk/tools/generateit b/trunk/tools/generateit
--- a/trunk/tools/generateit
+++ b/trunk/tools/generateit
@@ -30,26 +30,8 @@ else
      exit 1
 fi
 
-EXTENSION="$1"
+this_generate() {
 
-print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
-}
-
-if [ -z "$EXTENSION" ]; then
-      print_usage
-      exit 1
-fi
-
-if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
-     print_it error "You must create it first!"
-     exit 1
-fi
-
-this_main() {
-
-  CURRENT="$DATE $CURRENT"
-  SIZE=$(du -h "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" | cut -f1)
   [ ! "${EXTENSION%-bin}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, utilities."
   [ ! "${EXTENSION%-lib}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, shared libraries."
   [ ! "${EXTENSION%-dev}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, development files."
@@ -61,6 +43,9 @@ this_main() {
   if [ -e "$PACKAGE_EXTENSIONS/$EXTENSION/info" ]; then
       . "$PACKAGE_EXTENSIONS/$EXTENSION/info"
   fi
+
+  CURRENT="$DATE $CURRENT"
+  SIZE=$(du -h "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" | cut -f1)
 
   cat > "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz.info" << _EOF
 Title:		${EXTENSION}.tcz
@@ -84,7 +69,30 @@ _EOF
   return 0
 }
 
-print_it "Generating the extension $EXTENSION info ... \c"
+this_main() {
+
+  for EXTENSION in $EXTENSIONS
+  do
+      . "$PACKAGE_COMMON"
+
+      if [ ! -e "$TCEXTTOOLS_EXTENSIONS/$EXTENSION/${EXTENSION}.tcz" ]; then
+             print_it error "You must create it first!"
+             exit 1
+      fi
+
+      this_generate
+      if [ "$?" -gt 0 ]; then
+           print_it error "Generating the extension $EXTENSION info failed!"
+           return 1
+      else
+           print_it "Generating the extension $EXTENSION info successful!"
+      fi
+  done  
+
+  return 0
+}
+
+print_it "Generating the package $PACKAGE extensions info files ... \c"
 this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
diff --git a/trunk/tools/splitit b/trunk/tools/splitit
--- a/trunk/tools/splitit
+++ b/trunk/tools/splitit
@@ -30,25 +30,12 @@ else
      exit 1
 fi
 
-EXTENSION="$1"
-
-print_usage() {
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
-}
-
 if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
      print_it error "You must install it first!"
      exit 1
 fi
 
-if [ ! -f "$PACKAGE_EXTENSIONS/$EXTENSION/install" ]; then
-      print_usage
-      exit 1
-fi
-
-TMP_DIR="$(busybox mktemp -d)"
-
-this_main() {
+this_split() {
 
   CONTENTS="$(cat $PACKAGE_EXTENSIONS/$EXTENSION/install)"
   [ -z "$CONTENTS" ] && return 1
@@ -92,16 +79,35 @@ this_main() {
   fi
 
   sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION" || return 1
+
   sudo rm -rf "$TMP_DIR"
 
   return 0
 }
 
-print_it "Splitting the extension $EXTENSION out of the package $PACKAGE ... \c"
+this_main() {
+
+  for EXTENSION in $EXTENSIONS
+  do
+      TMP_DIR=$(busybox mktemp -d)
+
+      this_split
+      if [ "$?" -gt 0 ]; then
+           print_it error "Splitting the extension $EXTENSION failed!"
+           sudo rm -rf "$TMP_DIR"
+           return 1
+      else
+           print_it "Splitting the extension $EXTENSION successful!"
+      fi
+  done
+
+  return 0
+}
+
+print_it "Splitting the package $PACKAGE extensions ... \c"
 this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
-     [ -d "$TMP_DIR" ] && sudo rm -rf "$TMP_DIR" > /dev/null 2>&1
      exit 1
 fi
 print_it hilight "successful!"
