- Added installit to install tc-ext-tools - Deprecated and removed Makefile - User defined variables moved to ~/.tc-ext-tools/config - Added config.sample for initial user configuration - Updated INSTALL, README files - Fixed a bug in boostit

diff --git a/trunk/default/functions b/trunk/default/functions
--- a/trunk/default/functions
+++ b/trunk/default/functions
@@ -12,7 +12,14 @@ fi
 if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/config" ]; then
      . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/config
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools configuration file not found!${NORMAL}"
+     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools default configuration file not found!${NORMAL}"
+     exit 1
+fi
+
+if [ -f "$HOME"/.tc-ext-tools/config ]; then
+     . "$HOME"/.tc-ext-tools/config
+else
+     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools user configuration file not found!${NORMAL}"
      exit 1
 fi
 
@@ -35,16 +42,6 @@ print_it() {
                 ;;
   esac
 }
-
-TCEXTTOOLS_USER=$(cat /etc/sysconfig/tcuser)
-
-if [ ! -d "${TCEXTTOOLS_STORAGE}" ]; then
-     sudo install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_STORAGE} > /dev/null 2>&1
-     if [ $? -gt 0 ]; then
-          print_it error "Creating tc-ext-tools storage directory failed : ${TCEXTTOOLS_STORAGE}"
-          exit 1
-     fi
-fi
 
 PACKAGE_ROOT=${PWD}
 PACKAGE_COMMON="${PACKAGE_ROOT}/${TCEXTTOOLS_COMMON}"
@@ -74,12 +71,12 @@ if [ -e "${TCEXTTOOLS_COMMON}" ]; then
      TCEXTTOOLS_ERROR_LOG="${TCEXTTOOLS_LOG}/error.txt"
      TCEXTTOOLS_ERROR_LOG_2="${TCEXTTOOLS_LOG}/error2.txt"
 
-     [ -d "${TCEXTTOOLS_BIN}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_BIN}
-     [ -d "${TCEXTTOOLS_SRC}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_SRC}
-     [ -d "${TCEXTTOOLS_PKG}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_PKG}
-     [ -d "${TCEXTTOOLS_BIN_TEMP}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_BIN_TEMP}
-     [ -d "${TCEXTTOOLS_SRC_TEMP}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_SRC_TEMP}
-     [ -d "${TCEXTTOOLS_LOG}" ] || install -m 755 -d -o ${USER} -g staff ${TCEXTTOOLS_LOG}
+     [ -d "${TCEXTTOOLS_BIN}" ] || install -m 755 -d ${TCEXTTOOLS_BIN}
+     [ -d "${TCEXTTOOLS_SRC}" ] || install -m 755 -d ${TCEXTTOOLS_SRC}
+     [ -d "${TCEXTTOOLS_PKG}" ] || install -m 755 -d ${TCEXTTOOLS_PKG}
+     [ -d "${TCEXTTOOLS_BIN_TEMP}" ] || install -m 755 -d ${TCEXTTOOLS_BIN_TEMP}
+     [ -d "${TCEXTTOOLS_SRC_TEMP}" ] || install -m 755 -d ${TCEXTTOOLS_SRC_TEMP}
+     [ -d "${TCEXTTOOLS_LOG}" ] || install -m 755 -d ${TCEXTTOOLS_LOG}
 
 elif [ ! "${THIS}" = "boostit" ]; then
      print_it error "tc-ext-tools common file not found: ${TCEXTTOOLS_COMMON}"
