- Updated tc-ext-tools: applied changes from tc-ext-tools-bash and more

diff --git a/default/functions b/default/functions
--- a/default/functions
+++ b/default/functions
@@ -76,63 +76,52 @@ print_it() {
 
 }
 
-# sets package build dependencies
-set_depends() {
-
-   if [ -n "$BUILD_DEPENDS" ]; then
-        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS $BUILD_DEPENDS"
-   else
-        BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS"
-   fi
-
-}
-
 # sets the package source variables
 set_source() {
 
-     SOURCE_URL_TYPE="${SOURCE%%::*}"
-     if [ "$SOURCE_URL_TYPE" = "$SOURCE" ]; then
-          SOURCE_URL_TYPE=""
+     PACKAGE_SOURCE_URL_TYPE="${SOURCE%%::*}"
+     if [ "$PACKAGE_SOURCE_URL_TYPE" = "$SOURCE" ]; then
+          PACKAGE_SOURCE_URL_TYPE=""
      else
           SOURCE=${SOURCE#*::}
-          SOURCE_NAME=${PACKAGE}-${VERSION}.tar.xz
+          PACKAGE_SOURCE_NAME=${PACKAGE}-${VERSION}.tar.xz
           SOURCE_TOPDIR=${PACKAGE}-${VERSION}     
      fi
 
-     if [ -z "$SOURCE_NAME" ]; then
-          SOURCE_NAME=${SOURCE##*/}
+     if [ -z "$PACKAGE_SOURCE_NAME" ]; then
+          PACKAGE_SOURCE_NAME=${SOURCE##*/}
      fi
 
-     if [ ! "${SOURCE_NAME%.bz2}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="bz2"
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.bz2}.xz"
-     elif [ ! "${SOURCE_NAME%.gz}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="gz"
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.gz}.xz"
-     elif [ ! "${SOURCE_NAME%.tgz}" = "$SOURCE_NAME" ]; then
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.tgz}.tar.xz"
-            SOURCE_TYPE="tgz"
-     elif [ ! "${SOURCE_NAME%.tbz2}" = "$SOURCE_NAME" ]; then
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.tbz2}.tar.xz"
-            SOURCE_TYPE="tbz2"
-     elif [ ! "${SOURCE_NAME%.zip}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="zip"
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.zip}.tar.xz"
-     elif [ ! "${SOURCE_NAME%.xz}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="xz"
-            SOURCE_NAME_CONVERTED="$SOURCE_NAME"
-     elif [ ! "${SOURCE_NAME%.txz}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="txz"
-            SOURCE_NAME_CONVERTED="$SOURCE_NAME"
-     elif [ ! "${SOURCE_NAME%.tar}" = "$SOURCE_NAME" ]; then
-            SOURCE_TYPE="tar"
-            SOURCE_NAME_CONVERTED="${SOURCE_NAME%.tar}.tar.xz"
+     if [ ! "${PACKAGE_SOURCE_NAME%.bz2}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="bz2"
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.bz2}.xz"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.gz}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="gz"
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.gz}.xz"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.tgz}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.tgz}.tar.xz"
+            PACKAGE_SOURCE_TYPE="tgz"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.tbz2}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.tbz2}.tar.xz"
+            PACKAGE_SOURCE_TYPE="tbz2"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.zip}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="zip"
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.zip}.tar.xz"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.xz}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="xz"
+            PACKAGE_SOURCE_NAME_CONVERTED="$PACKAGE_SOURCE_NAME"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.txz}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="txz"
+            PACKAGE_SOURCE_NAME_CONVERTED="$PACKAGE_SOURCE_NAME"
+     elif [ ! "${PACKAGE_SOURCE_NAME%.tar}" = "$PACKAGE_SOURCE_NAME" ]; then
+            PACKAGE_SOURCE_TYPE="tar"
+            PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.tar}.tar.xz"
      else
             if [ -z "$SOURCE" ]; then
-                 SOURCE_TYPE=none
+                 PACKAGE_SOURCE_TYPE=none
             else
-                 SOURCE_TYPE="custom"
-                 [ -z "$SOURCE_NAME_CONVERTED" ] && SOURCE_NAME_CONVERTED="${SOURCE_NAME%.*}.tar.xz"
+                 PACKAGE_SOURCE_TYPE="custom"
+                 [ -z "$PACKAGE_SOURCE_NAME_CONVERTED" ] && PACKAGE_SOURCE_NAME_CONVERTED="${PACKAGE_SOURCE_NAME%.*}.tar.xz"
             fi
      fi
 
@@ -141,85 +130,104 @@ set_source() {
           [ -z "$SOURCE_TOPDIR" ] && SOURCE_TOPDIR=${PACKAGE}-${VERSION}
      fi
 
-}
- 
-# sets the package extensions
-set_extensions() {
+     if [ -n "$SOURCE_TOPDIR" ]; then
+          PACKAGE_SOURCE_TOPDIR="$PACKAGE_SRC_TEMP/$SOURCE_TOPDIR"
+     fi
 
-     unset EXTENSIONS
-
-     if [ -d "$PACKAGE_EXTENSIONS" ]; then
-          for i in $(find "$PACKAGE_EXTENSIONS" -type f -name install)
-          do
-              EXTENSION=$(basename ${i%/install})
-              if [ -z "$EXTENSIONS" ]; then
-                   EXTENSIONS="$EXTENSION"
-              else
-                   EXTENSIONS="$EXTENSIONS $EXTENSION"
-              fi
-          done
+     if [ "$PACKAGE_SOURCE_TYPE" != "none" ]; then
+          PACKAGE_SOURCE="$_PACKAGE_SRC/$PACKAGE_SOURCE_NAME"
+          PACKAGE_SOURCE_CONVERTED="$_PACKAGE_SRC/$PACKAGE_SOURCE_NAME_CONVERTED"
      fi
 
 }
+ 
+# sets the package extensions variables
+set_extensions() {
 
-# sets the package extension
+   if [ -z "$EXTENSIONS" ]; then
+        if [ -d "$PACKAGE_EXTENSIONS" ]; then
+             for i in $(find "$PACKAGE_EXTENSIONS" -type f -name install)
+             do
+                 EXTENSIONS="$EXTENSIONS $(basename ${i%/install})"
+             done
+        fi
+   fi
+
+   NUM=0
+   for i in $EXTENSIONS
+   do
+      NUM=`expr $NUM+1`
+   done
+
+   if [ "$NUM" == 0 ]; then
+        echo "Error! There is no extension available."
+        exit 1
+   elif [ "$NUM" == 1 ]; then
+        SINGLE_EXTENSION_PACKAGE=1
+   else
+        SINGLE_EXTENSION_PACKAGE=0
+   fi
+
+}
+
+# sets the package extension variables
 set_extension() {
 
-      if [ -z "$EXTENSION" ]; then
-           print_it error "EXTENSION is not set!"
-           return 1
-      fi
+   if [ -z "$EXTENSION" ]; then
+        echo "The variable EXTENSION must be set, skipping."
+        return 0
+   fi
 
-      PACKAGE_EXTENSION_COMMON="$PACKAGE_EXTENSIONS/$EXTENSION/common"
-      PACKAGE_EXTENSION_INSTALL="$PACKAGE_EXTENSIONS/$EXTENSION/install"
-      PACKAGE_EXTENSION_DEP="$PACKAGE_EXTENSIONS/$EXTENSION/dep"
-      PACKAGE_EXTENSION_TCEINSTALLED="$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed"
+   PACKAGE_EXTENSION_COMMON="$PACKAGE_EXTENSIONS/$EXTENSION/common"
+   PACKAGE_EXTENSION_INSTALL="$PACKAGE_EXTENSIONS/$EXTENSION/install"
+   PACKAGE_EXTENSION_DEP="$PACKAGE_EXTENSIONS/$EXTENSION/dep"
+   PACKAGE_EXTENSION_TCEINSTALLED="$PACKAGE_EXTENSIONS/$EXTENSION/tce.installed"
 
-      TCEXTTOOLS_EXTENSION_COMMON="$PACKAGE_EXTENSION_COMMON"
-      TCEXTTOOLS_EXTENSION_INSTALL="$PACKAGE_EXTENSION_INSTALL"
-      TCEXTTOOLS_EXTENSION_TCEINSTALLED="$PACKAGE_EXTENSION_TCEINSTALLED"
+   unset NAME ICON DESKTOP
 
-      unset NAME ICON DESKTOP
+   . "$PACKAGE_COMMON"
 
-       . "$PACKAGE_COMMON"
+   if [ -f "$PACKAGE_EXTENSION_COMMON" ]; then
+        . "$PACKAGE_EXTENSION_COMMON"
+   fi
 
-      if [ -f "$PACKAGE_EXTENSION_COMMON" ]; then
-           . "$PACKAGE_EXTENSION_COMMON"
-      fi
+   if [ -z "$NAME" ]; then
+        PACKAGE_EXTENSION_NAME="$EXTENSION"
+   else
+        PACKAGE_EXTENSION_NAME="$NAME"
+   fi
 
-      if [ -z "$NAME" ]; then
-           EXTENSION_NAME="$EXTENSION"
-      else
-           EXTENSION_NAME="$NAME"
-      fi
+   if [ -n "$(echo $PACKAGE_EXTENSION_NAME | grep KERNEL)" ]; then
+        PACKAGE_EXTENSION_NAME=$(echo $PACKAGE_EXTENSION_NAME | sed "s/KERNEL/${KERNEL}/")
+   fi
 
-      if [ -n "$(echo $EXTENSION_NAME | grep KERNEL)" ]; then
-           EXTENSION_NAME=$(echo $EXTENSION_NAME | sed "s/KERNEL/${KERNEL}/")
-      fi
+   PACKAGE_EXTENSION_BIN="$PACKAGE_BIN/$PACKAGE_EXTENSION_NAME"
+   PACKAGE_EXTENSION_PKG="$PACKAGE_PKG/$PACKAGE_EXTENSION_NAME"
+   PACKAGE_EXTENSION_BIN_TEMP="$PACKAGE_BIN_TEMP/$PACKAGE_EXTENSION_NAME"
+   PACKAGE_EXTENSION_PKG_TEMP="$PACKAGE_PKG_TEMP/$PACKAGE/$PACKAGE_EXTENSION_NAME"
+   PACKAGE_EXTENSION_TCZ="$PACKAGE_EXTENSION_PKG/${PACKAGE_EXTENSION_NAME}.tcz"
+   PACKAGE_EXTENSION_INFO="$PACKAGE_EXTENSION_PKG/${PACKAGE_EXTENSION_NAME}.tcz.info"
+   _PACKAGE_EXTENSION_DEP="$PACKAGE_EXTENSION_PKG/${PACKAGE_EXTENSION_NAME}.tcz.dep"
+   PACKAGE_EXTENSION_LIST="$PACKAGE_EXTENSION_PKG/${PACKAGE_EXTENSION_NAME}.tcz.list"
+   PACKAGE_EXTENSION_MD5SUM="$PACKAGE_EXTENSION_PKG/${PACKAGE_EXTENSION_NAME}.tcz.md5.txt"
 
-      TCEXTTOOLS_EXTENSION_BINDIR="$TCEXTTOOLS_BIN/$EXTENSION_NAME"
-      TCEXTTOOLS_EXTENSION_PKGDIR="$TCEXTTOOLS_PKG/$EXTENSION_NAME"
-      TCEXTTOOLS_EXTENSION_TCZ="$TCEXTTOOLS_EXTENSION_PKGDIR/${EXTENSION_NAME}.tcz"
-      TCEXTTOOLS_EXTENSION_INFO="$TCEXTTOOLS_EXTENSION_PKGDIR/${EXTENSION_NAME}.tcz.info"
-      TCEXTTOOLS_EXTENSION_DEP="$TCEXTTOOLS_EXTENSION_PKGDIR/${EXTENSION_NAME}.tcz.dep"
-      TCEXTTOOLS_EXTENSION_LIST="$TCEXTTOOLS_EXTENSION_PKGDIR/${EXTENSION_NAME}.tcz.list"
-      TCEXTTOOLS_EXTENSION_MD5SUM="$TCEXTTOOLS_EXTENSION_PKGDIR/${EXTENSION_NAME}.tcz.md5.txt"
-
-      PACKAGE_EXTENSION_BINDIR="$TCEXTTOOLS_EXTENSION_BINDIR"
-      PACKAGE_EXTENSION_PKGDIR="$TCEXTTOOLS_EXTENSION_PKGDIR"
-      PACKAGE_EXTENSION_TCZ="$TCEXTTOOLS_EXTENSION_TCZ"
-      PACKAGE_EXTENSION_INFO="$TCEXTTOOLS_EXTENSION_INFO"
-      PACKAGE_EXTENSION_LIST="$TCEXTTOOLS_EXTENSION_LIST"
-      PACKAGE_EXTENSION_MD5SUM="$TCEXTTOOLS_EXTENSION_MD5SUM"
+   if [ -n "$ICON" ]; then
+        PACKAGE_EXTENSION_ICON="$ICON"
+        if [ -n "$DESKTOP" ]; then
+             PACKAGE_EXTENSION_DESKTOP="$PACKAGE_BIN/$DESKTOP"
+        else
+             PACKAGE_EXTENSION_DESKTOP="$PACKAGE_BIN/usr/local/share/applications/${PACKAGE_EXTENSION_NAME}.desktop"
+        fi
+   fi
 
 }
 
 # sets the date, time, and seconds
 set_date() {
 
-    DATE=$(date +%Y/%m/%d)
-    TIME=$(date +%H:%M:%S)
-    SECONDS=$(date +%s)
+   DATE=$(date +%Y/%m/%d)
+   TIME=$(date +%H:%M:%S)
+   SECONDS=$(date +%s)
 
 }
 
@@ -239,74 +247,55 @@ PACKAGE_EXTENSIONS="$PACKAGE_ROOT/extensions"
 PACKAGE_FILES_LIST="$PACKAGE_EXTENSIONS/list"
 PACKAGE_SRC="$PACKAGE_ROOT/src"
 PACKAGE_PATCHES="$PACKAGE_SRC/patches"
-TCEXTTOOLS_PATCHES="$PACKAGE_PATCHES"
 
 if [ -f "$PACKAGE_COMMON" ]; then
      . "$PACKAGE_COMMON"
 
-     _TCEXTTOOLS_ROOT="$TCEXTTOOLS_STORAGE/$PACKAGE"
-     TCEXTTOOLS_BIN="$_TCEXTTOOLS_ROOT/bin"
-     TCEXTTOOLS_SRC="$_TCEXTTOOLS_ROOT/src"
-     TCEXTTOOLS_LOG="$_TCEXTTOOLS_ROOT/log"
-     TCEXTTOOLS_PKG="$_TCEXTTOOLS_ROOT/pkg"
-     TCEXTTOOLS_BIN_TEMP="$TCEXTTOOLS_BIN/temp"
-     TCEXTTOOLS_SRC_TEMP="$TCEXTTOOLS_SRC/temp"
-     TCEXTTOOLS_PKG_TEMP="$TCEXTTOOLS_PKG/temp"
-     TCEXTTOOLS_CONFIGURE_LOG="$TCEXTTOOLS_LOG/configure.txt"
-     TCEXTTOOLS_COMPILE_LOG="$TCEXTTOOLS_LOG/compile.txt"
-     TCEXTTOOLS_INSTALL_LOG="$TCEXTTOOLS_LOG/install.txt"
-     TCEXTTOOLS_BUILD_LOG="$TCEXTTOOLS_LOG/build.txt"
-     TCEXTTOOLS_MESSAGE_LOG="$TCEXTTOOLS_LOG/message.txt"
-     TCEXTTOOLS_MESSAGE_LOG_2="$TCEXTTOOLS_LOG/message2.txt"
-     TCEXTTOOLS_INSTALL_ROOT="$TCEXTTOOLS_BIN/root"
-     TCEXTTOOLS_PACKAGE="$TCEXTTOOLS_PKG/${PACKAGE}.tar.bz2"
-     TCEXTTOOLS_PACKAGE_ENCRYPTED="$TCEXTTOOLS_PKG/${PACKAGE}.tar.bz2.bfe"
-
-     PACKAGE_BIN="$TCEXTTOOLS_BIN"
-     PACKAGE_PKG="$TCEXTTOOLS_PKG"
-     PACKAGE_PACKAGE="$TCEXTTOOLS_PACKAGE"
-     PACKAGE_PACKAGE_ENCRYPTED="$TCEXTTOOLS_PACKAGE_ENCRYPTED"
-     PACKAGE_INSTALL_ROOT="$TCEXTTOOLS_INSTALL_ROOT"
+     _PACKAGE_ROOT="$TCEXTTOOLS_STORAGE/$PACKAGE"
+     PACKAGE_BIN="$_PACKAGE_ROOT/bin"
+     _PACKAGE_SRC="$_PACKAGE_ROOT/src"
+     PACKAGE_LOG="$_PACKAGE_ROOT/log"
+     PACKAGE_PKG="$_PACKAGE_ROOT/pkg"
+     PACKAGE_BIN_TEMP="$PACKAGE_BIN/temp"
+     PACKAGE_SRC_TEMP="$_PACKAGE_SRC/temp"
+     PACKAGE_PKG_TEMP="$PACKAGE_PKG/temp"
+     PACKAGE_CONFIGURE_LOG="$PACKAGE_LOG/configure.txt"
+     PACKAGE_COMPILE_LOG="$PACKAGE_LOG/compile.txt"
+     PACKAGE_INSTALL_LOG="$PACKAGE_LOG/install.txt"
+     PACKAGE_BUILD_LOG="$PACKAGE_LOG/build.txt"
+     PACKAGE_MESSAGE_LOG="$PACKAGE_LOG/message.txt"
+     PACKAGE_MESSAGE_LOG_2="$PACKAGE_LOG/message2.txt"
+     PACKAGE_INSTALL_ROOT="$PACKAGE_BIN/root"
+     PACKAGE_PACKAGE="$PACKAGE_PKG/${PACKAGE}.tar.bz2"
+     PACKAGE_PACKAGE_ENCRYPTED="$PACKAGE_PKG/${PACKAGE}.tar.bz2.bfe"
 
      INSTALL_ROOT="$PACKAGE_INSTALL_ROOT"
      PREFIX=/usr/local
 
+     PACKAGE_BUILD_DEPENDS="$TCEXTTOOLS_DEPENDS $BUILD_DEPENDS"
+
      set_source
      set_extensions
-     set_depends
-
-     if [ -n "$SOURCE_TOPDIR" ]; then
-          TCEXTTOOLS_SOURCE_TOPDIR="$TCEXTTOOLS_SRC_TEMP/$SOURCE_TOPDIR"
-          PACKAGE_SOURCE_TOPDIR="$TCEXTTOOLS_SOURCE_TOPDIR"
-     fi
-
-     if [ "$SOURCE_TYPE" != "none" ]; then
-          TCEXTTOOLS_SOURCE="$TCEXTTOOLS_SRC/$SOURCE_NAME"
-          TCEXTTOOLS_SOURCE_CONVERTED="$TCEXTTOOLS_SRC/$SOURCE_NAME_CONVERTED"
-          PACKAGE_SOURCE="$TCEXTTOOLS_SOURCE"
-          PACKAGE_SOURCE_CONVERTED="$TCEXTTOOLS_SOURCE_CONVERTED"
-     fi
 
      # shortened variables for use in package build
      P_ROOT="$PACKAGE_ROOT"
-     T_ROOT="$_TCEXTTOOLS_ROOT"
+     _P_ROOT="$_PACKAGE_ROOT"
      P_NAME="$PACKAGE"
      P_VER="$VERSION"
      P_SRC="$PACKAGE_SRC"
-     T_SRC="$TCEXTTOOLS_SRC"
+     _P_SRC="$_PACKAGE_SRC"
+     P_SRC_TEMP="$PACKAGE_SRC_TEMP"
      P_BIN="$PACKAGE_BIN"
-     T_BIN="$TCEXTTOOLS_BIN"
-     S_SRC="$T_SRC"
      S_TOP="$SOURCE_TOPDIR"
      S_ROOT="$PACKAGE_SOURCE_TOPDIR"
      I_ROOT="$INSTALL_ROOT"
 
      # create directories
      [ -d "$TCEXTTOOLS_STORAGE" ] || sudo install -m 755 -d -o "$TCUSER" -g staff "$TCEXTTOOLS_STORAGE"
-     [ -d "$TCEXTTOOLS_BIN" ] || install -m 755 -d "$TCEXTTOOLS_BIN"
-     [ -d "$TCEXTTOOLS_SRC" ] || install -m 755 -d "$TCEXTTOOLS_SRC"
-     [ -d "$TCEXTTOOLS_PKG" ] || install -m 755 -d "$TCEXTTOOLS_PKG"
-     [ -d "$TCEXTTOOLS_LOG" ] || install -m 755 -d "$TCEXTTOOLS_LOG"
+     [ -d "$PACKAGE_BIN" ] || install -m 755 -d "$PACKAGE_BIN"
+     [ -d "$_PACKAGE_SRC" ] || install -m 755 -d "$_PACKAGE_SRC"
+     [ -d "$PACKAGE_PKG" ] || install -m 755 -d "$PACKAGE_PKG"
+     [ -d "$PACKAGE_LOG" ] || install -m 755 -d "$PACKAGE_LOG"
 
 elif [ "$THIS" != "boostit" ]; then
      print_it error "You must boost it first!"
diff --git a/tools/checkit b/tools/checkit
--- a/tools/checkit
+++ b/tools/checkit
@@ -38,46 +38,45 @@ fi
 this_check() {
 
    echo "Cleaning the extension bin temporary directory."
-   EXTENSION_BIN_TEMP="$TCEXTTOOLS_BIN_TEMP/$EXTENSION_NAME"
-   [ -d "$EXTENSION_BIN_TEMP" ] && sudo rm -rf "$EXTENSION_BIN_TEMP"
-   mkdir -p "$TCEXTTOOLS_BIN_TEMP"
+   [ -d "$PACKAGE_EXTENSION_BIN_TEMP" ] && sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
+   mkdir -p "$PACKAGE_BIN_TEMP"
 
    echo "Extracting the extension to the extension bin temporary directory."
-   sudo unsquashfs -d "$EXTENSION_BIN_TEMP" "$TCEXTTOOLS_EXTENSION_TCZ" || return 1
+   sudo unsquashfs -d "$PACKAGE_EXTENSION_BIN_TEMP" "$PACKAGE_EXTENSION_TCZ" || return 1
 
-   echo "Checking the extension files ..."
-   sudo find "$EXTENSION_BIN_TEMP" -not -type d -exec file "{}" \; || return 1
+   echo "Checking the extension files."
+   sudo find "$PACKAGE_EXTENSION_BIN_TEMP" -not -type d -exec file "{}" \; || return 1
 
    echo ""
    echo "Checking the permissions and ownership of the extension tce.installed directory."
-   if [ -d "$EXTENSION_BIN_TEMP/usr/local/tce.installed" ]; then
-        OUT=$(sudo busybox ls -d -l "$EXTENSION_BIN_TEMP/usr/local/tce.installed")
+   if [ -d "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed" ]; then
+        OUT=$(sudo busybox ls -d -l "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed")
         PERM=$(echo $OUT | cut -d" " -f1)
         OWNER=$(echo $OUT | cut -d" " -f3-4)
 
         if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
-             echo "Error! wrong permissions on the extension $EXTENSION_NAME tce.installed directory."
+             echo "Error! Wrong permissions detected for the extension $PACKAGE_EXTENSION_NAME tce.installed directory."
              return 1
         fi
 
         if [ "$OWNER" != "root staff" ]; then
-             echo "Error! wrong ownership on the extension $EXTENSION_NAME tce.installed directory."
+             echo "Error! Wrong ownership detected for the extension $PACKAGE_EXTENSION_NAME tce.installed directory."
              return 1
         fi
 
         echo "Checking the permissions and ownership of the extension tce.installed script."
-        if [ -e "$EXTENSION_BIN_TEMP/usr/local/tce.installed/$EXTENSION_NAME" ]; then
-             OUT=$(sudo busybox ls -l "$EXTENSION_BIN_TEMP/usr/local/tce.installed/$EXTENSION_NAME")
+        if [ -e "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME" ]; then
+             OUT=$(sudo busybox ls -l "$PACKAGE_EXTENSION_BIN_TEMP/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME")
              PERM=$(echo $OUT | cut -d" " -f1)
              OWNER=$(echo $OUT | cut -d" " -f3-4)
 
              if [ "$PERM" != "-rwxrwxr-x" ] && [ "$PERM" != "-rwxrwsr-x" ]; then
-                  echo "Error! wrong permissions on the extension $EXTENSION_NAME tce.installed script."
+                  echo "Error! Wrong permissions detected for the extension $PACKAGE_EXTENSION_NAME tce.installed script."
                   return 1
              fi
 
              if [ "$OWNER" != "root staff" ]; then
-                  echo "Error! wrong ownership on the extension $EXTENSION_NAME tce.installed script."
+                  echo "Error! Wrong ownership detected for the extension $PACKAGE_EXTENSION_NAME tce.installed script."
                   return 1
              fi
         fi
@@ -94,25 +93,26 @@ this_main() {
 
    for EXTENSION in $EXTENSIONS
    do
-       echo ""
-       echo "Setting the extension $EXTENSION parameters."
-       set_extension || return 1
+       set_extension
 
-       echo "Checking if the extension exists."
-       if [ ! -f "$TCEXTTOOLS_EXTENSION_TCZ" ]; then
-              echo "Error! You must create it first!"
-              return 1
+       echo -e "Checking if the extension exists ... \c"
+       if [ -f "$PACKAGE_EXTENSION_TCZ" ]; then
+            echo "yes"
+       else
+            echo "no"
+            echo "Error! You must create it first!"
+            return 1
        fi
 
-       echo "Checking the extension $EXTENSION_NAME."
+       echo "Checking the extension $PACKAGE_EXTENSION_NAME."
        this_check
        if [ "$?" -gt 0 ]; then
-            echo "Error! Checking the extension $EXTENSION_NAME failed."
-            sudo rm -rf "$EXTENSION_BIN_TEMP"
+            echo "Error! Checking the extension $PACKAGE_EXTENSION_NAME failed."
+            sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
             return 1
        else
-            echo "Checking the extension $EXTENSION_NAME successful."
-            sudo rm -rf "$EXTENSION_BIN_TEMP"
+            echo "Checking the extension $PACKAGE_EXTENSION_NAME successful."
+            sudo rm -rf "$PACKAGE_EXTENSION_BIN_TEMP"
        fi
    done
 
@@ -124,7 +124,7 @@ this_main() {
 }
 
 print_it "Checking the package $PACKAGE extensions ... \c"
-this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
+this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
diff --git a/tools/convertit b/tools/convertit
--- a/tools/convertit
+++ b/tools/convertit
@@ -35,7 +35,7 @@ else
      exit 1
 fi
 
-if [ ! -e "$TCEXTTOOLS_SOURCE" ]; then
+if [ ! -f "$PACKAGE_SOURCE" ]; then
        print_it error "You must download it first!"
        exit 1
 fi
@@ -46,75 +46,74 @@ this_main() {
    echo "Converting the package $PACKAGE source ..."
 
    echo "Cleaning the package temporary source directory."
-   [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
-   mkdir -p "$TCEXTTOOLS_SRC_TEMP"
+   [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
+   mkdir -p "$PACKAGE_SRC_TEMP"
 
-   echo "The source type is set to $SOURCE_TYPE."
+   echo "The source type is set to $PACKAGE_SOURCE_TYPE."
 
-   if [ "$SOURCE_TYPE" = "bz2" ]; then
+   if [ "$PACKAGE_SOURCE_TYPE" = "bz2" ]; then
         echo "Decompressing the package source with bzip2."
-        bzip2 -d -c "$TCEXTTOOLS_SOURCE" > "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.bz2}" || return 1
+        bzip2 -d -c "$PACKAGE_SOURCE" > "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.bz2}" || return 1
 
         echo "Compressing the package source with xz."
-        xz "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.bz2}" || return 1
+        xz "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.bz2}" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.bz2}.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "gz" ]; then
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.bz2}.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "gz" ]; then
         echo "Decompressing the package source with gzip."
-        gzip -d -c "$TCEXTTOOLS_SOURCE" > "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.gz}" || return 1
+        gzip -d -c "$PACKAGE_SOURCE" > "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.gz}" || return 1
 
         echo "Compressing the package source with xz."
-        xz "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.gz}" || return 1
+        xz "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.gz}" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.gz}.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "tgz" ]; then
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.gz}.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "tgz" ]; then
         echo "Decompressing the package source with gzip."
-        gzip -d -c "$TCEXTTOOLS_SOURCE" > "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tgz}.tar" || return 1
+        gzip -d -c "$PACKAGE_SOURCE" > "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tgz}.tar" || return 1
 
         echo "Compressing the package source with xz."
-        xz "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tgz}.tar" || return 1
+        xz "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tgz}.tar" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tgz}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "tbz2" ]; then
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tgz}.tar.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "tbz2" ]; then
         echo "Decompressing the package source with bzip2."
-        bzip2 -d -c "$TCEXTTOOLS_SOURCE" > "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tbz2}.tar" || return 1
+        bzip2 -d -c "$PACKAGE_SOURCE" > "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tbz2}.tar" || return 1
 
         echo "Compressing the package source with xz."
-        xz "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tbz2}.tar" || return 1
+        xz "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tbz2}.tar" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tbz2}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "tar" ]; then
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tbz2}.tar.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "tar" ]; then
         echo "Copying the package source to the temporary source directory."
-        cp "$TCEXTTOOLS_SOURCE" "$TCEXTTOOLS_SRC_TEMP" || return 1
+        cp "$PACKAGE_SOURCE" "$PACKAGE_SRC_TEMP" || return 1
 
         echo "Compressing the package source with xz."
-        xz "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tar}.tar" || return 1
+        xz "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tar}.tar" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.tar}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "zip" ]; then
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.tar}.tar.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "zip" ]; then
         echo "Unzipping the package source to the temporary source directory."
-        unzip "$TCEXTTOOLS_SOURCE" -d "$TCEXTTOOLS_SRC_TEMP" || return 1
+        unzip "$PACKAGE_SOURCE" -d "$PACKAGE_SRC_TEMP" || return 1
 
         echo "Creating a tarball from the unzipped source."
-        tar -C "$TCEXTTOOLS_SRC_TEMP" -cJf "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.zip}.tar.xz" "$(ls $TCEXTTOOLS_SRC_TEMP)" || return 1
+        tar -C "$PACKAGE_SRC_TEMP" -cJf "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.zip}.tar.xz" "$(ls $PACKAGE_SRC_TEMP)" || return 1
 
         echo "Moving the converted source to the package source directory."
-        mv -f "$TCEXTTOOLS_SRC_TEMP/${SOURCE_NAME%.zip}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-   elif [ "$SOURCE_TYPE" = "custom" ]; then
-        echo "Executing the custom convert function defined in the package build file."
-        cd "$TCEXTTOOLS_SRC_TEMP"
+        mv -f "$PACKAGE_SRC_TEMP/${PACKAGE_SOURCE_NAME%.zip}.tar.xz" "$_PACKAGE_SRC" || return 1
+   elif [ "$PACKAGE_SOURCE_TYPE" = "custom" ]; then
+        echo "Executing the custom build convert function."
+        cd "$PACKAGE_SRC_TEMP"
         build_convert || return 1
    else
-        echo "Error! unsupported source type."
+        echo "Error! Unsupported source type."
         return 1
    fi
 
-   echo ""
    echo "Converted the package $PACKAGE source successfully."
 
    return 0
@@ -122,7 +121,7 @@ this_main() {
 }
 
 print_it "Converting the package $PACKAGE source ... \c"
-this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
+this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
diff --git a/tools/createit b/tools/createit
--- a/tools/createit
+++ b/tools/createit
@@ -37,83 +37,79 @@ fi
 
 this_create() {
 
-   echo "Checking if the extension has a tce.installed script."
-   if [ -f "$TCEXTTOOLS_EXTENSION_TCEINSTALLED" ]; then
-        echo "Yes it has, installing it with correct permissions and ownership."
-        sudo install -D -m 775 "$TCEXTTOOLS_EXTENSION_TCEINSTALLED" "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed/$EXTENSION_NAME" || return 1
-        sudo chown -R root:staff "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed" || return 1
-        sudo chmod -R 775 "$TCEXTTOOLS_EXTENSION_BINDIR/usr/local/tce.installed" || return 1
+   echo -e "Checking if the extension has a tce.installed script ... \c"
+   if [ -f "$PACKAGE_EXTENSION_TCEINSTALLED" ]; then
+        echo "yes"
+        echo "Installing the extension tce.installed script."
+        sudo install -D -m 775 "$PACKAGE_EXTENSION_TCEINSTALLED" "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME" || return 1
+        sudo chown -R root:staff "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed" || return 1
+        sudo chmod -R 775 "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed" || return 1
    else
-        echo "Not found."
+        echo "no"
    fi
 
-   echo "Checking if the extension icon is set."
-   if [ -n "$ICON" ]; then
-        echo "Yes it is."
+   echo -e "Checking if the extension icon is set ... \c"
+   if [ -n "$PACKAGE_EXTENSION_ICON" ]; then
+        echo "yes"
 
-        echo "Setting the extension desktop file."
-        if [ -z "$DESKTOP" ]; then
-             if [ -d "$TCEXTTOOLS_EXTENSION_BINDIR/usr/share/applications" ]; then
-                  DESKTOP="/usr/share/applications/${EXTENSION_NAME}.desktop"
+        echo -e "Checking if the extension desktop file exists ... \c"
+        if [ -f "$PACKAGE_EXTENSION_DESKTOP" ]; then
+             echo "yes"
+
+             echo -e "Checking if the extension desktop has X-FullPathIcon line ... \c"
+             if [ $(grep "X-FullPathIcon=" "$PACKAGE_EXTENSION_DESKTOP") ]; then
+                  echo "yes"
+                  echo "Deleting the line with X-FullPathIcon."
+                  sudo sed -i -e "/X-FullPathIcon=/d" "$PACKAGE_EXTENSION_DESKTOP"
              else
-                  DESKTOP="/usr/local/share/applications/${EXTENSION_NAME}.desktop"
-             fi
-        fi
-
-        echo "Checking if the extension desktop file exists ..."
-        if [ -f "$TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP" ]; then
-             echo "Yes, it is found. "
-
-             echo "Checking if the extension desktop has X-FullPathIcon."
-             if [ $(grep "X-FullPathIcon=" "$TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP") ]; then
-                  echo "Yes, it has. Deleting the line containing it."
-                  sudo sed -i -e "/X-FullPathIcon=/d" "$TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP"
+                  echo "no"
              fi
 
              echo "Writing the extension icon entry to the extension desktop file."
-             sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_EXTENSION_BINDIR/$DESKTOP" || return 1
+             sudo sh -c "echo \"X-FullPathIcon=$PACKAGE_EXTENSION_ICON\" >> $PACKAGE_EXTENSION_DESKTOP" || return 1
         else
-             echo "Error! the extension desktop file not found."
+             echo "no"
+             echo "Error! the extension desktop file not found but the icon is set."
              return 1
         fi
    else
-        echo "No, it is not."
+        echo "no"
    fi
 
    echo "Cleaning the package bin directory from previously created extension files."
-   sudo rm -f "$TCEXTTOOLS_BIN"/*.tcz*
+   sudo rm -f "$PACKAGE_BIN"/*.tcz*
 
-   cd "$TCEXTTOOLS_BIN"
+   cd "$PACKAGE_BIN"
 
    echo "Creating the extension tcz file."
-   sudo mksquashfs "$EXTENSION_NAME" "${EXTENSION_NAME}.tcz" || return 1
+   sudo mksquashfs "$PACKAGE_EXTENSION_NAME" "${PACKAGE_EXTENSION_NAME}.tcz" || return 1
 
    echo "Creating the extension md5 sum."
-   md5sum "${EXTENSION_NAME}.tcz" > "${EXTENSION_NAME}.tcz.md5.txt" || return 1
+   md5sum "${PACKAGE_EXTENSION_NAME}.tcz" > "${PACKAGE_EXTENSION_NAME}.tcz.md5.txt" || return 1
 
-
-   cd "$TCEXTTOOLS_EXTENSION_BINDIR"
+   cd "$PACKAGE_EXTENSION_BIN"
 
    echo "Creating the extension list file."
-   sudo find * -not -type d | sort > "$TCEXTTOOLS_BIN/${EXTENSION_NAME}.tcz.list"
+   sudo find * -not -type d | sort > "$PACKAGE_BIN/${PACKAGE_EXTENSION_NAME}.tcz.list"
 
    echo "Cleaning the extension pkg directory."
-   [ -d "$TCEXTTOOLS_EXTENSION_PKGDIR" ] && sudo rm -rf "$TCEXTTOOLS_EXTENSION_PKGDIR"
-   mkdir -p "$TCEXTTOOLS_EXTENSION_PKGDIR"
+   [ -d "$PACKAGE_EXTENSION_PKG" ] && sudo rm -rf "$PACKAGE_EXTENSION_PKG"
+   mkdir -p "$PACKAGE_EXTENSION_PKG"
 
-   echo "Copying the freshly created extension files to the extension pkg directory."
-   cp -f "$TCEXTTOOLS_BIN/${EXTENSION_NAME}".tcz* "$TCEXTTOOLS_EXTENSION_PKGDIR" || return 1
+   echo "Copying the extension files to the extension pkg directory."
+   cp -f "$PACKAGE_BIN/${PACKAGE_EXTENSION_NAME}".tcz* "$PACKAGE_EXTENSION_PKG" || return 1
 
-   echo "Checking if the extension has a dep file."
+   echo -e "Checking if the extension has a dep file ... \c"
    if [ -f "$PACKAGE_EXTENSION_DEP" ]; then
-        echo "Yes, it does. Copying it to the extension pkg directory."
-        install -m 644 "$PACKAGE_EXTENSION_DEP" "$TCEXTTOOLS_EXTENSION_DEP" || return 1
+        echo "yes"
+        echo "Copying it to the extension pkg directory."
+        install -m 644 "$PACKAGE_EXTENSION_DEP" "$_PACKAGE_EXTENSION_DEP" || return 1
    else
-        echo "No, it does not."
+        echo "no"
    fi
 
    echo "Cleaning the package bin directory from previously created extension files."
-   sudo rm -f "$TCEXTTOOLS_BIN"/*.tcz*
+   sudo rm -f "$PACKAGE_BIN"/*.tcz*
 
    return 0
 
@@ -126,28 +122,29 @@ this_main() {
 
    echo ""
    echo "Cleaning the package pkg directory."
-   [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG"
-   mkdir -p "$TCEXTTOOLS_PKG"
+   [ -d "$PACKAGE_PKG" ] && sudo rm -rf "$PACKAGE_PKG"
+   mkdir -p "$PACKAGE_PKG"
 
    for EXTENSION in $EXTENSIONS
    do
-       echo ""
-       echo "Setting the extension $EXTENSION parameters."
-       set_extension || return 1
+       set_extension
 
-       echo "Checking if the extension is splitted before."
-       if [ ! -d "$TCEXTTOOLS_EXTENSION_BINDIR" ]; then
-              echo "Error! You must split it first!"
-              return 1
+       echo -e "Checking if the extension is splitted before ... \c"
+       if [ -d "$PACKAGE_EXTENSION_BIN" ]; then
+            echo "yes"
+       else
+            echo "no"
+            echo "Error! You must split it first!"
+            return 1
        fi
 
-       echo "Creating the extension $EXTENSION_NAME."
+       echo "Creating the extension $PACKAGE_EXTENSION_NAME."
        this_create
        if [ "$?" -gt 0 ]; then
-            echo "Error! Creating the extension $EXTENSION_NAME failed."
+            echo "Error! Creating the extension $PACKAGE_EXTENSION_NAME failed."
             return 1
        else
-            echo "Creating the extension $EXTENSION_NAME successful."
+            echo "Creating the extension $PACKAGE_EXTENSION_NAME successful."
        fi
    done
 
@@ -159,7 +156,7 @@ this_main() {
 }
 
 print_it "Creating the package $PACKAGE extensions ... \c"
-this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
+this_main > "$PACKAGE_MESSAGE_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
