- Modified tet shell functions

diff --git a/common/tet-functions b/common/tet-functions
--- a/common/tet-functions
+++ b/common/tet-functions
@@ -26,8 +26,6 @@ export TET_PACKAGES_DATABASE="${HOME}/.local/share/tet/packages_db"
 
 _tet_common() {
 
-   CMD="$@"
-
    if [ -f "$HOME/.config/tet.conf" ]; then
         . "$HOME/.config/tet.conf"
    else
@@ -63,7 +61,7 @@ tetcd() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         cd "$TET_PACKAGES"
         return 0
    fi
@@ -76,7 +74,7 @@ tetcd() {
    fi
 
    if [ ! -d "$PACKAGE_ROOT" ]; then
-        echo "tetcd: Package $PACKAGE root directory does not exist"
+        echo "tetcd: The package $PACKAGE root directory does not exist"
         return 1
    fi
 
@@ -89,7 +87,7 @@ tetls() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         ls "$TET_PACKAGES_DATABASE"
         return 0
    fi
@@ -101,7 +99,12 @@ tetls() {
         return 1
    fi
 
-   cd "$PACKAGE_ROOT" || { echo "package is removed probably" ; return 1; }
+   if [ ! -d "$PACKAGE_ROOT" ]; then
+        echo "tetls: The package $PACKAGE root directory does not exist"
+        return 1
+   fi
+
+   cd "$PACKAGE_ROOT"
    ls $ARGS
    cd - > /dev/null
 
@@ -112,7 +115,7 @@ tetfind() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         find "$TET_PACKAGES" -not -path *.svn*
         return 0
    fi
@@ -121,6 +124,11 @@ tetfind() {
         . "$TET_PACKAGES_DATABASE/$PACKAGE"
    else
         echo "tetfind: No such package $PACKAGE"
+        return 1
+   fi
+
+   if [ ! -d "$PACKAGE_ROOT" ]; then
+        echo "tetfind: The package $PACKAGE root directory does not exist"
         return 1
    fi
 
@@ -135,8 +143,8 @@ teted() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
-        echo "teted: package ?"
+   if [ -z "$PACKAGE" ]; then
+        echo "teted: You must specify the package"
         return 1
    fi
 
@@ -148,12 +156,12 @@ teted() {
    fi
 
    if [ -z "$TET_EDITOR" ]; then
-        echo "teted: You need to set tc-ext-tools editor"
+        echo "teted: You need to set the tc-ext-tools editor in your configuration file"
         return 1
    fi
 
    if ! which "$TET_EDITOR" >/dev/null 2>&1; then
-        echo "teted: Editor $TET_EDITOR not found"
+        echo "teted: The text editor $TET_EDITOR not found"
         return 1
    fi
 
@@ -227,7 +235,7 @@ tetbrowse() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         $TET_FILE_MANAGER "$TET_PACKAGES" &
         return 0
    fi
@@ -240,7 +248,17 @@ tetbrowse() {
    fi
 
    if [ ! -d "$PACKAGE_ROOT" ]; then
-        echo "tetbrowse: Package $PACKAGE root directory does not exist"
+        echo "tetbrowse: The package $PACKAGE root directory does not exist"
+        return 1
+   fi
+
+   if [ -z "$TET_FILE_MANAGER" ]; then
+        echo "tetbrowse: You need to set the tc-ext-tools file manager in your configuration file"
+        return 1
+   fi
+
+   if ! which "$TET_FILE_MANAGER" >/dev/null 2>&1; then
+        echo "tetbrowse: The file manager $TET_FILE_MANAGER not found"
         return 1
    fi
 
@@ -253,7 +271,7 @@ tetinfo() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         echo "tetinfo: You must specify the package"
         return 0
    fi
@@ -279,7 +297,7 @@ tetwww() {
 
    _tet_common "$@" || return 1
 
-   if [ -z "$CMD" -a -z "$PACKAGE" ]; then
+   if [ -z "$PACKAGE" ]; then
         echo "tetwww: You must specify the package"
         return 0
    fi
@@ -293,6 +311,16 @@ tetwww() {
 
    if [ ! -d "$PACKAGE_ROOT" ]; then
         echo "tetwww: Package $PACKAGE root directory does not exist"
+        return 1
+   fi
+
+   if [ -z "$TET_WEB_BROWSER" ]; then
+        echo "tetwww: You need to set the tc-ext-tools web browser in your configuration file"
+        return 1
+   fi
+
+   if ! which "$TET_WEB_BROWSER" >/dev/null 2>&1; then
+        echo "tetbrowse: The web browser $TET_WEB_BROWSER not found"
         return 1
    fi
 
