This is an update to tc-ext-tools - Variable name manipulations, new variables, name changes etc - Removed unnecessary code from installit regarding gnome help browser files - Gnome help browser files are no longer called locale, an update to related packages must be made in the future - Changed the order of rule stripit from before splitit to after splitit - Updated stripit to a standart shape like its friends

diff --git a/tools/buildit b/tools/buildit
--- a/tools/buildit
+++ b/tools/buildit
@@ -37,7 +37,7 @@ fi
 
 print_usage(){
 
-   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} (clean|clear)|load|download|convert|unpack|patch|configure|compile|install|strip|split|create|check|generate|package|compress|encrypt|show|help|all${NORMAL}"
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} (clean|clear)|load|download|convert|unpack|patch|configure|compile|install|split|strip|create|check|generate|package|compress|encrypt|show|help${NORMAL}"
 
 }
 
@@ -170,10 +170,10 @@ install_it() {
 
 }
 
-strip_it() {
+split_it() {
 
-   print_it "Stripping the package $PACKAGE ... \c"
-   stripit "$TCEXTTOOLS_INSTALL_ROOT" > "$TCEXTTOOLS_MESSAGE_LOG" 2>&1
+   print_it "Splitting the package $PACKAGE extensions ... \c"
+   splitit > "$TCEXTTOOLS_MESSAGE_LOG" 2>&1
    if [ "$?" -gt 0 ]; then
         print_it error "failed!"
         print_it warning "For details: buildit show error"
@@ -183,10 +183,10 @@ strip_it() {
 
 }
 
-split_it() {
+strip_it() {
 
-   print_it "Splitting the package $PACKAGE extensions ... \c"
-   splitit > "$TCEXTTOOLS_MESSAGE_LOG" 2>&1
+   print_it "Stripping the package $PACKAGE ... \c"
+   stripit > "$TCEXTTOOLS_MESSAGE_LOG" 2>&1
    if [ "$?" -gt 0 ]; then
         print_it error "failed!"
         print_it warning "For details: buildit show error"
@@ -211,7 +211,7 @@ create_it() {
 
 generate_it() {
 
-   print_it "Generating the package $PACKAGE extensions' info files ... \c"
+   print_it "Generating the package $PACKAGE extension info files ... \c"
    generateit > "$TCEXTTOOLS_MESSAGE_LOG" 2>&1
    if [ "$?" -gt 0 ]; then
         print_it error "failed!"
@@ -331,7 +331,7 @@ show_it() {
 }
 
 if [ -z "$1" ]; then
-     "$0" all
+     build_it || exit 1
      exit 0
 fi
 
@@ -363,11 +363,11 @@ case "$1" in
 	install)
 		  install_it
 		  ;;
-	strip)
-		  strip_it
-		  ;;
 	split)
 		  split_it
+		  ;;
+	strip)
+		  strip_it
 		  ;;
 	create)
 		  create_it
@@ -392,9 +392,6 @@ case "$1" in
 		  ;;
 	custom)
 		  custom_it
-		  ;;
-	all)
-		  build_it
 		  ;;
 	*)
 		  print_usage
diff --git a/tools/stripit b/tools/stripit
--- a/tools/stripit
+++ b/tools/stripit
@@ -35,39 +35,26 @@ else
      exit 1
 fi
 
-TARGET_DIR="$1"
-
-print_usage(){
-
-   echo -e "${TCEXTTOOLS_ERROR_COLOR}${THIS} usage:\n\t${TCEXTTOOLS_MESSAGE_COLOR}${THIS} /path/to/directory${NORMAL}"
-
-}
-
-if [ -z "$TARGET_DIR" ] || [ ! -d "$TARGET_DIR" ]; then
-      print_usage
-      exit 1
-fi
-
 ############################################################################ 
 #                                this main                                 #
 ############################################################################
 
-this_main() {
+this_strip() {
 
-   EXE_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
-   SO_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+   EXECUTABLE_LIST=$(sudo find "$TCEXTTOOLS_EXTENSION_BINDIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+   SHARED_OBJECT_LIST=$(sudo find "$TCEXTTOOLS_EXTENSION_BINDIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
 
-   if [ -n "$EXE_LIST" ]; then
-        for i in $EXE_LIST
+   if [ -n "$EXECUTABLE_LIST" ]; then
+        for EXECUTABLE in $EXECUTABLE_LIST
         do
-            sudo strip --strip-unneeded "$i" || return 1
+            sudo strip --strip-unneeded "$EXECUTABLE" || return 1
         done
    fi
 
-   if [ -n "$SO_LIST" ]; then
-        for i in $SO_LIST
+   if [ -n "$SHARED_OBJECT_LIST" ]; then
+        for SHARED_OBJECT in $SHARED_OBJECT_LIST
         do
-            sudo strip -g "$i" || return 1
+            sudo strip -g "$SHARED_OBJECT" || return 1
         done
    fi
 
@@ -75,7 +62,32 @@ this_main() {
 
 }
 
-print_it "Stripping the files in the target directory ... \c"
+this_main() {
+
+   for EXTENSION in $EXTENSIONS
+   do
+       set_extension || return 1
+
+       if [ ! -d "$TCEXTTOOLS_EXTENSION_BINDIR" ]; then
+              print_it error "You must split it first!"
+              return 1
+       fi
+
+       this_strip
+       if [ "$?" -gt 0 ]; then
+            print_it error "Stripping the extension $EXTENSION_NAME failed!"
+            sudo rm -rf "$TMP_DIR"
+            return 1
+       else
+            print_it "Stripping the extension $EXTENSION_NAME successful!"
+       fi
+   done
+
+   return 0
+
+}
+
+print_it "Stripping the package $PACKAGE extensions ... \c"
 this_main > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
