- Updated tc-ext-tools: - Added more output to message level 2 - Removed unneccessary comments

diff --git a/tools/buildit b/tools/buildit
--- a/tools/buildit
+++ b/tools/buildit
@@ -58,7 +58,7 @@ download_it() {
 
    if [ -f "$PACKAGE_SOURCE" ]; then
         print_it warning "The package $PACKAGE source is already downloaded."
-        print_it warning "Run downloadit to force it to download the package source."
+        print_it warning "Run downloadit to force download the package source."
         exit 0
    fi
 
@@ -77,7 +77,7 @@ convert_it() {
 
    if [ -f "$PACKAGE_SOURCE_CONVERTED" ]; then
         print_it warning "The package $PACKAGE source is already converted."
-        print_it warning "Run convertit to force it to convert the package source."
+        print_it warning "Run convertit to force convert the package source."
         exit 0
    fi
 
@@ -254,28 +254,42 @@ encrypt_it() {
 
 }
 
-custom_it() {
+custom_function() {
 
-   build_custom || exit 1
+   FUNCTION="$1"
+
+   if [ -z "$FUNCTION" ]; then
+        print_it error "You need to specify the name of the custom function."
+        exit 1
+   fi
+
+   print_it "Executing the package $PACKAGE custom build function $FUNCTION ... \c"
+   build_${FUNCTION} > "$TCEXTTOOLS_MESSAGE_LOG_2" 2>&1
+   if [ "$?" -gt 0 ]; then
+        print_it error "failed!"
+        print_it warning "For details: buildit print error"
+        exit 1
+   fi
+   print_it hilight "successful!"
 
 }
 
 build_it() {
 
-   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE started at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR} on ${TCEXTTOOLS_HILIGHT_COLOR}$DATE${NORMAL}"
-   set_date && SECONDS_BEFORE="$SECONDS"
+   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE started at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR}"
+   set_date; SECONDS_BEFORE="$SECONDS"
    clean_it || exit 1
    build_rules || exit 1
-   set_date && SECONDS_AFTER="$SECONDS"
-   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE finished at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR} on ${TCEXTTOOLS_HILIGHT_COLOR}$DATE${TCEXTTOOLS_MESSAGE_COLOR} in ${TCEXTTOOLS_HILIGHT_COLOR}$(expr $SECONDS_AFTER - $SECONDS_BEFORE)${TCEXTTOOLS_MESSAGE_COLOR} seconds${NORMAL}"
+   set_date; SECONDS_AFTER="$SECONDS"
+   echo -e "${TCEXTTOOLS_MESSAGE_COLOR}Building the package $PACKAGE finished at ${TCEXTTOOLS_HILIGHT_COLOR}$TIME${TCEXTTOOLS_MESSAGE_COLOR} in ${TCEXTTOOLS_HILIGHT_COLOR}$(expr $SECONDS_AFTER - $SECONDS_BEFORE)${TCEXTTOOLS_MESSAGE_COLOR} seconds${NORMAL}"
    encrypt_it || exit 1
 
 }
 
-_print_it() {
+print_function() {
 
    case "$1" in
-        download) 
+        download)
                  [ -e "$TCEXTTOOLS_DOWNLOAD_LOG" ] && { cat "$TCEXTTOOLS_DOWNLOAD_LOG" ; echo -e "${NORMAL}\c" ; }
                  ;;
         configure)
@@ -353,10 +367,10 @@ case "$1" in
 		  encrypt_it
 		  ;;
 	print)
-		  _print_it "$2"
+		  print_function "$2"
 		  ;;
 	custom)
-		  custom_it
+		  custom_function "$2"
 		  ;;
 	*)
 		  print_usage
diff --git a/tools/patchit b/tools/patchit
--- a/tools/patchit
+++ b/tools/patchit
@@ -40,29 +40,41 @@ if [ -z "$TCEXTTOOLS_SOURCE_TOPDIR" ]; then
      exit 1
 fi
 
-############################################################################ 
-#                                this main                                 #
-############################################################################
-
 this_main() {
 
+   echo ""
+   echo "Patching the package $PACKAGE ..."
+
+   echo ""
+   echo "Checking for the package $PACKAGE patches ..."
    if [ -f "$TCEXTTOOLS_PATCHES/series" ]; then
         echo "Using the series file to detect the package patches."
         PATCHES=$(cat "$TCEXTTOOLS_PATCHES/series")
    elif [ -d "$TCEXTTOOLS_PATCHES" ]; then
-        echo "Listing the patch files under the package patches directory."
+        echo "No series file, getting the list of patches from the package patches directory contents."
         PATCHES=$(ls "$TCEXTTOOLS_PATCHES")
    fi
 
    if [ -n "$PATCHES" ]; then
+        echo ""
+        echo "Patches detected. Printing detected patches ..."
+        echo "PATCHES = $PATCHES"
+
+        echo ""
+        echo "Processing patches ..."
         for PATCH in $PATCHES
         do
+           echo "PATCH = $PATCH"
            if [ -d "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
                 echo "Skipping the patch $PATCH. It is a directory not a patch!"
                 continue
            fi
+
+           echo ""
+           echo "Detecting the patch level ..."
            for i in $(cat $TCEXTTOOLS_PATCHES/$PATCH | grep "\-\-\-" | cut -f2 -d" " | cut -f1 -d" ")
            do
+               PATCH_LEVEL=""
                if [ -f "$TCEXTTOOLS_SOURCE_TOPDIR/$i" ]; then
                     PATCH_LEVEL=0
                else
@@ -70,13 +82,31 @@ this_main() {
                fi
                break
            done
-           if [ -f "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
-                echo "Applying the patch $PATCH with patch level $PATCH_LEVEL ..."
-                patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np$PATCH_LEVEL -i "$TCEXTTOOLS_PATCHES/$PATCH" || return 1
+
+           if [ -z "$PATCH_LEVEL" ]; then
+                echo ""
+                echo "Error! patch level for $PATCH can not be detected."
+                return 1
            fi
-           echo "Applied the patch $PATCH successfully."
+
+           if [ ! -f "$TCEXTTOOLS_PATCHES/$PATCH" ]; then
+                echo ""
+                echo "Error! The patch $PATCH is not a regular file."
+                return 1
+           fi
+
+           echo ""
+           echo "Applying the patch $PATCH with patch level $PATCH_LEVEL ..."
+           patch --directory="$TCEXTTOOLS_SOURCE_TOPDIR" -Np$PATCH_LEVEL -i "$TCEXTTOOLS_PATCHES/$PATCH" || return 1
         done
+   else
+        echo ""
+        echo "No patch found. Skipping ..."
+        return 0
    fi
+
+   echo ""
+   echo "Patching the package completed successfully."
 
    return 0
 
diff --git a/tools/splitit b/tools/splitit
--- a/tools/splitit
+++ b/tools/splitit
@@ -40,88 +40,136 @@ if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
        exit 1
 fi
 
-############################################################################ 
-#                splits the files out of install root                      #
-############################################################################
-
 this_split() {
 
+   echo ""
+   echo "Getting the contents of the extension install ..."
    CONTENTS=$(cat $PACKAGE_EXTENSION_INSTALL)
-   [ -z "$CONTENTS" ] && return 1
+   if [ -z "$CONTENTS" ]; then
+        echo "Error! the extension install is empty."
+        return 1
+   fi
+   echo "CONTENTS = $CONTENTS"
+   echo ""
 
-   LIST="${TMP_DIR}/install.list"
-   X_LIST="${TMP_DIR}/x-install.list"
+   echo ""
+   echo "Touching install.list and x-install.list files."
+   LIST="${TCEXTTOOLS_BIN_TEMP}/install.list"
+   X_LIST="${TCEXTTOOLS_BIN_TEMP}/x-install.list"
+   touch "$LIST"
+   touch "$X_LIST"
+   echo ""
 
-   touch "$LIST" || return 1
-   touch "$X_LIST" || return 1
-
+   echo ""
+   echo "Processing the extension install contents ..."
    cd "$TCEXTTOOLS_INSTALL_ROOT"
-
    for i in $CONTENTS
    do
-       i=$(eval echo $i)
-       if [ -z "$(echo "$i" | grep '*')" ]; then
-               if [ "${i#\#}" = "$i" ]; then
-                    if [ "${i#x-}" = "$i" ]; then
-                         sudo find "$i" -not -type d >> "$LIST" || return 1
-                    else
-                         i="${i#x-}"
-                         sudo find "$i" -not -type d >> "$X_LIST" || return 1
-                    fi
-               fi
-       else
-               if [ "${i#\#}" = "$i" ]; then
-                    if [ "${i#x-}" = "$i" ]; then
-                         sudo find $i -not -type d >> "$LIST" || return 1
-                    else
-                         i="${i#x-}"
-                         sudo find $i -not -type d >> "$X_LIST" || return 1
-                    fi
-               fi
+       echo ""
+       echo "Processing the content $i ..."
+
+       echo ""
+       echo "Checking if the content is commented out ..."
+       if [ "${i#\#}" != "$i" ]; then
+            echo "The content $i is commented out. Skipping it."
+            continue
        fi
+       echo ""
+
+       echo ""
+       echo "Evaluating the content $i ..."
+       i=$(eval echo $i)
+       echo "The content is $i after the evaluation."
+       echo ""
+
+       echo ""
+       echo "Checking if a special wildcard used."
+       if [ -n "$(echo "$i" | grep '*')" ]; then
+            echo "The wildcard * found in the content."
+       fi
+       echo ""
+
+       echo ""
+       if [ -z "$(echo "$i" | grep '*')" ]; then
+            if [ "${i#x-}" = "$i" ]; then
+                 echo "Putting the files in the content to the include list."
+                 sudo find "$i" -not -type d >> "$LIST" || return 1
+            else
+                 i="${i#x-}"
+                 echo "Putting the files in the content to the exclude list."
+                 sudo find "$i" -not -type d >> "$X_LIST" || return 1
+            fi
+       else
+            if [ "${i#x-}" = "$i" ]; then
+                 echo "Putting the files in the content to the include list."
+                 sudo find $i -not -type d >> "$LIST" || return 1
+            else
+                 i="${i#x-}"
+                 echo "Putting the files in the content to the exclude list."
+                 sudo find $i -not -type d >> "$X_LIST" || return 1
+            fi
+       fi
+       echo ""
    done
+   echo ""
 
-   sudo tar -T "$LIST" -X "$X_LIST" -cpzf "$TMP_DIR/pkg.tar.gz" || return 1
-   sudo mkdir -p "$TMP_DIR/root" || return 1
-   sudo tar -C "$TMP_DIR/root" -pxzf "$TMP_DIR/pkg.tar.gz" || return 1
+   echo ""
+   echo "Creating the extension contents tarball from the include and the exclude lists."
+   sudo tar -T "$LIST" -X "$X_LIST" -cvpzf "$TCEXTTOOLS_BIN_TEMP/pkg.tar.gz" || return 1
+   echo ""
 
-   if [ -d "$TCEXTTOOLS_EXTENSION_BINDIR" ]; then
-        sudo rm -rf "$TCEXTTOOLS_EXTENSION_BINDIR" || return 1
-   fi
+   echo "Cleaning the package extension bin directory."
+   [ -d "$TCEXTTOOLS_EXTENSION_BINDIR" ] && sudo rm -rf "$TCEXTTOOLS_EXTENSION_BINDIR"
+   sudo mkdir -p "$TCEXTTOOLS_EXTENSION_BINDIR"
 
-   sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_EXTENSION_BINDIR" || return 1
+   echo ""
+   echo "Extracting the extension contents tarball to the extension bin directory."
+   sudo mkdir -p "$TCEXTTOOLS_EXTENSION_BINDIR"
+   sudo tar -C "$TCEXTTOOLS_EXTENSION_BINDIR" -pvxzf "$TCEXTTOOLS_BIN_TEMP/pkg.tar.gz" || return 1
+   echo ""
 
-   sudo rm -rf "$TMP_DIR"
+   echo ""
+   echo "Cleaning the extension bin temporary directory."
+   sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
+   echo ""
 
    return 0
 
 }
 
-############################################################################ 
-#                                this main                                 #
-############################################################################
-
 this_main() {
+
+   echo ""
+   echo "Starting the splitting process for the package $PACKAGE ..."
 
    for EXTENSION in $EXTENSIONS
    do
+       echo ""
+       echo "Processing the extension $EXTENSION ..."
+
+       echo ""
+       echo "Setting the extension parameters."
        set_extension || return 1
 
-       TMP_DIR=$(busybox mktemp -d)
-       if [ ! -d "$TMP_DIR" ]; then
-              print_it error "Creating a temporary directory for splitting the extension $EXTENSION_NAME failed!"
-              return 1
-       fi
+       echo ""
+       echo "Cleaning the package bin temporary directory."
+       [ -d "$TCEXTTOOLS_BIN_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
+       mkdir -p "$TCEXTTOOLS_BIN_TEMP"
 
+       echo ""
+       echo "Splitting the extension $EXTENSION_NAME ..."
        this_split
        if [ "$?" -gt 0 ]; then
-            print_it error "Splitting the extension $EXTENSION_NAME failed!"
-            sudo rm -rf "$TMP_DIR"
+            echo "Error! splitting the extension $EXTENSION_NAME failed."
+            sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
             return 1
        else
-            print_it "Splitting the extension $EXTENSION_NAME successful!"
+            echo "Splitting the extension $EXTENSION_NAME successful."
        fi
    done
+
+   echo ""
+   echo "Splitted the package $PACKAGE extensions successfully."
 
    return 0
 
