- Added two new tools: configureit, and compileit - Added KERNEL support to extension naming - All code reviewed and edited for better visual, and standarts

diff --git a/tools/checkit b/tools/checkit
--- a/tools/checkit
+++ b/tools/checkit
@@ -35,88 +35,105 @@ else
      exit 1
 fi
 
+for EXTENSION in $EXTENSIONS
+do
+    . "$PACKAGE_COMMON"
+
+    set_extension_name
+
+    if [ ! -e "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" ]; then
+           print_it error "You must create it first!"
+           exit 1
+    fi
+done
+
+############################################################################ 
+#                        checks the extension                              #
+############################################################################
+
 this_check() {
 
-  sudo busybox mount -o loop "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" "$TMPDIR" || return 1
+   sudo busybox mount -o loop "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" "$TMPDIR" || return 1
 
-  FILES="$(sudo find $TMPDIR -not -type d)"
-  SAVEIFS="$IFS"
-  IFS="$(echo -en "\n\b")"
-  for f in $FILES
-  do
-      sudo file "$f" || return 1
-  done
-  IFS="$SAVEIFS"
+   FILES="$(sudo find $TMPDIR -not -type d)"
+   SAVEIFS="$IFS"
+   IFS="$(echo -en "\n\b")"
+   for f in $FILES
+   do
+       sudo file "$f" || return 1
+   done
+   IFS="$SAVEIFS"
 
-  if [ -d "$TMPDIR/usr/local/tce.installed" ]; then
-       OUT=$(sudo busybox ls -d -l "$TMPDIR/usr/local/tce.installed")
-       PERM=$(echo $OUT | cut -d" " -f1)
-       OWNER=$(echo $OUT | cut -d" " -f3-4)
+   if [ -d "$TMPDIR/usr/local/tce.installed" ]; then
+        OUT=$(sudo busybox ls -d -l "$TMPDIR/usr/local/tce.installed")
+        PERM=$(echo $OUT | cut -d" " -f1)
+        OWNER=$(echo $OUT | cut -d" " -f3-4)
 
-       if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
-            print_it error "Wrong permissions on $EXTENSION_NAME tce.installed directory."
-            print_it warning "Expected permissions drwxrwxr-x or drwxrwsr-x but found permissions $PERM"
-            return 1
-       fi
+        if [ "$PERM" != "drwxrwxr-x" ] && [ "$PERM" != "drwxrwsr-x" ]; then
+             print_it error "Wrong permissions on $EXTENSION_NAME tce.installed directory."
+             print_it warning "Expected permissions drwxrwxr-x or drwxrwsr-x but found permissions $PERM"
+             return 1
+        fi
 
-       if [ "$OWNER" != "root staff" ]; then
-            print_it error "Wrong ownership on $EXTENSION_NAME tce.installed directory."
-            print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
-            return 1
-       fi
+        if [ "$OWNER" != "root staff" ]; then
+             print_it error "Wrong ownership on $EXTENSION_NAME tce.installed directory."
+             print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
+             return 1
+        fi
 
-       if [ -e "$TMPDIR/usr/local/tce.installed/$EXTENSION_NAME" ]; then
-            OUT=$(sudo busybox ls -l "$TMPDIR/usr/local/tce.installed/$EXTENSION_NAME")
-            PERM=$(echo $OUT | cut -d" " -f1)
-            OWNER=$(echo $OUT | cut -d" " -f3-4)
+        if [ -e "$TMPDIR/usr/local/tce.installed/$EXTENSION_NAME" ]; then
+             OUT=$(sudo busybox ls -l "$TMPDIR/usr/local/tce.installed/$EXTENSION_NAME")
+             PERM=$(echo $OUT | cut -d" " -f1)
+             OWNER=$(echo $OUT | cut -d" " -f3-4)
 
-            if [ "$PERM" != "-rwxrwxr-x" ] && [ "$PERM" != "-rwxrwsr-x" ]; then
-                 print_it error "Wrong permissions on $EXTENSION_NAME tce.installed script."
-                 print_it warning "Expected permissions -rwxrwxr-x or -rwxrwsr-x but found permissions $PERM"
-                 return 1
-            fi
+             if [ "$PERM" != "-rwxrwxr-x" ] && [ "$PERM" != "-rwxrwsr-x" ]; then
+                  print_it error "Wrong permissions on $EXTENSION_NAME tce.installed script."
+                  print_it warning "Expected permissions -rwxrwxr-x or -rwxrwsr-x but found permissions $PERM"
+                  return 1
+             fi
 
-            if [ "$OWNER" != "root staff" ]; then
-                 print_it error "Wrong ownership on $EXTENSION_NAME tce.installed script."
-                 print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
-                 return 1
-            fi
-       fi
-  fi
+             if [ "$OWNER" != "root staff" ]; then
+                  print_it error "Wrong ownership on $EXTENSION_NAME tce.installed script."
+                  print_it warning "Expected ownership \"root staff\" but found ownership \"$OWNER\""
+                  return 1
+             fi
+        fi
+   fi
 
-  sudo busybox umount "$TMPDIR"
-  sudo rm -rf "$TMPDIR"
+   sudo busybox umount "$TMPDIR"
+   sudo rm -rf "$TMPDIR"
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                                this main                                 #
+############################################################################
 
 this_main() {
 
-  for EXTENSION in $EXTENSIONS
-  do
-      . "$PACKAGE_COMMON"
+   for EXTENSION in $EXTENSIONS
+   do
+       . "$PACKAGE_COMMON"
 
-      set_extension_name
+       set_extension_name
 
-      if [ ! -e "$TCEXTTOOLS_PKG/$EXTENSION_NAME/${EXTENSION_NAME}.tcz" ]; then
-             print_it error "You must create it first!"
-             exit 1
-      fi
+       TMPDIR=$(busybox mktemp -d)
 
-      TMPDIR=$(busybox mktemp -d)
+       this_check
+       if [ "$?" -gt 0 ]; then
+            print_it error "Checking the extension $EXTENSION_NAME failed!"
+            sudo busybox umount "$TMPDIR"
+            sudo rm -rf "$TMPDIR"
+            return 1
+       else
+            print_it "Checking the extension $EXTENSION_NAME successful!"
+       fi
+   done
 
-      this_check
-      if [ "$?" -gt 0 ]; then
-           print_it error "Checking the extension $EXTENSION_NAME failed!"
-           sudo busybox umount "$TMPDIR"
-           sudo rm -rf "$TMPDIR"
-           return 1
-      else
-           print_it "Checking the extension $EXTENSION_NAME successful!"
-      fi
-  done
+   return 0
 
-  return 0
 }
 
 print_it "Checking the package $PACKAGE extensions ... \c"
diff --git a/tools/compressit b/tools/compressit
--- a/tools/compressit
+++ b/tools/compressit
@@ -40,67 +40,79 @@ TARGET="$2"
 NAME="$3"
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) bz2|gz|xz /path/to/target name${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) bz2|gz|xz /path/to/target name${NORMAL}"
+
 }
 
-if [ -z "$TARGET" -o -z "$FORMAT" ]; then
+if [ -z "$TARGET" ] || [ -z "$FORMAT" ]; then
      print_usage
      exit 1
 fi
 
-compress() {
+############################################################################ 
+#            compresses the target with a compression format               #
+############################################################################
 
-  if [ -d "$TARGET" ]; then
-       TOP_DIR="$(basename $TARGET)"
-       if [ -n "$NAME" ]; then
-            OUTPUT="${NAME}.tar.${FORMAT}"
-       else
-            OUTPUT="${TOP_DIR}.tar.${FORMAT}"
-       fi
+this_compress() {
 
-       [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
+   if [ -d "$TARGET" ]; then
+        TOP_DIR="$(basename $TARGET)"
+        if [ -n "$NAME" ]; then
+             OUTPUT="${NAME}.tar.${FORMAT}"
+        else
+             OUTPUT="${TOP_DIR}.tar.${FORMAT}"
+        fi
 
-       tar -C $(dirname $TARGET) -c"${XXX}f" "$OUTPUT" "$TOP_DIR" || return 1
+        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
 
-  elif [ -f "$TARGET" ]; then
-       if [ -n "$NAME" ]; then
+        tar -C $(dirname $TARGET) -c"${XXX}f" "$OUTPUT" "$TOP_DIR" || return 1
+
+   elif [ -f "$TARGET" ]; then
+        if [ -n "$NAME" ]; then
             OUTPUT="${NAME}.${FORMAT}"
-       else
+        else
             OUTPUT="$(basename $TARGET).${FORMAT}"
-       fi
+        fi
 
-       [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
+        [ -e "$OUTPUT" ] && sudo rm -f "$OUTPUT"
 
-       "$COMPRESSOR" -c "$TARGET" > "$OUTPUT" || return 1
-  fi
+        "$COMPRESSOR" -c "$TARGET" > "$OUTPUT" || return 1
+   fi
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                                this main                                 #
+############################################################################
 
 this_main() {
 
-  case "$FORMAT" in
-       bz2)
-           COMPRESSOR="bzip2"
-           XXX=j
-           compress || return 1
-           ;;
-       gz)
-           COMPRESSOR="gzip"
-           XXX="z"
-           compress || return 1
-           ;;
-       xz)
-           COMPRESSOR="xz"
-           XXX="J"
-           compress || return 1
-           ;;
-       *)
-           return 1
-           ;;
-  esac
+   case "$FORMAT" in
+        bz2)
+            COMPRESSOR="bzip2"
+            XXX=j
+            this_compress || return 1
+            ;;
+        gz)
+            COMPRESSOR="gzip"
+            XXX="z"
+            this_compress || return 1
+            ;;
+        xz)
+            COMPRESSOR="xz"
+            XXX="J"
+            this_compress || return 1
+            ;;
+        *)
+            return 1
+            ;;
+   esac
 
-  return 0
+   return 0
+
 }
 
 print_it "Compressing the target $TARGET with the compression format $FORMAT ... \c"
diff --git a/tools/downloadit b/tools/downloadit
--- a/tools/downloadit
+++ b/tools/downloadit
@@ -35,31 +35,36 @@ else
      exit 1
 fi
 
+############################################################################ 
+#                                this main                                 #
+############################################################################
+
 this_main() {
 
-  [ -d "$TCEXTTOOLS_SRC" ] && sudo rm -rf "$TCEXTTOOLS_SRC"
-  mkdir -p "$TCEXTTOOLS_SRC" || return 1
+   [ -d "$TCEXTTOOLS_SRC" ] && sudo rm -rf "$TCEXTTOOLS_SRC"
+   mkdir -p "$TCEXTTOOLS_SRC" || return 1
 
-  if [ "$VCS" = "svn" ]; then
-       [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
-       mkdir -p "$TCEXTTOOLS_SRC_TEMP"
-       svn --non-interactive --trust-server-cert co "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
-       compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
-       busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-  elif [ "$VCS" = "git" ]; then
-       [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
-       mkdir -p "$TCEXTTOOLS_SRC_TEMP"
-       git clone "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
-       compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
-       busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
-  elif [ -z "$VCS" ]; then
-       busybox wget --no-check-certificate "$SOURCE" -O "$TCEXTTOOLS_SRC/$SOURCE_NAME" || return 1
-  else
-       echo "Error! Unsupported source type."
-       return 1
-  fi
+   if [ "$VCS" = "svn" ]; then
+        [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
+        mkdir -p "$TCEXTTOOLS_SRC_TEMP"
+        svn --non-interactive --trust-server-cert co "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
+        compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
+        busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
+   elif [ "$VCS" = "git" ]; then
+        [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
+        mkdir -p "$TCEXTTOOLS_SRC_TEMP"
+        git clone "$SOURCE" "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
+        compressit xz "$TCEXTTOOLS_SRC_TEMP/$TOP_SRC" || return 1
+        busybox mv -f "${TOP_SRC}.tar.xz" "$TCEXTTOOLS_SRC" || return 1
+   elif [ -z "$VCS" ]; then
+        busybox wget --no-check-certificate "$SOURCE" -O "$TCEXTTOOLS_SRC/$SOURCE_NAME" || return 1
+   else
+        echo "Error! Unsupported source type."
+        return 1
+   fi
 
-  return 0
+   return 0
+
 }
 
 print_it "Downloading the package $PACKAGE source ... \c"
diff --git a/tools/encryptit b/tools/encryptit
--- a/tools/encryptit
+++ b/tools/encryptit
@@ -38,21 +38,33 @@ fi
 FILE="$1"
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/file${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/file${NORMAL}"
+
 }
 
-if [ -z "$FILE" -o ! -e "$FILE" ]; then
+if [ -z "$FILE" ] || [ ! -e "$FILE" ]; then
       print_usage
       exit 1
 fi
 
-[ -e "${PACKAGE}.tar.bz2.bfe" ] && sudo rm -f "${PACKAGE}.tar.bz2.bfe"
+############################################################################ 
+#                                this main                                 #
+############################################################################
+
+this_main() {
+
+   [ -e "${PACKAGE}.tar.bz2.bfe" ] && sudo rm -f "${PACKAGE}.tar.bz2.bfe"
+
+   bcrypt "$FILE" || return 1
+
+   return 0
+
+}
 
 print_it "Please enter the encryption key: \c"
 print_it hilight "$TCEXTTOOLS_ENCRYPTION_KEY"
-
-bcrypt "$FILE"
-
+this_main
 if [ "$?" -gt 0 ]; then
      exit 1
 fi
diff --git a/tools/splitit b/tools/splitit
--- a/tools/splitit
+++ b/tools/splitit
@@ -36,107 +36,122 @@ else
 fi
 
 if [ ! -d "$TCEXTTOOLS_INSTALL_ROOT" ]; then
-     print_it error "You must install it first!"
-     exit 1
+       print_it error "You must install it first!"
+       exit 1
 fi
+
+############################################################################ 
+#                splits the files out of install root                      #
+############################################################################
 
 this_split() {
 
-  CONTENTS="$(cat $PACKAGE_EXTENSIONS/$EXTENSION/install)"
-  [ -z "$CONTENTS" ] && return 1
+   CONTENTS="$(cat $PACKAGE_EXTENSIONS/$EXTENSION/install)"
+   [ -z "$CONTENTS" ] && return 1
 
-  LIST="${TMP_DIR}/install.list"
-  X_LIST="${TMP_DIR}/x-install.list"
+   LIST="${TMP_DIR}/install.list"
+   X_LIST="${TMP_DIR}/x-install.list"
 
-  touch "$LIST" || return 1
-  touch "$X_LIST" || return 1
+   touch "$LIST" || return 1
+   touch "$X_LIST" || return 1
 
-  cd "$TCEXTTOOLS_INSTALL_ROOT"
+   cd "$TCEXTTOOLS_INSTALL_ROOT"
 
-  for i in $CONTENTS
-  do
-      if [ -z "$(echo "$i" | grep '*')" ]; then
-              if [ "${i#\#}" = "$i" ]; then
-                   if [ "${i#x-}" = "$i" ]; then
-                        sudo find "$i" -not -type d >> "$LIST" || return 1
-                   else
-                        i="${i#x-}"
-                        sudo find "$i" -not -type d >> "$X_LIST" || return 1
-                   fi
-              fi
-      else
-              if [ "${i#\#}" = "$i" ]; then
-                   if [ "${i#x-}" = "$i" ]; then
-                        sudo find $i -not -type d >> "$LIST" || return 1
-                   else
-                        i="${i#x-}"
-                        sudo find $i -not -type d >> "$X_LIST" || return 1
-                   fi
-              fi
-      fi
-  done
+   for i in $CONTENTS
+   do
+       if [ -z "$(echo "$i" | grep '*')" ]; then
+               if [ "${i#\#}" = "$i" ]; then
+                    if [ "${i#x-}" = "$i" ]; then
+                         sudo find "$i" -not -type d >> "$LIST" || return 1
+                    else
+                         i="${i#x-}"
+                         sudo find "$i" -not -type d >> "$X_LIST" || return 1
+                    fi
+               fi
+       else
+               if [ "${i#\#}" = "$i" ]; then
+                    if [ "${i#x-}" = "$i" ]; then
+                         sudo find $i -not -type d >> "$LIST" || return 1
+                    else
+                         i="${i#x-}"
+                         sudo find $i -not -type d >> "$X_LIST" || return 1
+                    fi
+               fi
+       fi
+   done
 
-  sudo tar -T "$LIST" -X "$X_LIST" -cpzf "$TMP_DIR/pkg.tar.gz" || return 1
-  sudo mkdir "$TMP_DIR/root"
-  sudo tar -C "$TMP_DIR/root" -pxzf "$TMP_DIR/pkg.tar.gz" || return 1
+   sudo tar -T "$LIST" -X "$X_LIST" -cpzf "$TMP_DIR/pkg.tar.gz" || return 1
+   sudo mkdir "$TMP_DIR/root"
+   sudo tar -C "$TMP_DIR/root" -pxzf "$TMP_DIR/pkg.tar.gz" || return 1
 
-  if [ -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
-       sudo rm -rf "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
-  fi
+   if [ -d "$TCEXTTOOLS_BIN/$EXTENSION_NAME" ]; then
+        sudo rm -rf "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
+   fi
 
-  sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
+   sudo mv "$TMP_DIR/root" "$TCEXTTOOLS_BIN/$EXTENSION_NAME" || return 1
 
-  sudo rm -rf "$TMP_DIR"
+   sudo rm -rf "$TMP_DIR"
 
-  return 0
+   return 0
+
 }
+
+############################################################################ 
+#                    modifies the files of an extension                    #
+############################################################################
 
 this_modify() {
 
-  if [ -n "$ICON" ]; then
-       if [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON" ]; then
-            print_it error "The icon: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON does not exist!"
-            return 1
-       elif [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" ]; then
-            print_it error "The desktop entry: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP does not exist!"
-            return 1
-       else
-            sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" || return 1
-            unset ICON
-            unset DESKTOP
-       fi
-  fi
+   if [ -n "$ICON" ]; then
+        if [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON" ]; then
+               print_it error "The icon: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$ICON does not exist!"
+               return 1
+        elif [ ! -e "$TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" ]; then
+               print_it error "The desktop entry: $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP does not exist!"
+               return 1
+        else
+             sudo sh -c "echo \"X-FullPathIcon=$ICON\" >> $TCEXTTOOLS_BIN/$EXTENSION_NAME/$DESKTOP" || return 1
+             unset ICON
+             unset DESKTOP
+        fi
+   fi
+
 }
+
+############################################################################ 
+#                                this main                                 #
+############################################################################
 
 this_main() {
 
-  for EXTENSION in $EXTENSIONS
-  do
-      . "$PACKAGE_COMMON"
+   for EXTENSION in $EXTENSIONS
+   do
+       . "$PACKAGE_COMMON"
 
-      set_extension_name
+       set_extension_name
 
-      TMP_DIR=$(busybox mktemp -d)
+       TMP_DIR=$(busybox mktemp -d)
 
-      this_split
-      if [ "$?" -gt 0 ]; then
-           print_it error "Splitting the extension $EXTENSION_NAME failed!"
-           sudo rm -rf "$TMP_DIR"
-           return 1
-      else
-           print_it "Splitting the extension $EXTENSION_NAME successful!"
-      fi
+       this_split
+       if [ "$?" -gt 0 ]; then
+            print_it error "Splitting the extension $EXTENSION_NAME failed!"
+            sudo rm -rf "$TMP_DIR"
+            return 1
+       else
+            print_it "Splitting the extension $EXTENSION_NAME successful!"
+       fi
 
-      this_modify
-      if [ "$?" -gt 0 ]; then
-           print_it error "Modifying the extension $EXTENSION_NAME failed!"
-           return 1
-      else
-           print_it "Modifying the extension $EXTENSION_NAME successful!"
-      fi
-  done
+       this_modify
+       if [ "$?" -gt 0 ]; then
+            print_it error "Modifying the extension $EXTENSION_NAME failed!"
+            return 1
+       else
+            print_it "Modifying the extension $EXTENSION_NAME successful!"
+       fi
+   done
 
-  return 0
+   return 0
+
 }
 
 print_it "Splitting the package $PACKAGE extensions ... \c"
diff --git a/tools/stripit b/tools/stripit
--- a/tools/stripit
+++ b/tools/stripit
@@ -38,34 +38,41 @@ fi
 TARGET_DIR="$1"
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/directory${NORMAL}"
+
+   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/directory${NORMAL}"
+
 }
 
-if [ -z "$TARGET_DIR" -o ! -d "$TARGET_DIR" ]; then
+if [ -z "$TARGET_DIR" ] || [ ! -d "$TARGET_DIR" ]; then
       print_usage
       exit 1
 fi
 
+############################################################################ 
+#                                this main                                 #
+############################################################################
+
 this_main() {
 
-  EXE_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
-  SO_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+   EXE_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+   SO_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
 
-  if [ -n "$EXE_LIST" ]; then
-       for i in $EXE_LIST
-       do
-           sudo strip --strip-unneeded "$i" || return 1
-       done
-  fi
+   if [ -n "$EXE_LIST" ]; then
+        for i in $EXE_LIST
+        do
+            sudo strip --strip-unneeded "$i" || return 1
+        done
+   fi
 
-  if [ -n "$SO_LIST" ]; then
-       for i in $SO_LIST
-       do
-           sudo strip -g "$i" || return 1
-       done
-  fi
+   if [ -n "$SO_LIST" ]; then
+        for i in $SO_LIST
+        do
+            sudo strip -g "$i" || return 1
+        done
+   fi
 
-  return 0
+   return 0
+
 }
 
 print_it "Stripping the files in the target directory ... \c"
