- Completed new stamp mechanism for tc-ext-tools

diff --git a/tools/checkit b/tools/checkit
--- a/tools/checkit
+++ b/tools/checkit
@@ -34,6 +34,11 @@ else
      exit 1
 fi
 
+if [ -n "$HAVE_TET_CREATE" -a ! -f "$PACKAGE_CREATE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must create it first!${NORMAL}"
+     exit 1
+fi
+
 this_check() {
 
    echo "Cleaning the package extension bin temporary directory."
@@ -136,6 +141,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_CHECK_STAMP" ] && sudo rm -f "$PACKAGE_CHECK_STAMP"
+
 echo -e "${MESSAGE_COLOR}Checking the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extensions ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -144,6 +151,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_CHECK_STAMP"
 
 exit 0
 
diff --git a/tools/createit b/tools/createit
--- a/tools/createit
+++ b/tools/createit
@@ -34,6 +34,16 @@ else
      exit 1
 fi
 
+if [ -n "$HAVE_TET_SPLIT" -a ! -f "$PACKAGE_SPLIT_STAMP" ]; then
+     echo "${ERROR_COLOR}You must split it first!${NORMAL}"
+     exit 1
+fi
+
+if [ -n "$HAVE_TET_STRIP" -a ! -f "$PACKAGE_STRIP_STAMP" ]; then
+     echo "${ERROR_COLOR}You must strip it first!${NORMAL}"
+     exit 1
+fi
+
 this_create() {
 
    echo -e "Checking if the extension has a tce.installed script ... \c"
@@ -170,6 +180,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_CREATE_STAMP" ] && sudo rm -f "$PACKAGE_CREATE_STAMP"
+
 echo -e "${MESSAGE_COLOR}Creating the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extensions ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -178,6 +190,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_CREATE_STAMP"
 
 exit 0
 
diff --git a/tools/encryptit b/tools/encryptit
--- a/tools/encryptit
+++ b/tools/encryptit
@@ -34,9 +34,9 @@ else
      exit 1
 fi
 
-if [ ! -f "$PACKAGE_PACKAGE" ]; then
-       echo "${ERROR_COLOR}You must package it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_PACKAGE" -a ! -f "$PACKAGE_PACKAGE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must package it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
diff --git a/tools/generateit b/tools/generateit
--- a/tools/generateit
+++ b/tools/generateit
@@ -34,6 +34,11 @@ else
      exit 1
 fi
 
+if [ -n "$HAVE_TET_CREATE" -a ! -f "$PACKAGE_CREATE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must create it first!${NORMAL}"
+     exit 1
+fi
+
 this_generate() {
 
    echo "Setting the extension description."
@@ -132,6 +137,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_GENERATE_STAMP" ] && sudo rm -f "$PACKAGE_GENERATE_STAMP"
+
 echo -e "${MESSAGE_COLOR}Generating the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extension info files ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -140,6 +147,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_GENERATE_STAMP"
 
 exit 0
 
diff --git a/tools/splitit b/tools/splitit
--- a/tools/splitit
+++ b/tools/splitit
@@ -34,9 +34,9 @@ else
      exit 1
 fi
 
-if [ ! -d "$PACKAGE_INSTALL_ROOT" ]; then
-       echo "${ERROR_COLOR}You must install it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_INSTALL" -a ! -f "$PACKAGE_INSTALL_STAMP" ]; then
+     echo "${ERROR_COLOR}You must install it first!${NORMAL}"
+     exit 1
 fi
 
 this_split() {
@@ -177,6 +177,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_SPLIT_STAMP" ] && sudo rm -f "$PACKAGE_SPLIT_STAMP"
+
 echo -e "${MESSAGE_COLOR}Splitting the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} extensions ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -185,6 +187,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_SPLIT_STAMP"
 
 exit 0
 
