- Revolutionary changes with this update - Added support for packages with custom source such as nvidia - Updated buildit and other tools to fit design standarts - Added new tool cleanit as a result of buildit update - Updated packageit not to package custom src directory anymore - And many others see diff for details

diff --git a/tools/cleanit b/tools/cleanit
--- a/tools/cleanit
+++ b/tools/cleanit
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#  encryptit: Encrypts the file with the default encryption key
+#  cleanit: Cleans the package
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -30,27 +30,34 @@ else
      exit 1
 fi
 
-FILE="$1"
+this_main() {
+  
+  [ -d "$TCEXTTOOLS_BIN" ] && sudo rm -rf "$TCEXTTOOLS_BIN"
+  mkdir -p "$TCEXTTOOLS_BIN" || return 1
 
-print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/file${NORMAL}"
+  [ -d "$TCEXTTOOLS_PKG" ] && sudo rm -rf "$TCEXTTOOLS_PKG"
+  mkdir -p "$TCEXTTOOLS_PKG" || return 1
+
+  [ -d "$TCEXTTOOLS_BIN_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_BIN_TEMP"
+  mkdir -p "$TCEXTTOOLS_BIN_TEMP" || return 1
+
+  [ -d "$TCEXTTOOLS_SRC_TEMP" ] && sudo rm -rf "$TCEXTTOOLS_SRC_TEMP"
+  mkdir -p "$TCEXTTOOLS_SRC_TEMP" || return 1
+
+  [ -d "$TCEXTTOOLS_LOG" ] && sudo rm -rf "$TCEXTTOOLS_LOG"
+  mkdir -p "$TCEXTTOOLS_LOG" || return 1
+
+  return 0
 }
 
-if [ -z "$FILE" -o ! -e "$FILE" ]; then
-      print_usage
-      exit 1
-fi
-
-[ -e "${PACKAGE}.tar.bz2.bfe" ] && sudo rm -f "${PACKAGE}.tar.bz2.bfe"
-
-print_it "Please enter the encryption key: \c"
-print_it hilight "$TCEXTTOOLS_ENCRYPTION_KEY"
-
-bcrypt "$FILE"
-
+print_it "Cleaning the package $PACKAGE ... \c"
+this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
+     print_it error "failed!"
      exit 1
 fi
+
+print_it hilight "successful!"
 
 exit 0
 
diff --git a/tools/createit b/tools/createit
--- a/tools/createit
+++ b/tools/createit
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#  createit: Creates the extension
+#  createit: Creates the package extensions
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -30,23 +30,7 @@ else
      exit 1
 fi
 
-EXTENSION="$1"
-
-if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION" ]; then
-     print_it error "You must split it first!"
-     exit 1
-fi
-
-print_usage() {
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
-}
-
-if [ -z "$EXTENSION" ]; then
-     print_usage
-     exit 1
-fi
-
-this_main() {
+this_create() {
 
   cd $PACKAGE_ROOT
 
@@ -87,7 +71,31 @@ this_main() {
   return 0
 }
 
-print_it "Creating the extension $EXTENSION ... \c"
+this_main() {
+
+  [ -d "$TCEXTTOOLS_EXTENSIONS" ] && sudo rm -rf "$TCEXTTOOLS_EXTENSIONS"
+  mkdir -p "$TCEXTTOOLS_EXTENSIONS"
+
+  for EXTENSION in $EXTENSIONS
+  do
+      if [ ! -d "$TCEXTTOOLS_BIN/$EXTENSION" ]; then
+           print_it error "You must split it first!"
+           exit 1
+      fi
+
+      this_create
+      if [ "$?" -gt 0 ]; then
+           print_it error "Creating the extension $EXTENSION failed!"
+           return 1
+      else
+           print_it "Creating the extension $EXTENSION successful!"
+      fi
+  done
+
+  return 0
+}
+
+print_it "Creating the package $PACKAGE extensions ... \c"
 this_main > "$TCEXTTOOLS_ERROR_LOG_2" 2>&1
 if [ "$?" -gt 0 ]; then
      print_it error "failed!"
