- This update implements a new stamp mechanism used for transitions

diff --git a/tools/compileit b/tools/compileit
--- a/tools/compileit
+++ b/tools/compileit
@@ -34,9 +34,9 @@ else
      exit 1
 fi
 
-if [ ! -d "$PACKAGE_SOURCE_TOPDIR" ]; then
-       echo "${ERROR_COLOR}You must configure it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_CONFIGURE" -a ! -f "$PACKAGE_CONFIGURE_STAMP" ]; then
+     echo "${ERROR_COLOR}You must configure it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
@@ -64,6 +64,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_COMPILE_STAMP" ] && sudo rm -f "$PACKAGE_COMPILE_STAMP"
+
 echo -e "${MESSAGE_COLOR}Compiling the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -72,6 +74,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_COMPILE_STAMP"
 
 exit 0
 
diff --git a/tools/convertit b/tools/convertit
--- a/tools/convertit
+++ b/tools/convertit
@@ -34,9 +34,9 @@ else
      exit 1
 fi
 
-if [ ! -f "$PACKAGE_SOURCE_ORIG" ]; then
-       echo "${ERROR_COLOR}You must download it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_DOWNLOAD" -a ! -f "$PACKAGE_DOWNLOAD_STAMP" ]; then
+     echo "${ERROR_COLOR}You must download it first!${NORMAL}"
+     exit 1
 fi
 
 this_main() {
@@ -132,6 +132,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_CONVERT_STAMP" ] && sudo rm -f "$PACKAGE_CONVERT_STAMP"
+
 echo -e "${MESSAGE_COLOR}Converting the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} source ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -140,6 +142,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_CONVERT_STAMP"
 
 exit 0
 
diff --git a/tools/installit b/tools/installit
--- a/tools/installit
+++ b/tools/installit
@@ -38,9 +38,9 @@ if [ "$PACKAGE_SOURCE_TYPE" = "none" ]; then
      mkdir -p "$PACKAGE_SOURCE_TOPDIR"
 fi
 
-if [ ! -d "$PACKAGE_SOURCE_TOPDIR" ]; then
-       echo "${ERROR_COLOR}You must compile it first!${NORMAL}"
-       exit 1
+if [ -n "$HAVE_TET_COMPILE" -a ! -f "$PACKAGE_COMPILE_STAMP" ]; then
+      echo "${ERROR_COLOR}You must compile it first!${NORMAL}"
+      exit 1
 fi
 
 this_main() {
@@ -76,6 +76,8 @@ this_main() {
 
 }
 
+[ -f "$PACKAGE_INSTALL_STAMP" ] && sudo rm -f "$PACKAGE_INSTALL_STAMP"
+
 echo -e "${MESSAGE_COLOR}Installing the package ${HILIGHT_COLOR}$PACKAGE${MESSAGE_COLOR} ... ${NORMAL}\c"
 this_main > "$PACKAGE_MESSAGE_LOG" 2>&1
 if [ "$?" -gt 0 ]; then
@@ -84,6 +86,8 @@ if [ "$?" -gt 0 ]; then
      exit 1
 fi
 echo "${HILIGHT_COLOR}successful!${NORMAL}"
+
+touch "$PACKAGE_INSTALL_STAMP"
 
 exit 0
 
