added mercurial support: prepend hg:: to url

diff --git a/tools/downloadit b/tools/downloadit
--- a/tools/downloadit
+++ b/tools/downloadit
@@ -46,7 +46,7 @@ this_main() {
    [ -d "$_PACKAGE_SRC" ] && sudo rm -rf "$_PACKAGE_SRC"
    mkdir -p "$_PACKAGE_SRC" || return 1
 
-   if [ "$PACKAGE_SOURCE_URL_TYPE" = "svn" ] || [ "$PACKAGE_SOURCE_URL_TYPE" = "git" ]; then
+   if [ -n "$VERSION_CONTROL_SYSTEM" ]; then
         echo "Cleaning the package src temporary directory"
         [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
         mkdir -p "$PACKAGE_SRC_TEMP" || return 1
@@ -63,45 +63,82 @@ this_main() {
              fi
 
              echo -e "Getting svn repository revision number ... \c"
-             SVN_REVISION=$(grep "Checked out revision" "$PACKAGE_MESSAGE_LOG" | cut -f4 -d" " | sed 's/\.//')
+             if [ -z "$SKIP_REVISION" ]; then
+                  SVN_REVISION=$(grep "Checked out revision" "$PACKAGE_MESSAGE_LOG" | cut -f4 -d" " | sed 's/\.//')
 
-             if [ -n "$SVN_REVISION" -a -z "$SKIP_SVN_REVISION" ]; then
-                  echo "$SVN_REVISION"
-                  VERSION_NEW="svn~r${SVN_REVISION}"
-                  if [ "$VERSION_NEW" != "$VERSION" ]; then
-                       VERSION="$VERSION_NEW"
+                  if [ -n "$SVN_REVISION" ]; then
+                       echo "$SVN_REVISION"
+                       VERSION_NEW="svn~r${SVN_REVISION}"
+                       if [ "$VERSION_NEW" != "$VERSION" ]; then
+                            VERSION="$VERSION_NEW"
 
-                       echo "Adjusting the package version according to svn revision number"
-                       sed -i "s/VERSION=.*/VERSION=\"${VERSION}\"/" "$PACKAGE_COMMON" || return 1
+                            echo "Adjusting the package version according to revision number"
+                            sed -i "s/VERSION=.*/VERSION=\"${VERSION}\"/" "$PACKAGE_COMMON" || return 1
 
-                       echo "Renaming the package source top level directory"
-                       SOURCE_TOPDIR="${PACKAGE}-${VERSION}"
-                       mv "$PACKAGE_SOURCE_TOPDIR" "$PACKAGE_SRC_TEMP/$SOURCE_TOPDIR" || return 1
+                            echo "Renaming the package source top level directory"
+                            SOURCE_TOPDIR="${PACKAGE}-${VERSION}"
+                            mv "$PACKAGE_SOURCE_TOPDIR" "$PACKAGE_SRC_TEMP/$SOURCE_TOPDIR" || return 1
 
-                       PACKAGE_SOURCE_TOPDIR="$PACKAGE_SRC_TEMP/$PACKAGE-$VERSION"
-                       PACKAGE_SOURCE_NAME="${PACKAGE}-${VERSION}.tar.xz"
+                            PACKAGE_SOURCE_TOPDIR="$PACKAGE_SRC_TEMP/$PACKAGE-$VERSION"
+                            PACKAGE_SOURCE_NAME="${PACKAGE}-${VERSION}.tar.xz"
+                       else
+                            echo "No version change, skipping ..."
+                       fi
                   else
-                       echo "No version change, skipping ..."
+                       echo "failed!"
                   fi
              else
-                  echo "failed!"
+                  echo "skipping"
              fi
-
-             echo "Creating a tarball from the source"
-             tar --exclude-vcs -cvJf "$PACKAGE_SOURCE_NAME" "$SOURCE_TOPDIR" || return 1
-
-             echo "Moving the tarball to the package source directory"
-             mv -f "$PACKAGE_SOURCE_NAME" "$_PACKAGE_SRC" || return 1
         elif [ "$PACKAGE_SOURCE_URL_TYPE" = "git" ]; then
              echo "Cloning the git repository $SOURCE"
              git clone "$SOURCE" "$PACKAGE_SOURCE_TOPDIR" || return 1
+        elif [ "$PACKAGE_SOURCE_URL_TYPE" = "hg" ]; then
+             echo "Checking out the mercurial repository $SOURCE"
+             HG_CMD="hg clone $SOURCE $PACKAGE_SOURCE_TOPDIR"
+             if [ -n "$HG_FLAGS" ]; then
+                  $HG_CMD $HG_FLAGS || return 1
+             else
+                  $HG_CMD || return 1
+             fi
 
-             echo "Creating a tarball from the source"
-             tar --exclude-vcs -cvJf "$PACKAGE_SOURCE_NAME" "$SOURCE_TOPDIR" || return 1
+             echo -e "Getting mercurial repository revision number ... \c"
+             if [ -z "$SKIP_REVISION" ]; then
+                  cd "$PACKAGE_SOURCE_TOPDIR"
+                  HG_REVISION=$(hg identify -i)
+                  cd - >/dev/null
 
-             echo "Moving the tarball to the package source directory"
-             mv -f "$PACKAGE_SOURCE_NAME" "$_PACKAGE_SRC" || return 1
+                  if [ -n "$HG_REVISION" ]; then
+                       echo "$HG_REVISION"
+                       VERSION_NEW="~${HG_REVISION}"
+                       if [ "$VERSION_NEW" != "$VERSION" ]; then
+                            VERSION="$VERSION_NEW"
+
+                            echo "Adjusting the package version according to revision number"
+                            sed -i "s/VERSION=.*/VERSION=\"${VERSION}\"/" "$PACKAGE_COMMON" || return 1
+
+                            echo "Renaming the package source top level directory"
+                            SOURCE_TOPDIR="${PACKAGE}-${VERSION}"
+                            mv "$PACKAGE_SOURCE_TOPDIR" "$PACKAGE_SRC_TEMP/$SOURCE_TOPDIR" || return 1
+
+                            PACKAGE_SOURCE_TOPDIR="$PACKAGE_SRC_TEMP/$PACKAGE-$VERSION"
+                            PACKAGE_SOURCE_NAME="${PACKAGE}-${VERSION}.tar.xz"
+                       else
+                            echo "No version change, skipping ..."
+                       fi
+                  else
+                       echo "failed!"
+                  fi
+             else
+                  echo "skipping"
+             fi
         fi
+
+        echo "Creating a tarball from the source"
+        tar --exclude-vcs -cvJf "$PACKAGE_SOURCE_NAME" "$SOURCE_TOPDIR" || return 1
+
+        echo "Moving the tarball to the package source directory"
+        mv -f "$PACKAGE_SOURCE_NAME" "$_PACKAGE_SRC" || return 1
    elif [ "$PACKAGE_SOURCE_URL_TYPE" = "generic" ]; then
         echo "Downloading the package source $PACKAGE_SOURCE_NAME from $SOURCE"
         wget --no-check-certificate "$SOURCE" -O "$PACKAGE_SOURCE_ORIG" || return 1
