- Added ooo-build (openoffice3) package - Updated midori - Updated all tools and fixed many bugs see diffs for details

diff --git a/tools/encryptit b/tools/encryptit
--- a/tools/encryptit
+++ b/tools/encryptit
@@ -23,30 +23,30 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-FILE="${1}"
+FILE="$1"
 
 print_usage(){
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/file${NORMAL}"
 }
 
-if [ -z "${FILE}" -o ! -e "${FILE}" ]; then
+if [ -z "$FILE" -o ! -e "$FILE" ]; then
       print_usage
       exit 1
 fi
 
 print_it "Please enter the encryption key: \c"
-print_it hilight "${TCEXTTOOLS_ENCRYPTION_KEY}"
+print_it hilight "$TCEXTTOOLS_ENCRYPTION_KEY"
 
-bcrypt ${FILE}
+bcrypt $FILE
 
-if [ $? -gt 0 ]; then
+if [ "$?" -gt 0 ]; then
      exit 1
 fi
 
diff --git a/tools/generateit b/tools/generateit
--- a/tools/generateit
+++ b/tools/generateit
@@ -23,45 +23,45 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-EXTENSION="${1}"
+EXTENSION="$1"
 
 print_usage(){
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) extension${NORMAL}"
 }
 
-if [ -z "${EXTENSION}" ]; then
+if [ -z "$EXTENSION" ]; then
       print_usage
       exit 1
 fi
 
-if [ ! -e "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz" ]; then
+if [ ! -e "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz" ]; then
      print_it error "You must create it first!"
      exit 1
 fi
 
 this_main() {
 
-  CURRENT="${DATE} ${CURRENT}"
-  SIZE="$(du -h "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz" | cut -f1)"
-  [ ! "${EXTENSION%-bin}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, utilities."
-  [ ! "${EXTENSION%-lib}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, shared libraries."
-  [ ! "${EXTENSION%-dev}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, development files."
-  [ ! "${EXTENSION%-doc}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, documentation files."
-  [ ! "${EXTENSION%-locale}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, locale files."
-  [ ! "${EXTENSION%-gir}" = "${EXTENSION}" ] && DESCRIPTION="${DESCRIPTION%.}, gobject introspection data."
+  CURRENT="$DATE $CURRENT"
+  SIZE=$(du -h "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz" | cut -f1)
+  [ ! "${EXTENSION%-bin}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, utilities."
+  [ ! "${EXTENSION%-lib}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, shared libraries."
+  [ ! "${EXTENSION%-dev}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, development files."
+  [ ! "${EXTENSION%-doc}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, documentation files."
+  [ ! "${EXTENSION%-locale}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, locale files."
+  [ ! "${EXTENSION%-gir}" = "$EXTENSION" ] && DESCRIPTION="${DESCRIPTION%.}, gobject introspection data."
 
-  if [ -e "${PACKAGE_EXTENSIONS}/${EXTENSION}/info" ]; then
-      . ${PACKAGE_EXTENSIONS}/${EXTENSION}/info
+  if [ -e "$PACKAGE_EXTENSIONS"/"$EXTENSION"/info ]; then
+      . "$PACKAGE_EXTENSIONS"/"$EXTENSION"/info
   fi
 
-  cat > ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/${EXTENSION}.tcz.info << _EOF
+  cat > "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/"${EXTENSION}.tcz.info" << _EOF
 Title:		${EXTENSION}.tcz
 Description:	${DESCRIPTION}
 Version:	${VERSION}
@@ -75,7 +75,7 @@ Change-log:	${CHANGELOG}
 Current:	${CURRENT}
 _EOF
 
-  if [ $? -gt 0 ]; then
+  if [ "$?" -gt 0 ]; then
        print_it error "Failed to write ${EXTENSION}.tcz.info"
        return 1
   fi
@@ -83,9 +83,9 @@ _EOF
   return 0
 }
 
-print_it "Generating the extension ${EXTENSION} info ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Generating the extension $EXTENSION info ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/tools/loadit b/tools/loadit
--- a/tools/loadit
+++ b/tools/loadit
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#  loadit: Loads required dependencies to build the package
+#  loadit: Loads the extensions required to build the package
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -23,42 +23,42 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+        . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
-     exit 1
+        echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+        exit 1
 fi
 
-DEP_LIST="${1}"
+EXT_LIST="$1"
 
 TCE_DIR=$(cat /opt/.tce_dir)
-if [ $? -gt 0 ]; then
+if [ "$?" -gt 0 ]; then
      print_it error "Getting system tce directory failed!"
      exit 1
 fi
 
 print_usage(){
-  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) \"dep1 dep2 dep3\" | /path/to/deplist${NORMAL}"
+  echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) \"ext1 ext2 ext3\" | /path/to/extlist${NORMAL}"
 }
 
-if [ -z "${DEP_LIST}" ]; then
+if [ -z "$EXT_LIST" ]; then
      print_usage
      exit 1
 fi
 
 tcz_load() {
 
-  extension="${1}"
-  if [ -n "${extension}" ]; then
-       if [ "${extension#"#"}" = ${extension} ]; then
-            if [ ! -e "${TCE_DIR}/optional/${extension%.tcz}.tcz" ]; then
-                 tce-load -w ${extension%.tcz}.tcz || return 1
+  extension="$1"
+  if [ -n "$extension" ]; then
+       if [ "${extension#\#}" = "$extension" ]; then
+            if [ ! -e "$TCE_DIR"/optional/"${extension%.tcz}.tcz" ]; then
+                 tce-load -w "${extension%.tcz}.tcz" || return 1
             fi
-            if [ ! -e "/usr/local/tce.installed/${extension%.tcz}" ]; then
-                 tce-load -i ${extension%.tcz}.tcz || return 1
+            if [ ! -e /usr/local/tce.installed/"${extension%.tcz}" ]; then
+                 tce-load -i "${extension%.tcz}.tcz" || return 1
             fi
-        fi
+       fi
   fi
 
   return 0
@@ -66,25 +66,27 @@ tcz_load() {
 
 this_main() {
 
-  if [ -f "${DEP_LIST}" ]; then
-       DEP_LIST=$(cat ${DEP_LIST})
-       if [ -z "${DEP_LIST}" ]; then
+  if [ -f "$EXT_LIST" ]; then
+       EXT_LIST=$(cat $EXT_LIST)
+       if [ -z "$EXT_LIST" ]; then
             print_it error "Dependency list file is empty!"
             return 1
        fi
   fi
 
-  for DEP in ${DEP_LIST}
+  EXT_LIST="$EXT_LIST $TCEXTTOOLS_DEPENDS"
+
+  for EXT in $EXT_LIST
   do
-      tcz_load ${DEP} || return 1
+      tcz_load $EXT || return 1
   done
 
   return 0
 }
 
-print_it "Loading the dependencies in the list ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Loading the extensions ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/tools/packageit b/tools/packageit
--- a/tools/packageit
+++ b/tools/packageit
@@ -23,67 +23,67 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
 this_main() {
 
-  cd ${PACKAGE_ROOT}
+  cd $PACKAGE_ROOT
 
-  for EXTENSION in ${EXTENSIONS}
+  for EXTENSION in $EXTENSIONS
   do
-      if [ ! -d "${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}" ]; then
+      if [ ! -d "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION" ]; then
            print_it error "You must create it first!"
            exit 1
       fi
 
-      [ -d "${TCEXTTOOLS_PKG}/${EXTENSION}" ] || mkdir -p ${TCEXTTOOLS_PKG}/${EXTENSION}
+      [ -d "$TCEXTTOOLS_PKG"/"$EXTENSION" ] || mkdir -p "$TCEXTTOOLS_PKG"/"$EXTENSION"
 
-      busybox cp -f ${TCEXTTOOLS_EXTENSIONS}/${EXTENSION}/*.tcz* ${TCEXTTOOLS_PKG}/${EXTENSION} || return 1
+      busybox cp -f "$TCEXTTOOLS_EXTENSIONS"/"$EXTENSION"/*.tcz* "$TCEXTTOOLS_PKG"/"$EXTENSION" || return 1
   done
 
-  if [ -d "${PACKAGE_SRC}" ]; then
-       compressit xz ${PACKAGE_SRC} || return 1
-       SRC=$(basename ${PACKAGE_SRC}).tar.xz
-       busybox mv -f ${SRC} ${TCEXTTOOLS_PKG} || return 1
+  if [ -d "$PACKAGE_SRC" ]; then
+       compressit xz $PACKAGE_SRC || return 1
+       SRC=$(basename $PACKAGE_SRC).tar.xz
+       busybox mv -f $SRC $TCEXTTOOLS_PKG || return 1
   fi
 
-  [ ! "${SOURCE%.bz2}" = "${SOURCE}" ] && TYPE="bz2"
-  [ ! "${SOURCE%.gz}" = "${SOURCE}" ] && TYPE="gz"
-  [ ! "${SOURCE%.tgz}" = "${SOURCE}" ] && TYPE="tgz"
-  [ ! "${SOURCE%.xz}" = "${SOURCE}" ] && TYPE="xz"
-  [ ! "${SOURCE%.zip}" = "${SOURCE}" ] && TYPE="zip"
+  [ ! "${SOURCE%.bz2}" = "$SOURCE" ] && TYPE="bz2"
+  [ ! "${SOURCE%.gz}" = "$SOURCE" ] && TYPE="gz"
+  [ ! "${SOURCE%.tgz}" = "$SOURCE" ] && TYPE="tgz"
+  [ ! "${SOURCE%.xz}" = "$SOURCE" ] && TYPE="xz"
+  [ ! "${SOURCE%.zip}" = "$SOURCE" ] && TYPE="zip"
 
-  if [ "X${TYPE}" = "Xbz2" ]; then
-       if [ -e ${TCEXTTOOLS_SRC}/${SOURCE%.bz2}.xz ]; then
-            busybox cp -f ${TCEXTTOOLS_SRC}/${SOURCE%.bz2}.xz ${TCEXTTOOLS_PKG} || return 1
+  if [ "$TYPE" = "bz2" ]; then
+       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.bz2}.xz" ]; then
+            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.bz2}.xz" $TCEXTTOOLS_PKG || return 1
        fi
-  elif [ "X${TYPE}" = "Xgz" ]; then
-       if [ -e ${TCEXTTOOLS_SRC}/${SOURCE%.gz}.xz ]; then
-            busybox cp -f ${TCEXTTOOLS_SRC}/${SOURCE%.gz}.xz ${TCEXTTOOLS_PKG} || return 1
+  elif [ "$TYPE" = "gz" ]; then
+       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.gz}.xz" ]; then
+            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.gz}.xz" $TCEXTTOOLS_PKG || return 1
        fi
-  elif [ "X${TYPE}" = "Xtgz" ]; then
-       if [ -e ${TCEXTTOOLS_SRC}/${SOURCE%.tgz}.tar.xz ]; then
-            busybox cp -f ${TCEXTTOOLS_SRC}/${SOURCE%.tgz}.tar.xz ${TCEXTTOOLS_PKG} || return 1
+  elif [ "$TYPE" = "tgz" ]; then
+       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.tgz}.tar.xz" ]; then
+            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.tgz}.tar.xz" $TCEXTTOOLS_PKG || return 1
        fi
-  elif [ "X${TYPE}" = "Xxz" ]; then
-       busybox cp -f ${TCEXTTOOLS_SRC}/${SOURCE} ${TCEXTTOOLS_PKG} || return 1
-  elif [ "X${TYPE}" = "Xzip" ]; then
-       if [ -e ${TCEXTTOOLS_SRC}/${SOURCE%.zip}.tar.xz ]; then
-            busybox cp -f ${TCEXTTOOLS_SRC}/${SOURCE%.zip}.tar.xz ${TCEXTTOOLS_PKG} || return 1
+  elif [ "$TYPE" = "xz" ]; then
+       busybox cp -f "$TCEXTTOOLS_SRC"/"$SOURCE" $TCEXTTOOLS_PKG || return 1
+  elif [ "$TYPE" = "zip" ]; then
+       if [ -e "$TCEXTTOOLS_SRC"/"${SOURCE%.zip}.tar.xz" ]; then
+            busybox cp -f "$TCEXTTOOLS_SRC"/"${SOURCE%.zip}.tar.xz" $TCEXTTOOLS_PKG || return 1
        fi
   fi
 
   return 0
 }
 
-print_it "Packaging the package ${PACKAGE} ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+print_it "Packaging the package $PACKAGE ... \c"
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
diff --git a/tools/stripit b/tools/stripit
--- a/tools/stripit
+++ b/tools/stripit
@@ -23,40 +23,40 @@
 
 TCEXTTOOLS_ROOT=$(dirname $0)/..
 
-if [ -f "${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions" ]; then
-     . ${TCEXTTOOLS_ROOT}/etc/tc-ext-tools/functions
+if [ -f "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions ]; then
+     . "$TCEXTTOOLS_ROOT"/etc/tc-ext-tools/functions
 else
-     echo "${RED}$(basename ${0}):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
+     echo "${RED}$(basename $0):${BLUE} tc-ext-tools functions file not found!${NORMAL}"
      exit 1
 fi
 
-TARGET_DIR="${1}"
+TARGET_DIR="$1"
 
 print_usage(){
   echo -e "${TCEXTTOOLS_ERROR_COLOR}Usage:${TCEXTTOOLS_MESSAGE_COLOR}\n$(basename $0) /path/to/directory${NORMAL}"
 }
 
-if [ -z "${TARGET_DIR}" -o ! -d ${TARGET_DIR} ]; then
+if [ -z "$TARGET_DIR" -o ! -d "$TARGET_DIR" ]; then
       print_usage
       exit 1
 fi
 
 this_main() {
 
-  EXE_LIST=$(sudo find ${TARGET_DIR} | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
-  SO_LIST=$(sudo find ${TARGET_DIR} | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+  EXE_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "executable" | grep ELF | grep "not stripped" | cut -f 1 -d :)
+  SO_LIST=$(sudo find "$TARGET_DIR" | xargs sudo file | grep "shared object" | grep ELF | grep "not stripped" | cut -f 1 -d :)
 
-  if [ -n "${EXE_LIST}" ]; then
-       for i in ${EXE_LIST}
+  if [ -n "$EXE_LIST" ]; then
+       for i in $EXE_LIST
        do
-           sudo strip --strip-unneeded ${i} || return 1
+           sudo strip --strip-unneeded "$i" || return 1
        done
   fi
 
-  if [ -n "${SO_LIST}" ]; then
-       for i in ${SO_LIST}
+  if [ -n "$SO_LIST" ]; then
+       for i in $SO_LIST
        do
-           sudo strip -g ${i} || return 1
+           sudo strip -g "$i" || return 1
        done
   fi
 
@@ -64,8 +64,8 @@ this_main() {
 }
 
 print_it "Stripping the files in the target directory ... \c"
-this_main > ${TCEXTTOOLS_ERROR_LOG_2} 2>&1
-if [ $? -gt 0 ]; then
+this_main > $TCEXTTOOLS_ERROR_LOG_2 2>&1
+if [ "$?" -gt 0 ]; then
      print_it error "failed!"
      exit 1
 fi
