- Updated tc-ext-tools

diff --git a/tools/encryptit b/tools/encryptit
--- a/tools/encryptit
+++ b/tools/encryptit
@@ -37,24 +37,47 @@ fi
 
 if [ ! -f "$PACKAGE_PACKAGE" ]; then
        print_it error "You must package it first!"
-       return 1
+       exit 1
 fi
 
 this_main() {
 
-   echo "" > "$PACKAGE_MESSAGE_LOG_2"
+   echo "---------------------------------------------------------------" > "$PACKAGE_MESSAGE_LOG_2"
+   echo "" >> "$PACKAGE_MESSAGE_LOG_2"
    echo "Encrypting the package $PACKAGE ..." >> "$PACKAGE_MESSAGE_LOG_2"
+   echo "" >> "$PACKAGE_MESSAGE_LOG_2"
+   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
 
+   echo -e "Checking if the package $PACKAGE tarball encrypted exists ... \c" >> "$PACKAGE_MESSAGE_LOG_2"
    if [ -f "$PACKAGE_PACKAGE_ENCRYPTED" ]; then
-        echo "The package tarball encrypted detected, deleting it." >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "yes" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "Removing the package $PACKAGE tarball encrypted." >> "$PACKAGE_MESSAGE_LOG_2"
         sudo rm -f "$PACKAGE_PACKAGE_ENCRYPTED"
+   else
+        echo "no" >> "$PACKAGE_MESSAGE_LOG_2"
    fi
 
+   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
+   echo "Running bcrypt to encrypt the package $PACKAGE tarball."  >> "$PACKAGE_MESSAGE_LOG_2"
+   echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
    print_it "Please enter the encryption key: \c"
    print_it hilight "$PACKAGE_ENCRYPTION_KEY"
-   bcrypt "$PACKAGE_PACKAGE" || return 1
+   bcrypt "$PACKAGE_PACKAGE"
 
-   echo "Encrypted the package $PACKAGE successfully." >> "$PACKAGE_MESSAGE_LOG_2"
+   if [ "$?" -gt 0 ]; then
+        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "Encrypting the package $PACKAGE failed." >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
+        return 1
+   else
+        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "Encrypted the package $PACKAGE successfully." >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "" >> "$PACKAGE_MESSAGE_LOG_2"
+        echo "---------------------------------------------------------------" >> "$PACKAGE_MESSAGE_LOG_2"
+   fi
 
    return 0
 
diff --git a/tools/splitit b/tools/splitit
--- a/tools/splitit
+++ b/tools/splitit
@@ -42,23 +42,28 @@ fi
 
 this_split() {
 
+   echo "---------------------------------------------------------------"
    echo "Getting the contents of the extension install."
+   echo "---------------------------------------------------------------"
    CONTENTS=$(cat $PACKAGE_EXTENSION_INSTALL)
    if [ -z "$CONTENTS" ]; then
         echo "Warning! The extension install is empty."
    fi
 
-   echo "Touching install.list and x-install.list files."
+   echo "---------------------------------------------------------------"
+   echo "Creating the include list and the exclude list files."
+   echo "---------------------------------------------------------------"
    LIST="${PACKAGE_BIN_TEMP}/install.list"
    X_LIST="${PACKAGE_BIN_TEMP}/x-install.list"
    touch "$LIST"
    touch "$X_LIST"
 
-   echo "Processing the extension install contents."
    cd "$PACKAGE_INSTALL_ROOT"
    for i in ${CONTENTS-.}
    do
-       echo "Processing the content $i."
+       echo "---------------------------------------------------------------"
+       echo "Processing the content $i"
+       echo "---------------------------------------------------------------"
 
        echo -e "Checking if the content is commented out ... \c"
        if [ "${i#\#}" != "$i" ]; then
@@ -68,7 +73,7 @@ this_split() {
             echo "no"
        fi
 
-       echo "Evaluating the content $i."
+       echo "Evaluating the content $i"
        i=$(eval echo "$i")
 
        echo -e "Checking if a special wildcard used ... \c"
@@ -99,16 +104,20 @@ this_split() {
        fi
    done
 
+   echo "---------------------------------------------------------------"
    echo "Creating the extension contents tarball from the include and the exclude lists."
+   echo "---------------------------------------------------------------"
    sudo tar -T "$LIST" -X "$X_LIST" -cvpzf "$PACKAGE_BIN_TEMP/pkg.tar.gz" || return 1
 
    echo "Cleaning the package extension bin directory."
    [ -d "$PACKAGE_EXTENSION_BIN" ] && sudo rm -rf "$PACKAGE_EXTENSION_BIN"
    sudo mkdir -p "$PACKAGE_EXTENSION_BIN"
 
+   echo "---------------------------------------------------------------"
    echo "Extracting the extension contents tarball to the extension bin directory."
+   echo "---------------------------------------------------------------"
    sudo mkdir -p "$PACKAGE_EXTENSION_BIN"
-   sudo tar -C "$PACKAGE_EXTENSION_BIN" -pvxzf "$PACKAGE_BIN_TEMP/pkg.tar.gz" || return 1
+   sudo tar -C "$PACKAGE_EXTENSION_BIN" -pxzf "$PACKAGE_BIN_TEMP/pkg.tar.gz" || return 1
 
    echo "Cleaning the extension bin temporary directory."
    sudo rm -rf "$PACKAGE_BIN_TEMP"
@@ -119,30 +128,43 @@ this_split() {
 
 this_main() {
 
+   echo "---------------------------------------------------------------"
    echo ""
    echo "Splitting the package $PACKAGE extensions ..."
+   echo ""
+   echo "---------------------------------------------------------------"
 
    for EXTENSION in $EXTENSIONS
    do
        set_extension
 
+       echo "---------------------------------------------------------------"
+       echo "Splitting the package extension $PACKAGE_EXTENSION_NAME"
+       echo "---------------------------------------------------------------"
+
        echo "Cleaning the package bin temporary directory."
        [ -d "$PACKAGE_BIN_TEMP" ] && sudo rm -rf "$PACKAGE_BIN_TEMP"
        mkdir -p "$PACKAGE_BIN_TEMP"
 
-       echo "Splitting the extension $PACKAGE_EXTENSION_NAME."
        this_split
        if [ "$?" -gt 0 ]; then
-            echo "Error! splitting the extension $PACKAGE_EXTENSION_NAME failed."
+            echo "---------------------------------------------------------------"
+            echo "Error! splitting the package extension $PACKAGE_EXTENSION_NAME failed."
+            echo "---------------------------------------------------------------"
             sudo rm -rf "$PACKAGE_BIN_TEMP"
             return 1
        else
-            echo "Splitting the extension $PACKAGE_EXTENSION_NAME successful."
+            echo "---------------------------------------------------------------"
+            echo "Splitting the package extension $PACKAGE_EXTENSION_NAME successful."
+            echo "---------------------------------------------------------------"
        fi
    done
 
+   echo "---------------------------------------------------------------"
    echo ""
    echo "Splitted the package $PACKAGE extensions successfully."
+   echo ""
+   echo "---------------------------------------------------------------"
 
    return 0
 
