Fixed Issue 3: ICON= problems with no new line at the end of desktop files

diff --git a/tools/splitit b/tools/splitit
--- a/tools/splitit
+++ b/tools/splitit
@@ -138,10 +138,57 @@ this_split() {
         do
             link_full=`dirname $link`/`readlink $link`
             link_full=${link_full#$PACKAGE_EXTENSION_BIN}
-            echo "link_full=$link_full"
-            echo "link=$link"
+            echo "Linking the link $link to the full path link $link_full"
             sudo ln -sf "$link_full" "$link"
         done
+   fi
+
+   echo -e "Checking if the extension has a tce.installed script ... \c"
+   if [ -f "$PACKAGE_EXTENSION_TCEINSTALLED" ]; then
+        echo "yes"
+        echo "Installing the extension tce.installed script"
+        sudo install -D -m 775 "$PACKAGE_EXTENSION_TCEINSTALLED" "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed/$PACKAGE_EXTENSION_NAME" || return 1
+        sudo chown -R root:staff "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed" || return 1
+        sudo chmod -R 775 "$PACKAGE_EXTENSION_BIN/usr/local/tce.installed" || return 1
+   else
+        echo "no"
+   fi
+
+   echo -e "Checking if the extension icon is set ... \c"
+   if [ -n "$PACKAGE_EXTENSION_ICON" ]; then
+        echo "yes"
+
+        echo -e "Checking if the extension desktop file exists ... \c"
+        if [ -f "$PACKAGE_EXTENSION_DESKTOP" ]; then
+             echo "yes"
+
+             echo -e "Checking if the extension desktop file has new line at the end ... \c"
+             if [ "$(tail -c 1 $PACKAGE_EXTENSION_DESKTOP)" = "" ]; then
+                  echo "yes"
+             else
+                  echo "no"
+                  echo "Adding new line at the end of extension desktop file"
+                  sudo sh -c "echo >> $PACKAGE_EXTENSION_DESKTOP"
+             fi
+
+             echo -e "Checking if the extension desktop has X-FullPathIcon line ... \c"
+             if [ $(grep "X-FullPathIcon=" "$PACKAGE_EXTENSION_DESKTOP") ]; then
+                  echo "yes"
+                  echo "Deleting the line with X-FullPathIcon"
+                  sudo sed -i -e "/X-FullPathIcon=/d" "$PACKAGE_EXTENSION_DESKTOP"
+             else
+                  echo "no"
+             fi
+
+             echo "Adding the extension icon to the extension desktop file"
+             sudo sh -c "echo \"X-FullPathIcon=$PACKAGE_EXTENSION_ICON\" >> $PACKAGE_EXTENSION_DESKTOP" || return 1
+        else
+             echo "no"
+             echo "Error! The extension desktop file can not be found but the icon is set."
+             return 1
+        fi
+   else
+        echo "no"
    fi
 
    echo "Cleaning the package extension bin temporary directory"
