- Updated tc-ext-tools

diff --git a/tools/unpackit b/tools/unpackit
--- a/tools/unpackit
+++ b/tools/unpackit
@@ -49,7 +49,7 @@ this_main() {
 
    echo "Cleaning the package src temporary directory"
    [ -d "$PACKAGE_SRC_TEMP" ] && sudo rm -rf "$PACKAGE_SRC_TEMP"
-   mkdir -p "$PACKAGE_SRC_TEMP"
+   mkdir -p "$PACKAGE_SRC_TEMP" || return 1
 
    if [ -f "$PACKAGE_SOURCE_CONV" ] || [ "$PACKAGE_SOURCE_TYPE" = "tarbz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "targz" ] ||
       [ "$PACKAGE_SOURCE_TYPE" = "tgz" ] || [ "$PACKAGE_SOURCE_TYPE" = "tbz2" ] || [ "$PACKAGE_SOURCE_TYPE" = "tarxz" ] ||
@@ -71,7 +71,7 @@ this_main() {
         build_unpack || return 1
    else
         echo "---------------------------------------------------------------"
-        echo "Error, unsupported source type!"
+        echo "Error! Unsupported source type."
         echo "---------------------------------------------------------------"
         return 1
    fi
